### PR TITLE
Modified Drum kit and change its theme

### PR DESCRIPTION
**Pull request by aditidewangan**
image
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by aditidewangan** [comment]
I made some changes in Drumkit. I changed the drum theme and it make a different different sound by clicking on the particular drum. I hope this changes is really helpful for this issue.

**Comment by harshgupta20** [comment]
Hi @aditidewangan Please resolve the conflicts.

**Comment by harshgupta20** [comment]
Hello @aditidewangan Kindly reply in 2 days or we need close this issue.

**Comment by aditidewangan** [comment]
Okay @harshgupta20 I try to resolve the conflicts.

**Comment by aditidewangan** [comment]
What is the problem in my changes?

**Comment by 991rajat** [comment]
Actually someone else was also working who changed few things around to add some new feat.
What you need to do is to accept both changes i.e your changes + current changes. So that your changes reflect without affecting current changes or you could change also.

**Comment by aditidewangan** [comment]
Okay but how can I accept the changes because this issue is not made by me.

**Comment by 991rajat** [comment]
what you can do pull the latest changes in main branch merge in your current branch. Or directly pull to current branch. After that you will be able to see merge conflict.

**Comment by aditidewangan** [comment]
Okay @991rajat

**Pull request merged**
