### PR TITLE
math_trainer app

### PR DESCRIPTION
**Pull request by Tanya933**
## Related Issue
Closes: #1183 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Checklist:

- [x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot 2021-04-28 at 22 38 28

### CODE REVIEW

**Comment by Tanya933** [comment]
@991rajat  @harshgupta20 @urvashi-code1255  .Please review the PR . Thankyou

**Comment by 991rajat** [comment]
@Tanya933 You haven't added any JS, CSS files.
Also add the project to script.js

**Review by 991rajat — APPROVED** [review]
Looks Good. Good Work

**Comment by 991rajat** [comment]
Congratulations on merging of first PR :tada: 
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
