### PR TITLE
Added some changes.

### PR DESCRIPTION
**Pull request by archana-9430**
Added the details of project "Simple Interest Calculator".

## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
@archana-9430 Did you created any issue related to this PR ?

**Comment by archana-9430** [comment]
> @archana-9430 Did you created any issue related to this PR ?

NO.

**Comment by archana-9430** [comment]
@Vishal-raj-1 , I've added the details of JavaScript Simple Interest Calculator in the Readme file.

**Comment by 991rajat** [comment]
@archana-9430 I don't see any project in commits.
Please create an issue for this and link it and 
Push the project as well.

**Comment by Vishal-raj-1** [comment]
Hello @archana-9430 You have already one PR for this purpose check my comment their.

**Pull request closed without merging**
