### PR TITLE
PIN code search

### PR DESCRIPTION
**Pull request by TidbitsJS**
Closes: #505 

### Describe the changes you've made
Added the project "PIN code Tracker" with real data fetching, which will provide the location info of that particular PIN code. & it's responsive!

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Demo
https://tidbitsjs.github.io/Awesome-JavaScript-Projects/

### CODE REVIEW

**Comment by TidbitsJS** [comment]
Kindly review @harshgupta20 & @urvashi-code1255 :) 
( Else I will have to keep adding comments of merge conflicts resolve 😂 )

**Comment by urvashi-code1255** [comment]
@TidbitsJS Please resolve them again.

**Comment by TidbitsJS** [comment]
> @TidbitsJS Please resolve them again.

Yes, done :)

**Comment by urvashi-code1255** [comment]
Hey @TidbitsJS Can you share hosted link of your fork on GitHub pages

**Comment by TidbitsJS** [comment]
> Hey @TidbitsJS Can you share hosted link of your fork on GitHub pages

Here you go - https://tidbitsjs.github.io/Awesome-JavaScript-Projects/
( I have set it to the main branch )

**Comment by TidbitsJS** [comment]
@urvashi-code1255, can you let me know whether the PR is good or not so that I can make changes over here? ( or else I will start working on the other issue's PR )

**Review by urvashi-code1255 — APPROVED** [review]
Thanks for contributing @TidbitsJS and sorry for the delay!

You can start working on the other issue assigned to you :)

**Pull request merged**
