### PR TITLE
Memory game

### PR DESCRIPTION
**Pull request by Amit366**
Closes: #591 

### Describe the changes you've made
Added Memory game

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Amit366** [comment]
@ridsuteri please review

**Comment by 991rajat** [comment]
@Amit366  Look into this. It's not working.
image

**Comment by Amit366** [comment]
@991rajat check now

**Comment by 991rajat** [comment]
Looks Good.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution.
Keep Contributing.

**Comment by Amit366** [comment]
@991rajat is there any issue which is open??

**Comment by 991rajat** [comment]
@Amit366 I opend a issue Named fix images find it comment there will assign you

**Pull request merged**
