### PR TITLE
Beautified contact page

### PR DESCRIPTION
**Pull request by fatma-sia27**
Hey @Vishal-raj-1 , issue #515 was assigned to me . So I had made some changes in the contact form in order to make it more beautiful. My changes are : I had added background color to the form , added hover effect on 'submit' and 'cartonik' button and also added placeholder property . 
Please review it and let me know if you find any changes in it , otherwise I request you to please merge my first PR.

Thank you
WhatsApp Image 2021-04-03 at 10 20 27 AM

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@fatma-sia27 the changes are not reflecting on my side...also you changed expanding card's files in the PR...
i guess you have not made the PR correctly...
so i would suggest making a fresh PR since you are a begineer and change only the necessary files
Also do let us (mentors) know if you need any help with your first PR 😁😁

**Comment by fatma-sia27** [comment]
> @fatma-sia27 the changes are not reflecting on my side...also you changed expanding card's files in the PR...
> i guess you have not made the PR correctly...
> so i would suggest making a fresh PR since you are a begineer and change only the necessary files
> Also do let us (mentors) know if you need any help with your first PR 😁😁

Yes please guide me with the steps I should follow to make my first PR. Since I am beginner so I have no idea that how to make PR . Please help.
Thank you

**Comment by ridsuteri** [comment]
> > @fatma-sia27 the changes are not reflecting on my side...also you changed expanding card's files in the PR...
> > i guess you have not made the PR correctly...
> > so i would suggest making a fresh PR since you are a begineer and change only the necessary files
> > Also do let us (mentors) know if you need any help with your first PR 😁😁
> 
> Yes please guide me with the steps I should follow to make my first PR. Since I am beginner so I have no idea that how to make PR . Please help.
> Thank you

@fatma-sia27 kindly follow this article : https://opensource.com/article/19/7/create-pull-request-github

**Comment by harshgupta20** [comment]
@fatma-sia27 Any update?
Kindly reply within 2 days or i have to close it.

**Comment by fatma-sia27** [comment]
> @fatma-sia27 Any update?
> Kindly reply within 2 days or i have to close it.

Hey @harshgupta20 Please give me time of 3 days I will do it. Also please tell me I should make another PR right?

**Comment by fatma-sia27** [comment]
Hey @harshgupta20 , I had made change in this PR . Please review this PR.
Thank you

**Comment by Vishal-raj-1** [comment]
@fatma-sia27 Please resolve this, If You are not comfortable to resolve this I would say Update Your local main branch, then take a new branch and then do required changes !! 

```
Conflicting files
public/ExpandingCard.html
script.js
```

**Pull request closed without merging**
