### PR TITLE
Add Proxy Pattern Two way Binding and validator Sample

### PR DESCRIPTION
**Pull request by mghanatabady**
## Related Issue
Add Two way binding sample by proxy pattern sample #1247

Closes: #1247

### Describe the changes you've made
I have updated script.js and add an HTML and an image to project

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
It is simple and hasn't got any thing unusual
### Checklist:

- [ *] My code follows the style guidelines of this project.
- [*] I have performed a self-review of my own code.
- [*] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [*] New and existing unit tests pass locally with my changes.

### Screenshots
TwoWayBinding

### CODE REVIEW

**Comment by 991rajat** [comment]
@mghanatabady Looks Good. Few Changes
1. When adding I don't see any changes in the UI, was this way the code was done? It would be great if Age can also been seen.
2. In script.js its png not PNGdue to this image not loading.
3. It would be great if you could add some css, If don't know css don't worry, leave it Fix(1,2)

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?

**Comment by mghanatabady** [comment]
> @mghanatabady Looks Good. Few Changes
> 
> 1. When adding I don't see any changes in the UI, was this way the code was done? It would be great if Age can also been seen.
> 2. In script.js its png not PNGdue to this image not loading.
> 3. It would be great if you could add some css, If don't know css don't worry, leave it Fix(1,2)
>    Properly link the issue in description too
>    Its like Closes #PRNO

1- I'm working on it
2- I'm changing the image file
3- It's a good idea but I think so this example  should be simple in UI and the code reader can focus only on pure code

**Review by 991rajat — APPROVED** [review]
Looks Good.

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing.

**Comment by mghanatabady** [comment]
> Congratulations on merging of first PR. 🎉
> Keep Contributing.

Thank you Indeed, Ok I will.

**Pull request merged**
