### PR TITLE
Check the Train details #1404

### PR DESCRIPTION
**Pull request by WebVishal**
Hi @991rajat  & @Vishal-raj-1 check PR I complete task  #1404 

I have added a Screenshot

Screenshot (3)
Screenshot (2)

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@WebVishal Resolve merge conflicts first

**Comment by WebVishal** [comment]
> @WebVishal Resolve merge conflicts first
hey @Vishal-raj-1 when I have complete the resolve conflicts after that show me 
"This page is out of date. Start over" can you help me, how to I can remove it.

**Comment by Vishal-raj-1** [comment]
@WebVishal Just do git pull upstream master then git push

**Comment by Vishal-raj-1** [comment]
for info check [this](https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch#:~:text=make%20sure%20you've%20checked%20out%20your%20branch%3A%20git%20checkout,of%2Ddate%20is%20blocking%20your)

**Pull request merged**
