### PR TITLE
css box shadow added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
css box shadow added
Closes: #1325

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/117844589-6c35b200-b29d-11eb-8624-0253081e9f8e.mp4

Document - Google Chrome 11-05-2021 20_25_26

### CODE REVIEW

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR .

**Comment by Ankita297** [comment]
@991rajat Please review my PR .

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR .

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 :)

**Pull request merged**
