### PR TITLE
Make Speech Recognization

### PR DESCRIPTION
**Pull request by Goheljay**
## Related Issue
  - Info about Issue or bug

Closes: #494 

### Describe the changes you've made
I have to add javascript Project Speech recognization. which is convert speech to text.
In this project not use any external speech -recognization API or other API and External library.
### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

speech-reco
speech-recognization

### CODE REVIEW

**Comment by Goheljay** [comment]
Please Review it and Marged my PR.

**Comment by 991rajat** [comment]
@Goheljay  Great Work.
Resolve the conflict please.

**Comment by Goheljay** [comment]
how can I solve this conflict? can you help me???

**Review by 991rajat — APPROVED** [review]
Great Work

**Comment by 991rajat** [comment]
Thanks for your contribution. :star_struck: 
Keep Contributing

**Pull request merged**
