### PR TITLE
added a new game

### PR DESCRIPTION
**Pull request by neha07kumari**
## Related Issue
  - Click Shape Javascript game.

Closes: #1282 

### Describe the changes you've made
Added the game Click Shape.

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Click Circles JavaScript Game

Click Circles JavaScript Game

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@neha07kumari kindly add this project and it's gif to script.js file :)

**Comment by neha07kumari** [comment]
> @neha07kumari kindly add this project and it's gif to script.js file :)

Done.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@neha07kumari there are conflicts  and the image is also not showing up in the project card in the script.js file also the css and js files are also not linked properly with the html file

**Comment by neha07kumari** [comment]
> @neha07kumari there are conflicts and the image is also not showing up in the project card in the script.js file also the css and js files are also not linked properly with the html file

@ridsuteri Now it's working. Please check it.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
the img is still not loading up in the project card , bcz of it's name try renaming it without spaces and the conflicts still persists , resolve it too
also please check locally before pushing it to remote :)

**Review by ridsuteri — APPROVED** [review]
good work @neha07kumari :)

**Pull request merged**
