### PR TITLE
Project addition : Koch snowflake

### PR DESCRIPTION
**Pull request by jhamadhav**
## Related Issue

Project `Koch Snowflake` added.

Closes: #1098 

### Describe the changes you've made

The Koch snowflake (also known as the Koch curve, Koch star, or Koch island) is a fractal curve and one of the earliest fractals to have been described. It is based on the Koch curve, which appeared in a 1904 paper titled "On a Continuous Curve Without Tangents, Constructible from Elementary Geometry" by the Swedish mathematician Helge von Koch.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by jhamadhav** [comment]
@urvashi-code1255 please review the PR!
and add GSSOC21 and level tag too.

**Comment by 991rajat** [comment]
Add the project to script.js. Reduce the size of gif too.
Also squash the commits too, if possible.

**Comment by jhamadhav** [comment]
@991rajat I have added my project to `script.js`. and this project has no gif.

for squash, I tried `git rebase -i HEAD~6` but it shows commits of different people and not of this project, so please squash the commits via UI.

**Comment by 991rajat** [comment]
Looks Good. Great Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
