### PR TITLE
Mouse trails

### PR DESCRIPTION
**Pull request by Ayushjain2205**
## Related Issue

Closes: #924 

### Describe the changes you've made
Added mouse trails effect. On mouse movement creates and moves balls of various sizes and colour

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
screenrecording-chunk-1

### CODE REVIEW

**Comment by Ayushjain2205** [comment]
@991rajat  Please review this PR

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing.

**Comment by 991rajat** [comment]
Learn about squashing the commits. It's a good pratice.

**Comment by Ayushjain2205** [comment]
> Learn about squashing the commits. It's a good pratice.

Sure! Thanks for the feedback, will work on it!

**Pull request merged**
