### PR TITLE
Added Falling Bullets Animation JS

### PR DESCRIPTION
**Pull request by Fab-Gaurav**
## Related Issue
Issue :  https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/issues/651

### Describe the changes you've made
added new file:   public/FallingBulletsAnimation.html
added new file:   assets/css/FallingBulletsAnimation.css
added new file:   assets/js/FallingBulletsAnimation.js
and modified:   script.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Falling Bullets Animation JS

### CODE REVIEW

**Comment by Fab-Gaurav** [comment]
@991rajat Kindly review this

**Comment by Fab-Gaurav** [comment]
@991rajat , @Vishal-raj-1 , @urvashi-code1255 
Please have a look on the change


### Mentioning the present update of Background Change
FallingBulletsAnimation

Review my PR

**Comment by harshgupta20** [comment]
@Fab-Gaurav , It consist some conflicts i script.js file, Kindly look into it and resolve it.

**Comment by Fab-Gaurav** [comment]
> @Fab-Gaurav , It consist some conflicts in script.js file, Kindly look into it and resolve it.

**Pull request closed without merging**
