### PR TITLE
Lyrics App

### PR DESCRIPTION
**Pull request by TidbitsJS**
Closes: #614 

### Describe the changes you've made
Created lyrics search application.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Demo
https://tidbitsjs.github.io/Awesome-JavaScript-Projects/

### CODE REVIEW

**Comment by TidbitsJS** [comment]
Kindly review @urvashi-code1255 & @991rajat :)

**Review by 991rajat — CHANGES_REQUESTED** [review]
Excellent Work
One Suggestion When Nothing found display something like "No Result Found" Whatever message you feel like. It can be image or text.

**Comment by TidbitsJS** [comment]
Kindly review @Vishal-raj-1 :) 
So that I can work on the next issue.

**Comment by Vishal-raj-1** [comment]
@TidbitsJS  I am not able to find lyrics of the song & if I search one item then I can't search second thing again. Have a look at the issue.

https://user-images.githubusercontent.com/59874304/113476182-8b1f7800-9497-11eb-9327-ab2f70ab7a41.mp4

**Comment by TidbitsJS** [comment]
@Vishal-raj-1, it seems a problem with CORS policy. It's returning a result for few items & for a few, it's not.
About searching, you have to wait a little bit, till the fetch operation completes & returns the result. The soon you hit the search button again & again, it will send another request & thus it will take time :)

**Comment by Vishal-raj-1** [comment]
Okay Then you can raise the issue and we will merge this PR for now. @991rajat Please merge this PR for now

**Review by 991rajat — APPROVED** [review]
Great Work

**Comment by 991rajat** [comment]
Congratulations of merging of first PR. :tada: 
Keep Contributing.

**Comment by TidbitsJS** [comment]
> Congratulations of merging of first PR. 
> Keep Contributing.

Thank you :)

**Pull request merged**
