### PR TITLE
Dynamic calendar

### PR DESCRIPTION
**Pull request by satyampgt4**
## Related Issue
  - Dynamic calendar you can go to any particular month or date
  -  It will show the calendar of current month with highlighting current date Dynamically

Closes: #220

#### script.js
* Add calendar project

####  public/calendar.html 
* html of the project
 
#### assets/css/calander.css
* css of the project

####  assets/js/calendar.js
* java script  of the project

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
Na

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
cal

### CODE REVIEW

**Comment by satyampgt4** [comment]
@urvashi-code1255 please add GSSOC 2021 label

**Comment by satyampgt4** [comment]
@urvashi-code1255  conflict  has resolved

**Review by urvashi-code1255 — APPROVED** [review]
Its looking good to me @satyampgt4 :)

**Comment by satyampgt4** [comment]
@urvashi-code1255 please add GSSOC 2021 and level label to pr also as #220

**Pull request merged**
