### PR TITLE
Expand and collapse card

### PR DESCRIPTION
**Pull request by Amrutha1101**
## Related Issue
  - Info about Issue or bug

Closes: #1488 

### Describe the changes you've made
1.expand and collapse
2. changed UI of the page

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (166)

### CODE REVIEW

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Hey, please pull the latest changes before making a pr. I see many commits have been reverted in this pr.

**Comment by Amrutha1101** [comment]
I think I messed up with something again as I received not message run failed

**Comment by Amrutha1101** [comment]
*bot message

**Review by Rizwan-S — APPROVED** [review]
Looks great!!!

**Pull request merged**
