### PR TITLE
Fixed Issue number #573 (Collapse Plugin not working under Navbar section in lower screen dimension)

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issue
  - Collapse plugin was not working under lower screen dimension in the navbar section.

Closes: #573 

### Describe the changes you've made
An Id was not created for targeting the data target so that toggler button to work so i created an id of same name as that of data target.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Review by urvashi-code1255 — APPROVED** [review]
Thanks for contributing @abhijeet141 :)

**Comment by abhijeet141** [comment]
> Thanks for contributing @abhijeet141 :)
               
   Welcome 😊

**Comment by abhijeet141** [comment]
Respected mentors the GSSOC21 label is not correct thats why i did not got any points on this PR can you please correct the label 
image
@urvashi-code1255 @ridsuteri

**Comment by ridsuteri** [comment]
@abhijeet141 corrected :)

**Comment by abhijeet141** [comment]
> @abhijeet141 corrected :)

Thank You 😊

**Pull request merged**
