### PR TITLE
Mapping_Earthquakes_Data

### PR DESCRIPTION
**Pull request by iamabhii1**
## Related Issue
-Added project which  shows **_Mapping_Earthquakes_Data_**  
  

Closes: #645 

### Describe the changes you've made
:This is about _**Mapping Earthquake Data**_ on world map showing earthquakes location and there intensity using government (usgs) API.
:I have added a html , JavaScript and image file(icon) in this project ,along with i have used  usgs government API's for showcasing the earthquakes  data intensity  on world map . Used mapbox API for world map .  
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
As such there are no unusual behaviour but the API's takes some time for fetching/showing the data on Map.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (12)

### CODE REVIEW

**Comment by iamabhii1** [comment]
created a pull request for issue #645  **_Mapping_Earthquakes_Data_**

**Review by urvashi-code1255 — CHANGES_REQUESTED** [review]
@iamabhii1 
1. Seperate the css file.
2. Add your project's details in main script.js
3. Pull the recent changes.

**Review by iamabhii1 — COMMENTED** [review]
please check if there is anything left  from my side?

**Comment by iamabhii1** [comment]
Hi , I just wanted to reupdated the script.js file with  **_Mapping_Earth_Quakedata.gif_** 
can i do this in this only ?
or should i create a new issue ?

**Pull request merged**
