### PR TITLE
Added the Custom Countdown Project

### PR DESCRIPTION
**Pull request by K-jais**
It solves issue #1147 

Its working video,

https://user-images.githubusercontent.com/75881393/115986272-0d99e400-a5cd-11eb-9528-ec3ecb910a45.mp4

### CODE REVIEW

**Comment by K-jais** [comment]
Please @ridsuteri @urvashi-code1255 @991rajat review this PR.

**Review by ridsuteri — APPROVED** [review]

**Comment by ridsuteri** [comment]
good work @K-jais , thanks for contributing :)

**Comment by K-jais** [comment]
Sir @ridsuteri isn't it supposed to be a level 2 PR ?

**Comment by ridsuteri** [comment]
@K-jais srry my bad

**Comment by K-jais** [comment]
No problem sir

**Pull request merged**
