### PR TITLE
Add Dice Game

### PR DESCRIPTION
**Pull request by iamrishavraj1**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by iamrishavraj1** [comment]
screencapture-file-F-GSSOC-21-Awesome-JavaScript-Projects-public-diceGame-html-2021-03-13-15_45_48

**Review by urvashi-code1255 — COMMENTED** [review]
@iamrishavraj1 Please add your project details in script.js like other projects

Also pull the recent changes

**Comment by iamrishavraj1** [comment]
Done Mam :)

**Comment by urvashi-code1255** [comment]
@iamrishavraj1 You haven't resolved the merge conflicts

**Comment by iamrishavraj1** [comment]
> @iamrishavraj1 You haven't resolved the merge conflict
Done Mam :)

**Comment by iamrishavraj1** [comment]
Mam, Please Review My PR

**Comment by 991rajat** [comment]
Project is not visible at main page. Please look into it.
Link the issue no.
Squash the commits.
Let me know if needed any help.

**Pull request closed without merging**
