### PR TITLE
make Awesome snake game

### PR DESCRIPTION
**Pull request by Marim99**
## Related Issue
  - make Awesome snake game

Closes: #685
### Describe the changes you've made
Add AwesomeSnakeGame.js file in assets/js
Add AwesomeSnakeGame.html file in public folder 
Add two audio in assets/sounds 
Add Gif in assets/GIFs
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:
AwesomeSnakeGame

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Marim99** [comment]
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri
 Please view my PR

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Marim99 project looks great ! , just resolve the merge conflicts

**Comment by Vishal-raj-1** [comment]
Thanks for your contribution !!

**Comment by Marim99** [comment]
thanks please can you make labels for it ,i'm participant in GSSoc 2021 @ridsuteri @Vishal-raj-1

**Pull request merged**
