### PR TITLE
Added Match_Four_Game

### PR DESCRIPTION
**Pull request by sreetu**
## Related Issue
  - Match Four Game

Closes: #1386 
### Describe the changes you've made
The project game is implemented.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

Screenshot (1070)

### CODE REVIEW

**Comment by sreetu** [comment]
Requesting @admins to review and merge my PR

**Comment by 991rajat** [comment]
Add the project to script.js.

**Comment by sreetu** [comment]
> Add the project to script.js.

Done Sir

**Comment by 991rajat** [comment]
Looks Good. Few Chagnges.
In Script.js lot of project are added again example like counter and many more.
Remove them only add your project.
If possible fix this If not able to do leave it fix the above point, After winning Don't let user to click, as after winning I click winner changes.

**Comment by sreetu** [comment]
> Looks Good. Few Chagnges.
> In Script.js lot of project are added again example like counter and many more.
> Remove them only add your project.
> If possible fix this If not able to do leave it fix the above point, After winning Don't let user to click, as after winning I click winner changes.

Actually, after resolving conflicts in script.js file ,it shows that other projects are also added by me so, should i delete them or not?

**Comment by sreetu** [comment]
I have solved 'after winning click' issue. Now winner will not change .

**Comment by 991rajat** [comment]
In Files Changed Section as you can see lot of projects added, There should only be your project lines be added, 
Other project will create duplicacy, Like these.
image

Just Remove them and only add your project,
If face any problem let us know.

**Comment by 991rajat** [comment]
Easiest way to do this 
Copy the script file from main branch of current repo,
Paste it in your branch(Replace)
Add the project and Push.

**Comment by sreetu** [comment]
Kindly review it now @991rajat sir

**Pull request merged**
