### PR TITLE
Animated counter(updated)

### PR DESCRIPTION
**Pull request by mahesh-11102**
## Related Issue
feature which I have made in the Animated Counter Js Project?

- Added a `button` on the left side of the page, **decreased** the counting speed , applied `shadow effect` to the container and decreased the **width** of the section , so that the the background image would look more appealing.
### 
**_Closes: #460_**

### Describe the changes you've made
I have added an `onclick` function in the **js** file , added a button as well as a `GIF` (so that the column looks satisfactory) in the **_html_** file and **_css_** effects on the button and some **_shadow effect_** to the container

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
 `NA` (updated and removed unnecessary files)

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have tested in my system.
- [x] New and existing unit tests pass locally with my changes.

### **_`Before` editing the project_**

image

### **_`After` editing the project_**

image

### CODE REVIEW

**Review by ridsuteri — APPROVED** [review]
well done @mahesh-11102 thanks for contributing :)

**Comment by mahesh-11102** [comment]
Hello @ridsuteri  @Vishal-raj-1  @urvashi-code1255  @991rajat  @harshgupta20 mentors , please add `GSSOC'21` and `level` label to the PR .
Thank you :-)

**Comment by mahesh-11102** [comment]
Sorry to disturb you @ridsuteri  sir , please add the `level` label to this PR :)

**Comment by ridsuteri** [comment]
done @mahesh-11102 :)

**Comment by mahesh-11102** [comment]
> done @mahesh-11102 :)

Thank you @ridsuteri  sir :-)

**Pull request merged**
