### PR TITLE
hover board project added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
hover board project added
Closes: #1546

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/119480190-094d1c00-bd6f-11eb-96a1-4c1047ff18c1.mp4

Document - Google Chrome 25-05-2021 15_21_29
Document - Google Chrome 25-05-2021 15_23_01

### CODE REVIEW

**Comment by Ankita297** [comment]
@ridsuteri  Sir Please review my PR .

**Comment by ridsuteri** [comment]
> @ridsuteri Sir Please review my PR .

yeah @Ankita297 , give me few minutes, I am reviewing all your PRs and assigning you the issues

**Comment by Ankita297** [comment]
okay Sir thank you for that

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 :)

**Pull request merged**
