### PR TITLE
Added Weather-App

### PR DESCRIPTION
**Pull request by Atif0604**
## Related Issue
  - Added  new Weather-app

Closes: #1774 will be closed through this PR](Add New version of weather app with good ui #1774)

### Describe the changes you've made
I've added a new weather app using unsplash api for dynamic changing of background and openweather api for the weather forecast

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [✔️ ] My code follows the style guidelines of this project.
- [ ✔️] I have performed a self-review of my own code.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.
- [ ✔️] I have made corresponding changes to the documentation.
- [ ✔️] New and existing unit tests pass locally with my changes.

### Screenshots
Weather-App

### CODE REVIEW

**Comment by Atif0604** [comment]
Please Review my PR @Ankita297 @Rizwan-S

**Comment by Ankita297** [comment]
@Atif0604  nice work . Keep going .

**Comment by Atif0604** [comment]
> @Atif0604 nice work . Keep going .

@Ankita297 @Rizwan-S 
This Commits is not listed in the contributors Commit

> @Atif0604 nice work . Keep going .

@Ankita297 @Rizwan-S I have made more than 3 commits as 2 PR are merged but it shows only 3 commits of the latest PR merged

image

**Comment by Rizwan-S** [comment]
Hello @Atif0604 ! Can you please elaborate about what is missing according to you? I have checked the commit history of recent past and it looks correct. I'm attaching the commits history by you.
Screenshot_20210629-215446

**Comment by Atif0604** [comment]
> Hello @Atif0604 ! Can you please elaborate about what is missing according to you? I have checked the commit history of recent past and it looks correct. I'm attaching the commits history by you.
> Screenshot_20210629-215446

yeah its fine 
 @Rizwan-S

**Pull request merged**
