### PR TITLE
preloader added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
preloader added
Closes: #352

### Describe the changes you've made
preloader added
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots

https://user-images.githubusercontent.com/67833077/111342441-79b92c00-86a0-11eb-8f09-c3baa29c4a56.mp4

### CODE REVIEW

**Comment by harshgupta20** [comment]
Hello @Ankita297 , Its good see it, but the design of the pre-loader is far away from the website basic theme, Kindly mold it accordingly so that it will not look separate from the website.☺☺

**Comment by Ankita297** [comment]
So sir should i use some simple gif preloader or change the color theme of this preloader to match with website theme

**Comment by Ankita297** [comment]
I mean should i mantain this design and change the color scheme   accordingly ?

**Comment by Ankita297** [comment]
I had also put an idea inside the issue section  . Please review .

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111424122-52ea0c80-8717-11eb-9f51-7b4c80de7a41.mp4

**Comment by Ankita297** [comment]
@harshgupta20  Please review it and tell me if it is okay , then i can make  commit .

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111738035-a8085880-88a6-11eb-80f9-e0b1a32ba1c2.mp4

**Comment by Ankita297** [comment]
@harshgupta20 Please review it if it is okay ?
Or any other changes require ?

**Comment by Ankita297** [comment]
Please review my PR @Vishal-raj-1  @ridsuteri  .

**Review by ridsuteri — APPROVED** [review]
Great work @Ankita297 ,thanks for contributing :)

**Comment by Ankita297** [comment]
Can you please add it now ?

**Pull request merged**
