### PR TITLE
Animation and Hover effect on Nav title 

### PR DESCRIPTION
**Pull request by aastha621**
## Related Issue
Adding text animation, and on-hover effects.
In relevance of Issue #553 

Closes: #553 

### Describe the changes you've made
The sub text on banner is given an animation, using typewriter effect by using typed.js.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@aastha621 You did so many unwanted changes and changed 8100+ lines....

Revert all the unnecessary changes.

**Comment by aastha621** [comment]
@urvashi-code1255  okay will do so and make a new PR soon.

**Comment by aastha621** [comment]
@urvashi-code1255 pls review it again and let me know if more changes are required

**Comment by aastha621** [comment]
@991rajat @urvashi-code1255 kindly review this PR

**Comment by 991rajat** [comment]
Great Work.
Resolve the conflict.

**Comment by aastha621** [comment]
> Great Work.
> Resolve the conflict.

@991rajat Hey, Thankyou! I resolved the conflicts. pls check!

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
