### PR TITLE
Added code for Colorful Fixed Header

### PR DESCRIPTION
**Pull request by Nkap23**
## Related Issue
Added Colorful Fixed Header
Closes: #245 

### Describe the changes you've made
Added 3 new files
- assets/css/colorful_fixed_header.css
- assets/js/colorful_fixed_header.js
- public/colorful_fixed_header.html

The files contain code for a fixed header which changes color based on the scroll.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
- Before Scroll
Screenshot (510)
- After Scroll
Screenshot (511)

### CODE REVIEW

**Comment by Nkap23** [comment]
@urvashi-code1255
@Vishal-raj-1 
Request you to review it.
Thanks!

**Review by Vishal-raj-1 — COMMENTED** [review]
@Nkap23 You are adding two projects here. But adding only one project in script.js

**Comment by Vishal-raj-1** [comment]
Also check the conflicting file

**Comment by Vishal-raj-1** [comment]
@Nkap23 ??

**Pull request merged**
