### PR TITLE
PINPAD VALIDATOR

### PR DESCRIPTION
**Pull request by syamala27**
## About **_PinPad validator_**
- I have created a pin-pad validator, if u enter wrong pin  it will show "**INCORRECT**", else it will show "**SUCCESS**" .
- The correct pin is in the files section (js file) :)

## Describe the changes you've made
there are three files, one for `HTML` where all the base elements are present, one for `CSS` to make the project eye-catching, and a `JS` file to make the elements functioning.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots
- **_Main page_** 

image

- **_If u enter an `incorrect` pin_** 

image

- **_If u enter `correct` pin_**

image

 
@ridsuteri  @urvashi-code1255  @991rajat , please guide me if any changes required.

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@syamala27 kindly add this project to the script.js file

**Comment by syamala27** [comment]
@ridsuteri  sir, I have updated the script.js file and added gif please verify it.

**Review by ridsuteri — APPROVED** [review]
good work  @syamala27 ,thanks for contributing :)

**Comment by mahesh-11102** [comment]
Thank you sir :)

**Pull request merged**
