### PR TITLE
Navbar Toggler issues fixed | Night mode icon changed 

### PR DESCRIPTION
**Pull request by nikhil-Vaibhav**
## Related Issue
  - Info about Issue or bug

Closes: #316 

### Describe the changes you've made
1. I have fixed the issue of of the toggler which was not working when the window was resized.

2. I have also changed the night mode icon with a font-awesome icon as it is looking more nice and clear and conveying information that it is to enable/disable night mode.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA - (This is my first PR so there were a lot line changes during testing. But at the end everything is working fine)
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (15)

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@nikhil-Vaibhav PLease pull the recent changes

**Comment by nikhil-Vaibhav** [comment]
@urvashi-code1255  @Sapna2001  Please help me with this how can I pull the changes into one branch.

**Review by urvashi-code1255 — COMMENTED** [review]
@nikhil-Vaibhav Project is having so many issues after your changes..

Please have a look

**Comment by nikhil-Vaibhav** [comment]
@urvashi-code1255 I need your help regarding all this. Please tell me can I text you on discord as I want to clear certain things.

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 I need your help regarding all this. Please tell me can I text you on discord as I want to clear certain things.

OKay Sure @nikhil-Vaibhav

**Pull request closed without merging**
