### PR TITLE
Grocery List Project

### PR DESCRIPTION
**Pull request by rray14**
## Related Issue
  - To create a Grocery list project

Closes: #435

### Describe the changes you've made
Added a new js project Grocery List where users can input the items and quantity and it generates a list. Added HTML,CSS and js files into respective folders

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (54)

### CODE REVIEW

**Comment by 991rajat** [comment]
1. Add the project to script.js
2. Don't push setting.json.
3. Reduce the size of the gif. If not able to do reduce the duration and resolution, try again. If not able tow work replace it with static image.
Make the gif under 500KB or so.

**Comment by rray14** [comment]
Sir @991rajat I have modified my PR as mentioned.

**Comment by 991rajat** [comment]
Good Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. Keep Contributing.

**Pull request merged**
