### PR TITLE
extra space removed

### PR DESCRIPTION
**Pull request by khushi935**
#42

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
> #42

hey @khushi935 please follow the PR template present in the project

**Comment by khushi935** [comment]
I closed this PR and made a new pull request and follow PR template 😊.

**Comment by Vishal-raj-1** [comment]
@khushi935 You don't need to create new PR for this purpose !! You can simply edit your message like this
edit

**Comment by khushi935** [comment]
Okay, I don't know that we can edit PR. Thank you for giving the information.

**Pull request closed without merging**
