### PR TITLE
Added the code for RGB Color Guessing Game[GSSoC'21]

### LINKED ISSUE #270: RGB COLOR GUESSING GAME!
I would like to make a color guessing game using javascript.

**Features**
1. Button to choose between easy or Hard level.
2. Change in the background color, if the right color is chosen.
3. You'll be able to choose new colors, if you are not happy with the current shuffle of colors, just like it happens in spider solitaire, basically new game.
4. A 'try again', 'play again' and Correct alerts, based on the responses of the user.

PLease assign this to me under GSSoC 2021

### PR DESCRIPTION
**Pull request by SHAGUN0312**
Hey, @urvashi-code1255 @Vishal-raj-1,
I have created this RGB Color Guessing Game under GSSoc'21, please do check this PR.
closes #270

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@SHAGUN0312 resolve the merge conflicts

**Comment by urvashi-code1255** [comment]
@SHAGUN0312 Please resolve the merge conflicts again

**Comment by SHAGUN0312** [comment]
Conflict Resolved @urvashi-code1255

**Comment by 991rajat** [comment]
@SHAGUN0312 Please Squash the commits and Pull latest changes and resolve the conflict

**Review by 991rajat — APPROVED** [review]
Great work!
Congratulation for the first contribution 🎉 
Keep Contributing

**Pull request merged**
