### PR TITLE
New Project addition : phyllotaxis

### LINKED ISSUE #907: Project addition : Phyllotaxis
# Phyllotaxis

Phyllotaxis is a pattern found in nature, the rotational angle from leaf to leaf in a repeating spiral can be represented by a fraction of a full rotation around the stem. The project is to represent the following pattern via mathematical visualization 
This project is an attempt to showcase its visualization.
[*Source-Wikipedia*](https://en.wikipedia.org/wiki/Golden_angle)

## Main goal

1. Make visualization of Phyllotaxis 
2. Add colors to the points
3. Make it responsive

## Tech stack
- **Frontend**: HTML, SCSS/CSS and JavaScript.

## Examples :
image

### PR DESCRIPTION
**Pull request by jhamadhav**
## Describe the changes you've made
I have Made a project called phyllotaxis, to generate phyllotaxis patterns using a mathematical formula.
Closes #907

## Describe if there is any unusual behavior of your code(Write NA if there isn't)
NA

## Checklist:

My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots
Put any screenshot(s) of the project here :
phyllotaxis

### CODE REVIEW

**Comment by jhamadhav** [comment]
> 
> 
> TO much extra files. removes unnecessary files

I removed the extra files.
Please guide me on how to resolve the `script.js` issue, it appeared after I tried adding my project there.
Kindly add GSSOC'21 and Level tags!
Thank you!

**Comment by jhamadhav** [comment]
@991rajat I have resolved the `script.js` issue and added my project into it please check.

**Comment by jhamadhav** [comment]
@991rajat @Vishal-raj-1 please check the PR for merge, I have made all the requested changes and resolved the conflict!

**Comment by 991rajat** [comment]
Hey @jhamadhav Good Work. Just one thing more you know about squashing ? could you perform it. 
Squash them into 1 commit. If not please let me know.

**Comment by jhamadhav** [comment]
@991rajat due to others project in `script.js` it shows a lot of conflicts while trying to squash using `git rebase -i HEAD~16`? what to do?

**Comment by jhamadhav** [comment]
and while squashing I can see a lot of other people commits too ?

**Comment by 991rajat** [comment]
I guess it got tangled up while pulling the changes.
It happens I'll squash them from the UI, I guess it's hard in command line.

**Comment by 991rajat** [comment]
No worries Great Work.

**Comment by jhamadhav** [comment]
Thanks a lot 😇

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing.

**Comment by jhamadhav** [comment]
@991rajat please add a level tag in this PR!

**Pull request merged**
