### PR TITLE
Note app styling

### PR DESCRIPTION
**Pull request by mirakiii**
## Related Issue
  - Styling of noteApp

Closes: #15 

### Describe the changes you've made
added more styling and features using css and modifying the js file. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@mirakiii Its looking pretty cool. Just update the GIf of the notes app card in script.js

**Comment by mirakiii** [comment]
> @mirakiii Its looking pretty cool. Just update the GIf of the notes app card in script.js

sure !

**Comment by mirakiii** [comment]
hey ! @urvashi-code1255 have changed the gif , kindly see to it :)

**Review by urvashi-code1255 — APPROVED** [review]
Its looking great now @mirakiii . Thanks for contributing.

**Pull request merged**
