### PR TITLE
Added Mario run project

### PR DESCRIPTION
**Pull request by Abhijay007**
Closes: #112

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

Added Mario-run project and changes files accordingly  

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### Screenshots
Put any screenshot(s) of the project here.

mario

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @Abhijay007 Could you please squash your commits into one?

**Comment by Abhijay007** [comment]
> Hey @Abhijay007 Could you please squash your commits into one?

@urvashi-code1255 can you please guide me to do that

**Comment by Abhijay007** [comment]
I pulled changes from upstream and made a separate branch but I don't know why it shows my previous commits

**Comment by Abhijay007** [comment]
is there any command to squash multiple commits one?

**Comment by urvashi-code1255** [comment]
> is there any command to squash multiple commits one?

Yes @Abhijay007 read out [this](https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc#:~:text=Squashing%20is%20mainly%20used%20to,(like%20master%20or%20develop).) article

**Comment by Abhijay007** [comment]
@urvashi-code1255 when I try to squash those commits I am getting this.
rebase

and according to the tutorial I watched and blogs you mentioned the result of the last five commits must be something like this:

javaScript Drum kit 5997606
resolving conflicts 4226dfe
Added netflix clone project f139be0
Merge branch 'main' of https://github.com/Vishal-raj-1/Awesome-JavaSc… …a3a33ca
Mario-run project added 2f9cce7

I not getting where I made the mistake, can you please guide me?

**Review by Vishal-raj-1 — APPROVED** [review]
Awesome Work @Abhijay007 !!

**Pull request merged**
