### PR TITLE
Bubble Particle Text project [gssoc21]

### PR DESCRIPTION
**Pull request by ishita-sehgal**
## Related Issue
  - I have added a 'Bubble Particle Text' project using canvas and vanilla JS. In this project the text is in bubble form and bubbles move on moving mouse over it and then text re-gains its form automatically

Closes: #481

### Describe the changes you've made
Added the 'Bubble Particle Text' Project.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
`NA`
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image
image

### CODE REVIEW

**Comment by ishita-sehgal** [comment]
@991rajat ,can you pls review this PR.

**Review by 991rajat — APPROVED** [review]
Good Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by ishita-sehgal** [comment]
@991rajat, can you pls add the gssoc21 and level tag on this PR.

**Pull request merged**
