### PR TITLE
Rearranged all projects in alphabetical order

### LINKED ISSUE #667: Rearrange the Project In Alphabetical Order
As you can see the projects are in random order. I would like to rearrange them in alphabetical order so that it will be easy for the user to navigate through them.

@ridsuteri @urvashi-code1255  Please assign me this issue under GSSOC21 label.

### PR DESCRIPTION
**Pull request by Bhavyal9**
Fixed #667

## Related Issue
  Rearranged the projects in alphabetical order so that the user can navigate easily.

Closes: #667 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Bhavyal9** [comment]
@ridsuteri @Vishal-raj-1 @urvashi-code1255 Please add a label under gssoc21

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Bhavyal9 your changes are breaking the project section...
kindly review locally and resolve the issue

**Comment by ridsuteri** [comment]
@Bhavyal9 any progress?

**Comment by Bhavyal9** [comment]
@ridsuteri I am still having an issue with conflict. I will try again today.

**Comment by ridsuteri** [comment]
@Bhavyal9 any progress? or should i open this issue for someone else?

**Pull request closed without merging**
