### PR TITLE
Added Color Picker Converter

### PR DESCRIPTION
**Pull request by AmeyaJain-25**
## Related Issue
  - Added a new feature of Color Picker and Converter application

Closes: #265 

### Describe the changes you've made
I have added the application for color picker and converter. It helps user to convert RGB to hex and hex to RGB code. Also it helps to select color by changing the range and a random picker feature is also added

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
ColorPickerConverter
Screenshot from 2021-03-14 17-25-03
Screenshot from 2021-03-14 17-25-24

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@AmeyaJain-25 PLease resolve the merge conflicts

**Comment by AmeyaJain-25** [comment]
@urvashi-code1255 
Resolved the conflicts. Please review and merge my PR

Thanks.

**Review by urvashi-code1255 — APPROVED** [review]
@AmeyaJain-25 I really loved your project.

Thanks for your contribution :)

**Comment by AmeyaJain-25** [comment]
> @AmeyaJain-25 I really loved your project.
> 
> Thanks for your contribution :)

Thank you so much.
Great experience to contribute and learn more new things

**Comment by AmeyaJain-25** [comment]
@urvashi-code1255 
Can you please change the label to GSSoC21 instead of gssoc'21.
Because in the leaderboard, it's not accepting the label and my points wouldn't be counted.

Please do the changes in the label.

**Pull request merged**
