### PR TITLE
JavaScript Interest Calculator - Enhancement

### PR DESCRIPTION
**Pull request by AnshikaAgrawal5501**
## Related Issue
  - I have enhanced the entire look of the Interest Calculator

Closes: #1023

### Describe the changes you've made
 - made the project completely responsive
 - changed the background styling
 - placed an image in the background
 - added bootstrap to the input fields and the buttons
 - changed the theme of the calculator
 - removed unnecessary headings
 - changed the styling of the heading
 - added icons to the input fields.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Before
InterestCalculator

After
Interest_Calculator_Backcover

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@AnshikaAgrawal5501 please update the GIF too

**Comment by AnshikaAgrawal5501** [comment]
Hey @urvashi-code1255,
I have replaced the back cover image of the project with a gif.

Please have a look at it and do let me know.
Interest_Calculator

**Comment by AnshikaAgrawal5501** [comment]
@Vishal-raj-1  @urvashi-code1255  @harshgupta20  @ridsuteri 
Please review the PR and do let me know if more changes are required.
Thanks.

**Review by ridsuteri — APPROVED** [review]
good work @AnshikaAgrawal5501 , thanks for contributing :)

**Comment by AnshikaAgrawal5501** [comment]
> good work @AnshikaAgrawal5501 , thanks for contributing :)

Thanks, @ridsuteri  for merging the PR.

**Pull request merged**
