### PR TITLE
Added Expense Tracker and Weight converter

### PR DESCRIPTION
**Pull request by vinayak0127**
## Related Issue
  - expense tracker using pure vanilla js

Closes: #290 #341 

### Describe the changes you've made
- added expense and weight converter tracker in pure vanilla js under gssoc'21 participant

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
N\A

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image
image

### CODE REVIEW

**Comment by vinayak0127** [comment]
@Vishal-raj-1  @urvashi-code1255  review this pr

**Comment by 991rajat** [comment]
@vinayak0127 Reduce the size of gif and resolve the conflict please.

**Review by 991rajat — APPROVED** [review]
Great Work

**Comment by 991rajat** [comment]
Thanks for the contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
