### PR TITLE
Successfully added styles to the BMI Calculator page

### PR DESCRIPTION
**Pull request by SilverGraph**
## Related Issue
  `NA`

Closes: #563 

### Describe the changes you've made

- Changed the BMICalculator.html
- Changed the BMICalcilator.css
- Changed the BMICalculator.js
- Added bmi-img.jpg to /assets/Images/
- Added diagnosis.png /assets/Images/

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

Before:
before

After:
after

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@SilverGraph Design is looking good but website is not respnsive.

**Comment by SilverGraph** [comment]
I had only decided to style the page as mentioned in the issue but I'll try to make it responsive like you said.

**Comment by SilverGraph** [comment]
@urvashi-code1255 I have successfully added a responsive design.

Mid-size:
mid-size

Phone size:
small-size

**Comment by 991rajat** [comment]
@SilverGraph Awesome work.
Please update the old gif with new updated UI of gif.
And Squash the commit.

**Comment by SilverGraph** [comment]
> @SilverGraph Awesome work.
> Please update the old gif with new updated UI of gif.
> And Squash the commit.

I am sorry but I didn't understand what you meant by `gif` because I haven't applied any gif.

**Comment by 991rajat** [comment]
Just Replace the old gif with new one as You have updated UI create a new gif with that and replace the old one.

**Comment by SilverGraph** [comment]
@991rajat I have squashed all the commits and changed the gif.

Desktop-size:
desktop-size

iPad-size:
iPad-size

Mobile-size:
iPhone-size

**Comment by 991rajat** [comment]
@SilverGraph Good Work
Replace this gif with new yours new one. Remember size of gif should be small.
image

**Comment by SilverGraph** [comment]
@991rajat Like this?

Screenshot 2021-03-19 184124

**Comment by 991rajat** [comment]
No That
At the main website in Projects Gif is old you have to replace that one.
Simply create a new gif with your project.
And replace  in assets/gif/{BMI gif}
image

**Comment by SilverGraph** [comment]
@991rajat I have succesfully replaced the old gif.

BMIcal

**Review by 991rajat — APPROVED** [review]
Fabulous Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
keep contributing.

**Pull request merged**
