### PR TITLE
Create a Music App with JavaScript #887  Open

### PR DESCRIPTION
**Pull request by WebVishal**
hi, @991rajat & @harshgupta20 hope you well,  I completed task #887 please reviews the code. I have added some screenshots hope you can help in the code review

Sorry For Dealy 

Screenshot (111)
Screenshot (114)

### CODE REVIEW

**Comment by 991rajat** [comment]
There is another music player add exist. Remove that project from script.js
Fix the the image and Reduce the size of the gif, if not able to reduce, swap it with a static image.
There are lot of pojects added again, remove that only add your project and remove the existing project.
image

**Comment by WebVishal** [comment]
hi, @991rajat I have updated the Project name and gifs Please check it 
now it looks like this ;

Screenshot (126)

**Comment by 991rajat** [comment]
@WebVishal Reduce the size of gif, Use Image size is too much.
Also Lot of projects are added again, Don't add them. Fix this

**Comment by 991rajat** [comment]
Let me know if need any help

**Comment by WebVishal** [comment]
@991rajat  I only have to reduce the size of the gifs or images also.

**Comment by WebVishal** [comment]
hey @991rajat I have updated the gifs from 32MB to almost 8m hope now it's fine to Review it

**Comment by 991rajat** [comment]
Lot of projects are added again. Please fix it.

**Comment by WebVishal** [comment]
@991rajat  What do i need to fix ??

**Comment by 991rajat** [comment]
These projects are already added.
image

**Comment by WebVishal** [comment]
@991rajat  I can't understand what do want ?? please explain

**Comment by 991rajat** [comment]
Projects on green are already present, you are adding again, when you will search you will find there are duplicates,
There should be no changes in script.js Don't you think as nothing has to be added other than you project only.

**Comment by WebVishal** [comment]
@991rajat Sorry  its added by mistake  i have update please check it

**Comment by 991rajat** [comment]
@WebVishal Let me know if u face any issue?

**Comment by WebVishal** [comment]
@991rajat  Check above from pic I have push with "Update script.js" commit

**Comment by 991rajat** [comment]
Only Your project lines should be added in script.js

**Comment by WebVishal** [comment]
@991rajat  check it hope now it's fine 😢

**Pull request merged**
