### PR TITLE
currency converter added

### PR DESCRIPTION
**Pull request by Sapna2001**
## Related Issue
Closes: #208

### Describe the changes you've made
Made a currency convertor

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot from 2021-03-09 10-34-44

@Vishal-raj-1 @urvashi-code1255  please review this and let me know if any change is there. I am a GSSOC'2021 participant so please add the relevant labels.

### CODE REVIEW

**Comment by Sapna2001** [comment]
@urvashi-code1255 can you check if the projects are visible now.

**Comment by Sapna2001** [comment]
@urvashi-code1255 I have resolved the merge conflicts. Is there anything else to be done?

**Comment by urvashi-code1255** [comment]
@Sapna2001 Please resolve the conflicts again

**Comment by Sapna2001** [comment]
@urvashi-code1255 Conflicts Resolved.

**Comment by urvashi-code1255** [comment]
@Sapna2001 ...

**Pull request closed without merging**
