### PR TITLE
Apple Game Added

### PR DESCRIPTION
**Pull request by neha07kumari**
## Related Issue
  - Apple Collector Game in Javascript.

Closes: #1358 

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
screenshot

### CODE REVIEW

**Comment by neha07kumari** [comment]
@ridsuteri Please review my PR and let me know if there are any conflicts.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@neha07kumari the project looks good, just resolve the merge conflicts :)

**Comment by neha07kumari** [comment]
> @neha07kumari the project looks good, just resolve the merge conflicts :)

@ridsuteri The conflict has been resolved.

**Review by ridsuteri — APPROVED** [review]
good work @neha07kumari :)

**Pull request merged**
