### PR TITLE
Harry potter

### PR DESCRIPTION
**Pull request by pritamkr1**
## Related Issue
  - Info about Issue or bug

Closes: #653 

### Describe the changes you've made 

Basically! used harry potter character API and fetched with js and also added the AOS CSS library.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
![x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
herry

### CODE REVIEW

**Comment by 991rajat** [comment]
@pritamkr1 Add the project to script.js

**Comment by pritamkr1** [comment]
added details to script.js files  and merge it  @Vishal-raj-1

**Comment by pritamkr1** [comment]
added details to script.js file @Vishal-raj-1

**Comment by pritamkr1** [comment]
please @Vishal-raj-1  merge it..

**Comment by 991rajat** [comment]
@pritamkr1 Is search works?

**Comment by pritamkr1** [comment]
No! @Vishal-raj-1  actually it working but can't working properly with characters

**Comment by 991rajat** [comment]
Okay No Problem. Good Work

**Comment by 991rajat** [comment]
Thank you for this awesome contribution. 🤩 
Keep Contributing.

**Pull request merged**
