### PR TITLE
Github_user_ finder

### PR DESCRIPTION
**Pull request by bitaashna**
## Related Issue
 #583 

Closes: #583 

### Describe the changes you've made
An app to find  github user and we can keep track of name,company,bio,pubic repos,etc
There will be a button directing to the github profile of user
This app fetches some of the recent repos and on clicking on those repos ,the user will be directed to that repo on github

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
github_finder

### CODE REVIEW

**Comment by bitaashna** [comment]
@urvashi-code1255 Please review it!

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@bitaashna there is some issue with your script.js file, which is breaking the whole project section,
kindly check it locally and fix it .

**Comment by bitaashna** [comment]
Please check it now!

**Review by ridsuteri — APPROVED** [review]
good work @bitaashna ,thanks for contributing :)

**Pull request merged**
