### PR TITLE
added music player game

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue-> #56 

@urvashi-code1255

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Follow [this](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/PR_template.md) PR template!!

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Follow [this](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/PR_template.md) PR template!!

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Follow [this](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/PR_template.md) PR template!!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 your pr template is not in place it did not show me anything when I made a pr,
I guess you have to name it as "pull_request_template.md"

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda your PR contains so many unwanted changes!! Please change only files/lines related to your issue. 

Besides everything!!! You can do one thing to solve very issue!! 

Just delete your forked repo and fork this again and don't do unwanted changes!!(unwanted changes includes formatting the file)

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 your pr template is not in place it did not show me anything when I made a pr,
> I guess you have to name it as "pull_request_template.md"

Yeah I am looking into it!!

**Comment by Sloth-Panda** [comment]
> Hey @Sloth-Panda your PR contains so many unwanted changes!! Please change only files/lines related to your issue.
> 
> Besides everything!!! You can do one thing to solve every issue!!
> 
> Just delete your forked repo and fork this again and don't do unwanted changes!!(unwanted changes includes formatting the file)

I guess its fine now cause after pulling from upstream and solving all the merge conflicts I made the pr can you just confirm

**Comment by urvashi-code1255** [comment]
> > Hey @Sloth-Panda your PR contains so many unwanted changes!! Please change only files/lines related to your issue.
> > Besides everything!!! You can do one thing to solve every issue!!
> > Just delete your forked repo and fork this again and don't do unwanted changes!!(unwanted changes includes formatting the file)
> 
> I guess its fine now cause after pulling from upstream and solving all the merge conflicts I made the pr can you just confirm

I have tested your PR locally thats why I am saying. After your PR space between about and Project section is increased!!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 what are you saying I am asking if everything is okay with the pr or not? You may be having conflicts if you have not updated ur code with the upstream

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 what are you saying I am asking if everything is okay with the pr or not? You may be having conflicts if you have not updated ur code with the upstream

hey @Sloth-Panda just send me the picture of the space between about and project seection

**Comment by Sloth-Panda** [comment]
Screenshot (116)
Screenshot (117)
Screenshot (118)
Screenshot (119)

see its completely fine and you can see music player too

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda What I am saying and what you are sending!!

I am saying about this space!!
Capture

**Comment by Sloth-Panda** [comment]
Screenshot (120)
see

**Comment by urvashi-code1255** [comment]
Yes, See this space is large!! @Sloth-Panda . You can check the real spacing [here](https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/)

**Comment by Sloth-Panda** [comment]
okay  should I close this pr then? will have to refork and again make a pr

**Pull request closed without merging**
