### PR TITLE
Keyboard typing 

### LINKED ISSUE #17: Calculator: Allow typing on the keyboard
Either make the textfield editable, or mark it as readonly and setup keyboard listeners to react to the keypresses. 

Important to keep the code short and easy to understand.

### PR DESCRIPTION
**Pull request by bitaashna**
fixes #17 
**Describe the changes you've made**

- -keyboard listener has been set up to react to keypresses- Now calculation can be done directly by pressing keys on keyboard .Implemented by using event listeners like keyup , keydown.
- -shows error message as well, whenever wrong syntax is used.

**Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)**
NA

 **Checklist:**

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

#GSSOC'21

**Screenshots**
https://user-images.githubusercontent.com/57864526/110376287-05b3ce00-8079-11eb-832e-7652397b6646.mp4
#17

### CODE REVIEW

**Comment by synox** [comment]
Would it be possible to do it with less code, maybe with less functionality? For a beginner this is a lot of code to digest, compared to the previous version.

**Review by urvashi-code1255 — APPROVED** [review]
Awesome work @bitaashna :)

**Comment by bitaashna** [comment]
@urvashi-code1255  thanks ! Can u please give it a label of GSSOC'21

**Comment by bitaashna** [comment]
@urvashi-code1255 
For this PR label were not mentioned.
Can u please mention the labels.
I think for this PR my points are not added.
Thank you:)

**Comment by harshgupta20** [comment]
@bitaashna I have applied PR.

**Pull request merged**
