### PR TITLE
Issue#431

### PR DESCRIPTION
**Pull request by SharmaTanish**
## Added Rode Slider Game
  -I have made a Rode Slider Game using native JavaScript with HTML and CSS . In this game there are two rods that move collectively ( so that game can be played by single player ) and the ball moves randomly in the are between rods and they both need to prevent ball to tough their respective screen borders . Also I have used the concept of " local storage " using JavaScript to keep the track of score of player and hence to find the maximum score .

Closes: #431 

### Changes I made
I have added one HTML , CSS , JavaScript file and GIF , background video related to game . Also made respective changes to " script.js " file . All these are named " rodeslider " or " rodeslidergame " along with their respective extensions .
@Vishal-raj-1 , @urvashi-code1255 please have a look on this .

###NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by ridsuteri** [comment]
> @ridsuteri I have resolved the merge conflict , but I do not know why again it is showing conflict here on github .
> Please help me out of this !
> You can also check the below screenshot -
> Screenshot (1158)
> 
> Thank you

@SharmaTanish this is happening when you are making changes on your copy of main's script file,and before you submit a PR the main's script file is getting  updated by any other PR and these changes in script file is conflicting with your's changes...

**Comment by SharmaTanish** [comment]
So @ridsuteri  how can I resolve this problem as you can see in above screenshot that when I run (git merge issue#431) as issue#431 is my another branch , then it is showing already up to date instead of throwing the merge conflict error . Also the "mark as resolved" button is disabled on github after clicking to resolve conflicts , so I can't resolve it on github and also not in terminal .
Please guide me what to do in this situation ?
Thank you

**Comment by ridsuteri** [comment]
@SharmaTanish you can pull recent changes from the main branch

**Comment by SharmaTanish** [comment]
@ridsuteri I have resolved the conflict , now please you check the changes at your level and then merge this pull request .
Also please add relevant labels to this pull request.
Thank you !

**Review by ridsuteri — APPROVED** [review]
great work @SharmaTanish ,thanks for contributing :)

**Comment by SharmaTanish** [comment]
Thank you @ridsuteri for your support 😀!

**Pull request merged**
