### PR TITLE
Added pixels game

### PR DESCRIPTION
**Pull request by amrzaki2000**
## Related Issue
  - Info about Issue or bug

Closes: #289
### Describe the changes you've made
- Created a javascript mouse-click 2D game.
- Added the game to the website.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by amrzaki2000** [comment]
@urvashi-code1255  Kindly review my PR request 
Thank you

**Comment by amrzaki2000** [comment]
@urvashi-code1255 @Vishal-raj-1 
Please, review my PR.

**Comment by amrzaki2000** [comment]
@ridsuteri Can you review my PR, please ?
Thank you

**Review by ridsuteri — APPROVED** [review]
great work @amrzaki2000

**Comment by amrzaki2000** [comment]
> 
> 
> great work @amrzaki2000

@ridsuteri 
Thank you 😄 
Can you add the GSSoC tags, please ?

**Comment by amrzaki2000** [comment]
@ridsuteri 
Can you add the level tag so the score can be calculated, please?

**Comment by ridsuteri** [comment]
@amrzaki2000 don't worry about the score since issue is linked with this PR the team will handle the scores on basis of that

**Pull request merged**
