### PR TITLE
DiceGame

### PR DESCRIPTION
**Pull request by bilal-23**
## Related Issue
  Added the files for DiceGame

Closes: #162 

### Describe the changes you've made
I have added the html file,css file and script file for the dice game. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@bilal-23 Add your project details in script.js

**Comment by bilal-23** [comment]
Added details in script.js

**Review by urvashi-code1255 — COMMENTED** [review]
@bilal-23 I told you to add your project details in main script.js like the other projects,

Please have a look at script.js

**Comment by bilal-23** [comment]
@urvashi-code1255 Hey, I have raised a new PR #557  for this issue #162.
Please check.

**Pull request closed without merging**
