### PR TITLE
px-rem converter added 

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
px-rem converter added 
Closes: #1344 
### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Document - Google Chrome 11-05-2021 16_54_49

https://user-images.githubusercontent.com/67833077/117809465-d63d5f80-b27b-11eb-9910-e90f1b0b907b.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by 991rajat** [comment]
Looks Good.

**Review by 991rajat — APPROVED** [review]
Looks Good.

**Pull request merged**
