### PR TITLE
digital clock button bug

### PR DESCRIPTION
**Pull request by Astrodevil**
## Related Issue
  - digital clock button bug
Closes: #482

### Describe the changes you've made
I changed the color of start button & stop button before and after clicking.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
**before**
start

**After**
now

### CODE REVIEW

**Comment by 991rajat** [comment]
@Astrodevil Squash the commits please.
What squashing does is it combines multiple commit into one.
It's a good practice Please try to do.
Let me know if you need any help

**Comment by Astrodevil** [comment]
> 
> 
> @Astrodevil Squash the commits please.
> What squashing does is it combines multiple commit into one.
> It's a good practice Please try to do.
> Let me know if you need any help

**Comment by Astrodevil** [comment]
please guide me, how to squash the commits. 
do i have to create branch? @991rajat

**Comment by 991rajat** [comment]
@Astrodevil DM on Discord.

**Comment by 991rajat** [comment]
Okay I'm closing this.

**Pull request closed without merging**
