### PR TITLE
Validated HTML solving issue #708

### PR DESCRIPTION
**Pull request by Muskan-creator**
## Related Issue
  - Info about Issue or bug
  - Html have parsing errors

Closes: #708

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
  - I have validated  index.html
  - validated projects.html
  - validated contact .html

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

Example how to mark a checkbox:-

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by Muskan-creator** [comment]
Please review @urvashi-code1255  @Vishal-raj-1 @991rajat

**Comment by Vishal-raj-1** [comment]
@Muskan-creator Resolve Conflicts Please

**Comment by Muskan-creator** [comment]
@Vishal-raj-1 @harshgupta20 Please merge my PR

**Comment by urvashi-code1255** [comment]
@Muskan-creator Resolve merge conflicts and I will merge it on priority :)

**Comment by Muskan-creator** [comment]
@urvashi-code1255 Now please merge my PR

**Comment by urvashi-code1255** [comment]
@Muskan-creator Please resolve them once again

**Comment by Muskan-creator** [comment]
I have resolved conflicts @urvashi-code1255 
Please merge my PR

**Pull request merged**
