### PR TITLE
Added url shortener

### PR DESCRIPTION
**Pull request by Sloth-Panda**
## Related Issue
  - Info about Issue or bug
Issue: #62 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Added an url shortener that shortens given url using tiny url
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (135)

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
https://sloth-panda.github.io/Awesome-JavaScript-Projects/ 

This is the link for checking out url shortener @urvashi-code1255  @Vishal-raj-1 .

**Comment by Sloth-Panda** [comment]
@Vishal-raj-1 Many times due to merge conflicts after I am solving the conflicts and trying to push  the  same code to the same branch where I made pr for that issue its giving me error and even after pulling the code from upstream I am not able to push the code and eventaully I am pushing the code by opening up a new branch thereby a new issue . What to do in that case??

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 You have to wait for some time to see the update if its giving u a 405 not allowed error as I just updated it

**Comment by Vishal-raj-1** [comment]
First of all, resolve this merge conflicts and squash your commit into one commit. How much time we have to wait ?

**Comment by Sloth-Panda** [comment]
@Vishal-raj-1  aree bhai yar tum jitna time kuch kar rha he merge har time meera merge conflict ajate hein😢

**Comment by Sloth-Panda** [comment]
Screenshot (142)

Aisa kyun ata he har time conflicts solve karne ke bad push karne par push nahi hota but branch change karne ke bad karne par hota he?

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda Don't worry my brother !! Have a look at this [video](https://youtu.be/f1wnYdLEpgI) This is the best video which help you to understand the git concepts.

The Reason is very simple You doing change at same place. So what you have to do is, first you have to `git pull upstream master` then you have do changes then do `git push`.

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda Great !!

**Pull request merged**
