### PR TITLE
Adding Age calculator

### PR DESCRIPTION
**Pull request by jaypatel31**
## Age Calculator Addition
  - New Project age calculator is added in the project section

Closes: #605

### Describe the changes you've made

- script.js (Addition of my project on index page)
- assets/Images/AgeCalculator.png (Image of Project)
- assets/css/AgeCalculator.css (Css file for Project)
- assets/js/AgeCalculator.js (Js file addition)
- public/AgeCalculator.html (Html file additon)

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
AgeCalculator

### Note
I am GSSOC'21 participant so kindly add gssoc tag in this pr.

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
@jaypatel31 Everything looks perfect to me. Just do a simple changes in .css and .js file, format the files. Currently It have unnecessary spaces

**Comment by jaypatel31** [comment]
Okay @Vishal-raj-1  I will do the formatting of the mentioned file.

**Comment by jaypatel31** [comment]
@Vishal-raj-1 , @991rajat  Please review and merge this pr as I have to solve conflict everyday.

**Review by 991rajat — APPROVED** [review]
Good Work

**Comment by 991rajat** [comment]
Next Time please squash the commits before pushing. It's a good practice.

**Pull request merged**
