### PR TITLE
bubble particle text project added

### PR DESCRIPTION
**Pull request by ishita-sehgal**
## Related Issue
  - I have added a 'Bubble Particle Text' project using canvas and vanilla JS. In this project the text is in bubble form and bubbles move on moving mouse over it and then text re-gains its form automatically

Closes: #481 

### Describe the changes you've made
Added the 'Bubble Particle Text' Project.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (657)
Screenshot (658)

### CODE REVIEW

**Comment by ishita-sehgal** [comment]
@991rajat ,can you pls review this PR.

**Comment by 991rajat** [comment]
Great work. Looks very cool.
Resolve the conflict and please squash the commits.

**Comment by ishita-sehgal** [comment]
on pulling the changes from upstream into my local main branch , some untouched files are showing modified and hence I cannot switch to my feature branch for resolving conflict and squashing . Can you pls look into it  @991rajat .

Screenshot (2)

**Comment by 991rajat** [comment]
@ishita-sehgal commit them and push
If can't squash leave it. also reduce the file size of gif please also

**Comment by ishita-sehgal** [comment]
@991rajat , I have done the required changes .Pls review and merge this PR.

**Comment by 991rajat** [comment]
Hey @ishita-sehgal your project works fine, but the breakout project which is pushed along is different from existing project.
Sorry for inconvienece could you either push only your project
or create a new PR with only your project.
Creating a new PR is easy.

**Comment by ishita-sehgal** [comment]
ok I will try and then make a new PR

**Comment by 991rajat** [comment]
Your project works fine. Have you created PR?

**Comment by ishita-sehgal** [comment]
yes at  #963 PR. pls review it.

**Pull request closed without merging**
