### PR TITLE
IssueTracker issue#251

### PR DESCRIPTION
**Pull request by dcs-soni**
## Related Issue
  - Github Issue Tracker which will help to manage the issues 

Closes: #[251]

### Describe the changes you've made
-> Built a **Github Issue Tracker** that will be useful for the maintainers of the project. Any important or valid issues that they need to look upon later can be added manually on this app. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@dcs-soni Resolve the merge conflicts

**Comment by dcs-soni** [comment]
Hey @urvashi-code1255 Can you please check, I've resolved the conflicts.

**Comment by dcs-soni** [comment]
Hi @ridsuteri Can you please check this one.

**Review by ridsuteri — APPROVED** [review]

**Comment by ridsuteri** [comment]
good work @dcs-soni ,thanks for contributing :)

**Pull request merged**
