### PR TITLE
Updated_Digital_Fancy_Clock

### PR DESCRIPTION
**Pull request by iamabhii1**
## Related Issue
  **_Updated the Digital_Fancy_Clock_** 

Closes: #820 

### Describe the changes you've made
I have updated the CSS (design look) of Digital_Fancy_Clock 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
As such there are no unusual behaviour .

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
**_BEFORE_**

Screenshot (2)

_**AFTER**_

Screenshot (4)

### CODE REVIEW

**Comment by 991rajat** [comment]
Please replace the image with the new one
It's in the script.js
image

**Comment by iamabhii1** [comment]
Ok I 'll do it .

**Comment by iamabhii1** [comment]
done , please check

**Review by 991rajat — APPROVED** [review]
Looks Great.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing.

**Comment by 991rajat** [comment]
Next time always create a new branch and do work on that don't add features to  main branch.
And learn squashing the commits. It's a good practice.

**Pull request merged**
