### PR TITLE
Added Sidenav

### PR DESCRIPTION
**Pull request by fsafarkhani**
I have made a Sidenav 
I hope it is useful

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hi @fsafarkhani please show a demo of your navabar here

**Comment by fsafarkhani** [comment]
@urvashi-code1255  Here is the Demo:
demo

**Comment by urvashi-code1255** [comment]
@fsafarkhani please add a card for this project like other projects on the main index.html

**Comment by fsafarkhani** [comment]
@urvashi-code1255 Added to card Done

**Comment by urvashi-code1255** [comment]
Hey @fsafarkhani Check your changes locally!! It contains bugs. Please remove them and make it same as the hosted link!!

**Comment by fsafarkhani** [comment]
I have got a lot of conflicts, I'm closing this pull request, and make another one again

**Pull request closed without merging**
