### PR TITLE
Project addition : Caesar cipher

### PR DESCRIPTION
**Pull request by jhamadhav**
# CAESAR CIPHER

In cryptography, a Caesar cipher, also known as Caesar's cipher, the shift cipher, Caesar's code or Caesar shift, is one of the simplest and most widely known encryption techniques. It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet. For example, with a left shift of 3, D would be replaced by A, E would become B, and so on. The method is named after Julius Caesar, who used it in his private correspondence.
[*Source-wikipedia*](https://en.wikipedia.org/wiki/Caesar_cipher)

Closes: #1475 

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)

NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Output

caesarCipher

### CODE REVIEW

**Comment by jhamadhav** [comment]
@Vishal-raj-1 @991rajat please review the PR and add level tags!

**Comment by 991rajat** [comment]
Looks Good Just. Resolve the conflict.

**Comment by jhamadhav** [comment]
@991rajat done

**Review by 991rajat — APPROVED** [review]
Looks Good. Great Work

**Pull request merged**
