### PR TITLE
Image Editor

### PR DESCRIPTION
**Pull request by sejalshri**
## Related Issue
  - Added a Js project that has an image editing and downloading feature.

Closes: #705 

### Describe the changes you've made
i have added the necessary html,css and js file for the project.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
iess

### CODE REVIEW

**Comment by sejalshri** [comment]
@ridsuteri @urvashi-code1255 @harshgupta20 @Vishal-raj-1 kindly review the PR.

**Review by urvashi-code1255 — COMMENTED** [review]
@sejalshri Change the card image with GIF

**Comment by sejalshri** [comment]
> 
> 
> @sejalshri Change the card image with GIF

done ma'am ! @urvashi-code1255

**Comment by sejalshri** [comment]
@urvashi-code1255 ,I have made the new PR for the same #817 .please review it.

**Pull request closed without merging**
