### PR TITLE
Mole-Game-Updated

### PR DESCRIPTION
**Pull request by Meghag5**
## Related Issue
  - Info about Issue or bug

Closes: #69 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have updated the start button and overflow of screen is now hidden.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/65459236/108181115-87c16e80-712d-11eb-9912-761e2c6d621a.mp4

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Hello @Meghag5 Can you please squash your commit into one commit ?

**Comment by Meghag5** [comment]
> Hello @Meghag5 Can you please squash your commit into one commit ?

can you help pls

**Comment by urvashi-code1255** [comment]
> can you help pls

@Meghag5 you can read [this](https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc#:~:text=Squashing%20is%20mainly%20used%20to,(like%20master%20or%20develop).)

**Comment by Vishal-raj-1** [comment]
@Meghag5 Do a one thing see this [video](https://youtu.be/f1wnYdLEpgI) . Squash your commits in your local repo, I am merging it for now !! But you must watch it, It is very interesting topic.

**Comment by Meghag5** [comment]
> @Meghag5 Do a one thing see this [video](https://youtu.be/f1wnYdLEpgI) . Squash your commits in your local repo, I am merging it for now !! But you must watch it, It is very interesting topic.

Thanks @Vishal-raj-1 I will watch it

**Pull request merged**
