### PR TITLE
Blurry Loading Interface

### PR DESCRIPTION
**Pull request by gaurav24072002**
Hey !!
I am a participant in Girl Script Summer of Code and want to contribute in this project.
can you assign this project to me !

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
sure

**Comment by urvashi-code1255** [comment]
Hey @gaurav24072002 Open an issue for your project first!!

**Comment by urvashi-code1255** [comment]
> Hey @gaurav24072002 Open an issue for your project first!!

Also do follow the PR template and add UI picture/video

**Comment by gaurav24072002** [comment]
@urvashi-code1255 there is no issue for this project but I just wanted to contribute in this repository so please merge my pull request... ok

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 there is no issue for this project but I just wanted to contribute in this repository so please merge my pull request... ok

Hey @gaurav24072002 then also you have to follow rules of the repository... right!!

**Comment by gaurav24072002** [comment]
ok... 
sure thanks...

**Comment by gaurav24072002** [comment]
done ...
Is that ok ? ..

**Review by Vishal-raj-1 — COMMENTED** [review]
@gaurav24072002 Follow structure of the projects. Make seperate css, js file. Second enable github pages on your local forked repo so that I can see your changes and review it clearly.

**Comment by urvashi-code1255** [comment]
Hey @gaurav24072002 Any updates on this PR?

**Comment by gaurav24072002** [comment]
@Vishal-raj-1  can you please describe briefly about what I have to do Please...

**Comment by Vishal-raj-1** [comment]
@gaurav24072002 I mean You have make a single file. Break this file into 3 files namely `blurry_loading_interface.html` , `blurry_loading_interface.css`, `blurry_loading_interface.js` . 

Second Now Do one more thing, enable github pages, so I can review your changes before merging to this codebase.

**Comment by gaurav24072002** [comment]
sure I will do it

**Pull request closed without merging**
