### PR TITLE
Animated counter

### PR DESCRIPTION
**Pull request by TidbitsJS**
Animated Counter in JavaScript to show statistics on website

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @TidbitsJS Please create an issue explaining about this pull request. Also, Add demo video here

**Comment by TidbitsJS** [comment]
Hello @urvashi-code1255 . Logged the issue. & here is the demo 

Demo

**Review by urvashi-code1255 — APPROVED** [review]
@TidbitsJS I like this project. Thanks for adding it!!

**Comment by TidbitsJS** [comment]
Thank you so much @urvashi-code1255

**Pull request merged**
