### PR TITLE
Add date-time widget project - #348

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - To add new date-time widget project.

Closes: #348 

### Describe the changes you've made
I have added new project of date-time widget which contain two new files **dateTimeWidget.html** and **dateTimeWidget.js** are added in `public/` and `assets/js/` respectively.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

clock-com

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@Vedant-Rahane Please add your project details in script.js like the other projects

**Comment by Vedant-Rahane** [comment]
@urvashi-code1255  I just added my project to script.js and pull from upstream but it is showing conflicts can you please help me what changes should be made.

**Comment by 991rajat** [comment]
Hey @Vedant-Rahane Please resolve the conflict.
Let me know if need any help.

**Comment by Vedant-Rahane** [comment]
@urvashi-code1255 @991rajat Can you please review and merge.

**Comment by Vedant-Rahane** [comment]
@991rajat Can please help me how to resolve this conflict, this is my first time in open source, I don't know how to resolve.

**Comment by Vedant-Rahane** [comment]
@991rajat Can you please review and merge this.

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM

**Comment by Vishal-raj-1** [comment]
Thanks for your contribution

**Pull request merged**
