### PR TITLE
 add DragNDrop

### PR DESCRIPTION
**Pull request by sonalisonawane**
## Related Issue
  - Info about Issue or bug

Closes: #153

### Describe the changes you've made
Added one JavaScript Project having the drag and drop functionality

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
DragNDrop

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@sonalisonawane Resolve the merge conflicts.

**Comment by sonalisonawane** [comment]
solved merge conflicts.

**Comment by urvashi-code1255** [comment]
Hey @sonalisonawane write [x] in place of [ x] and write closes #153 in place of Closes: #[153]

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @sonalisonawane You did so many unwanted changes in index.html but you only want to add your project card. Revert all the unwanted changes.

**Comment by sonalisonawane** [comment]
> Hey @sonalisonawane write [x] in place of [ x] and write closes #153 in place of Closes: #[153]

done!

**Review by Vishal-raj-1 — COMMENTED** [review]
@sonalisonawane Actually now onward we are using `Awesome-JavaScript-Projects/script.js` for projects detail. You can remove all the changes in `index.html` and add your project in mentioned file. Thanks

**Comment by sonalisonawane** [comment]
> @sonalisonawane Actually now onward we are using `Awesome-JavaScript-Projects/script.js` for projects detail. You can remove all the changes in `index.html` and add your project in mentioned file. Thanks

Done..!

**Comment by sonalisonawane** [comment]
> Hey @sonalisonawane You did so many unwanted changes in index.html but you only want to add your project card. Revert all the unwanted changes.

Do I have to remove all cards from Index.html?

**Review by urvashi-code1255 — COMMENTED** [review]
@sonalisonawane use 
`git checkout origin/main index.html` to make index.html same as it is in the main repository

As you don't have to do any change in the index.html now.

**Comment by sonalisonawane** [comment]
> @sonalisonawane use
> `git checkout origin/main index.html` to make index.html same as it is in the main repository
> 
> As you don't have to do any change in the index.html now.

Done!

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @sonalisonawane After some of your changes website is distorted. Please fix them!!

See the website on your local and see the main website. Compare them and do the necessary changes.

**Comment by sonalisonawane** [comment]
> Hey @sonalisonawane After some of your changes website is distorted. Please fix them!!
> 
> See the website on your local and see the main website. Compare them and do the necessary changes.

ok I will

**Comment by sonalisonawane** [comment]
done!

**Review by Vishal-raj-1 — APPROVED** [review]
@sonalisonawane Everything looks perfect to me. Do one last thing here. squash your commits into one single commit.

**Comment by sonalisonawane** [comment]
> @sonalisonawane Everything looks perfect to me. Do one last thing here. squash your commits into one single commit.

I am sorry @Vishal-raj-1 but I don't know how to do it :(

**Comment by urvashi-code1255** [comment]
> I am sorry @Vishal-raj-1 but I don't know how to do it :(

Read [this](https://www.internalpointers.com/post/squash-commits-into-one-git) for the same.

**Comment by Vishal-raj-1** [comment]
> I am sorry @Vishal-raj-1 but I don't know how to do it :(

First of all don't be sorry, I know you don't know about squashing that's why I was asking for it. Now You can learn this beautiful concept through this [video](https://youtu.be/f1wnYdLEpgI). This help you to understand `git` more clearly.

**Comment by sonalisonawane** [comment]
I understood the concept but not able to do it ,instead I created all mess, what should I do now

**Comment by sonalisonawane** [comment]
Hello @Vishal-raj-1  sir, I am not able to squashing commits . After seeing so many videos can you plzz help me for this?

**Comment by sonalisonawane** [comment]
> First of all don't be sorry, I know you don't know about squashing that's why I was asking for it. Now You can learn this beautiful concept through this [video](https://youtu.be/f1wnYdLEpgI). This help you to understand `git` more clearly.
I think I am done now ,Can you Plz Check once, and merge my request !

**Comment by sonalisonawane** [comment]
@Vishal-raj-1 I think I am done now ,Can you Plz Check once, and merge my request !

**Review by urvashi-code1255 — APPROVED** [review]
Everything is looking good to me @sonalisonawane :)

**Pull request merged**
