### PR TITLE
a tag added in index.html file to redirect page and delete the index.…

### LINKED ISSUE #31: Change UI of the Project Section
Remove Visit button from here and make image clickable which redirect to the project. Increase the Image size. 

project

### PR DESCRIPTION
**Pull request by khushi935**
#### Issue Number
fixes #31 

#### Describe the changes you've made
I changed the index.html file (added a stage instead of button) and delete the index.js file.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
NA

#### Test plan (OPTIONAL)
NA

#### Checklist
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
hey @khushi935 Please add the whole card div inside the <a> tag not only the image.

**Review by urvashi-code1255 — COMMENTED** [review]
hey @khushi935 Please add the whole card div inside the <a> tag not only the image.

**Comment by khushi935** [comment]
Screenshot (68)
If I add the a tag in whole card then the underline will be shown and its not removing (after i did text-decoration:none).
What should I do now?

**Comment by urvashi-code1255** [comment]
@khushi935 Can you show me the pictures html and css code you used for it?

**Comment by urvashi-code1255** [comment]
@khushi935 Can you show me the pictures html and css code you used for it?

**Comment by khushi935** [comment]
> @khushi935 Can you show me the pictures html and css code you used for it?

Done. I did some mistakes in writing code, now it's not showing underline.

**Comment by khushi935** [comment]
Screenshot (70)

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @khushi935 Good work!!

**Pull request merged**
