### PR TITLE
2048 Game Made responsive

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed issue #1046
Made site responsive

Screenshots:
Earlier:
2048-old

Now:
2048-new

@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri Please view my PR

### CODE REVIEW

**Comment by Bhavya-Sehgal** [comment]
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri Please view my PR

**Comment by Bhavya-Sehgal** [comment]
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri Please view my PR

**Comment by 991rajat** [comment]
In 400px It's getting trimmed Look into this
image

**Comment by Bhavya-Sehgal** [comment]
okay I will update that.

**Comment by Bhavya-Sehgal** [comment]
Changes updated kindly check
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri @991rajat

**Comment by 991rajat** [comment]
Great Work. Keep Contributing.

**Pull request merged**
