### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by manisha-27**
Closes: #1302 

### Describe the changes you've made
Using HTML, CSS, and JavaScript to create a fully functional weather app.
Also added humidity, wind speed as well as the weather condition fully responsive with images.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (468)

Screenshot (467)

### CODE REVIEW

**Comment by 991rajat** [comment]
Hey @manisha-27 Weather already exist. Just Replace the old with new one of yours.

**Comment by manisha-27** [comment]
hey @991rajat please check this issue, I've replaced with it.

**Comment by 991rajat** [comment]
Looks Good, Just replace old gif with new one
image

**Comment by manisha-27** [comment]
hey @991rajat  please check now, I've added gif.

**Pull request merged**
