### PR TITLE
Giveaway

### PR DESCRIPTION
**Pull request by pritamkr1**
## Related Issue
  - Info about Issue or bug

Closes: #400 

### Describe the changes you've made
It is a basic giveaway app using vanila JS. ti shows a giveaway for computer.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (99)

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@pritamkr1 Resolve conflicts Please !!

**Comment by pritamkr1** [comment]
But How @Vishal-raj-1

**Comment by pritamkr1** [comment]
my branch is up to date with 'origin/giveaway' @Vishal-raj-1

**Comment by 991rajat** [comment]
Thanks for the contribution. :star_struck:

**Comment by 991rajat** [comment]
Learn about Squashing the commits it's a good practice.

**Pull request merged**
