### PR TITLE
Added a new project CGPA Calculator

### PR DESCRIPTION
**Pull request by Abhikr-git**
## Related Issue
  - Info about Issue or bug
I have added a new project named "CGPA Calculator".
It is a simple project built using HTML, css and javaScript which takes GPA of all Semesters as input  and print out the Total CGPA. 
Closes: #[465]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Made changes in script.js file to add projectName, projectImage and projectUrl.
Added cgpaCalculator.html file in public
Added cgpaCalculator.css in assets/css 
Added cgpaCalculator.js in assets/js 
Added cgpaCalculator.png in assets/Images 
Added cgpaCalculator.gif in assets/GIFs
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (121)

### CODE REVIEW

**Comment by ridsuteri** [comment]
@Abhikr-git there are conflicts in script.js file
kindly resolve them :)

**Comment by harshgupta20** [comment]
Hello @Abhikr-git , Kindly respond within 2 days or we will close it.

**Comment by Abhikr-git** [comment]
@harshgupta20  I've made the changes in the conflicting file script.js, please merge the PR.

**Comment by harshgupta20** [comment]
Hi @Abhikr-git  Squash the commit.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Abhikr-git the project is not added to script file properly,kindly fix it

**Pull request closed without merging**
