### PR TITLE
Grocery Bud

### PR DESCRIPTION
**Pull request by Amit366**
Closes: #740 
### Describe the changes you've made
Added the grocery bud.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots

Screenshot (145)

### CODE REVIEW

**Comment by Amit366** [comment]
grocery

**Review by ridsuteri — COMMENTED** [review]
@Amit366 this project looks nice !,but since a similar one already exists so you can either improve that  project by adding styles or by adding delete item feature to that project or try to add any other awesome project

**Comment by Amit366** [comment]
Screenshot (163)

**Comment by Amit366** [comment]
@Vishal-raj-1 is it fine now or anything else need to add??

**Comment by Amit366** [comment]
@ridsuteri is it fine now??

**Comment by ridsuteri** [comment]
> @ridsuteri is it fine now??

yes this looks great !! but can you do these improvements in the local storage project(similar project in the repo) instead of making it anohter project?

**Comment by Amit366** [comment]
@ridsuteri then I might get a lower level 😅😅

**Comment by ridsuteri** [comment]
> @ridsuteri then I might get a lower level 😅😅

yeah but exactly similar project already exists :(  , you if want you can add any new project ...

**Comment by Amit366** [comment]
@ridsuteri almost all new projects are in the repo or already someone is working on it . So what new project can I add.

**Comment by ridsuteri** [comment]
> @ridsuteri almost all new projects are in the repo or already someone is working on it . So what new project can I add.

there are lots of people coming up with new projects everyday...,there can still be many projects that can be added to the repo..

**Comment by Amit366** [comment]
@ridsuteri ok sir I will add my code to the existing repo. But I created an issue now please assign that to me.

**Comment by ridsuteri** [comment]
ok @Amit366 so should i close this PR now?

**Comment by Amit366** [comment]
@ridsuteri I will the code. So don't close

**Comment by ridsuteri** [comment]
> @ridsuteri I will add the code. So don't close. At least can I get a level 2??

add the code as in new project?

**Comment by Amit366** [comment]
@ridsuteri I will add the code to existing project, right??

**Comment by ridsuteri** [comment]
ok great @Amit366 ,go ahead

**Comment by Amit366** [comment]
@ridsuteri will I get a level 2?? Just asking

**Comment by ridsuteri** [comment]
for that it would be better if you create a new fresh PR and a new issue
since this issue and PR is for adding new grocery project

**Comment by ridsuteri** [comment]
@Amit366 about the level i will ask the admins and let you know

**Comment by Amit366** [comment]
> for that it would be better if you create a new fresh PR and a new issue
> since this issue and PR is for adding new grocery project

@ridsuteri I created a new issue on grocery bud and so I sent this PR. But you said to just add the code to the existing project.

**Comment by ridsuteri** [comment]
> > for that it would be better if you create a new fresh PR and a new issue
> > since this issue and PR is for adding new grocery project
> 
> @ridsuteri I created a new issue on grocery bud and so I sent this PR. But you said to just add the code to the existing project.

yes @Amit366 i asked you to update the exsiting project and this PR is adding a new project...so i want you to close this PR and open another one where you will update the existing code..

**Comment by Amit366** [comment]
@ridsuteri ok. But one doubt can I make the existing project similar to mine. Like the way I did??

**Comment by ridsuteri** [comment]
@Amit366 yes you can :)

**Comment by ridsuteri** [comment]
@Amit366 so i am closing this PR and the related issue now  !
open another issue and PR for improvement in the existing project ..

**Pull request closed without merging**
