### PR TITLE
Text to Speech

### PR DESCRIPTION
**Pull request by bitaashna**
#247 

Closes: #247

 **Describe the changes you've made**

- A text to speech app for non-verbal conversations. Pre-made buttons and custom text speech is made
- Created a responsive UI (CSS Grid) with picture buttons
- Speaks the text when button clicked
- Drop down custom text to speech
- Speaks the text typed in the text area
- Change voices and accents(in the language of your own choice)
- A ripple Effect is added which comes into action when something is typed in the text area.

**Describe if there is any unusual behaviour of your code**
NA

**Checklist:**

- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

*Screenshots* 
speechText

#gssoc'21

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@bitaashna Project is looking good to me :)

Please resolve the merge conflicts

**Comment by bitaashna** [comment]
how to resolve this @urvashi-code1255 . I have no idea .Please help me with this

**Comment by bitaashna** [comment]
@urvashi-code1255  Please review it!!

**Review by bitaashna — COMMENTED** [review]
I have resolved the issues.
Hey @urvashi-code1255 do check it!

**Comment by urvashi-code1255** [comment]
@bitaashna Please resolve the merge conflicts again and tag me when you are done with that

**Comment by bitaashna** [comment]
@urvashi-code1255 Please check it.I have resolved the issue

**Review by urvashi-code1255 — APPROVED** [review]
Thanks for contributing @bitaashna :)

**Pull request merged**
