### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by pritamkr1**
## Related Issue
  - Info about Issue or bug

Closes: #331

### Describe the changes you've made
I have added a project progress bar to this  **Awesome-JavaScript-Projects**  It contains three files that are  progressbar.html, progressbar.css and prgressbar.js. It shows progress in % of HTML, CSS, JavaScript, React and WordPress.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented on my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (27)

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@pritamkr1 Seperate the files into css html and js files. Also add your project details in script.js like the other projects

**Comment by pritamkr1** [comment]
Done! please have look.

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @pritamkr1 You haven't added your project details in script.js like the other projects

**Comment by pritamkr1** [comment]
ma'am m not getting your point. you mean to say comment all thing js file one by one??

**Comment by pritamkr1** [comment]
Done! now.

**Comment by pritamkr1** [comment]
please assign into this giveaway app using vanilaJS #400

**Comment by 991rajat** [comment]
@pritamkr1 I didn't get it explain me this project a little.
Squash the commits too.

**Comment by pritamkr1** [comment]
I'm totally confused about it how it shows in #390  and Resolves conflicts as well.

**Comment by pritamkr1** [comment]
When I did My PR, all my PR showing here ... I don't why 
I'm a newbie here please fix it?

**Comment by pritamkr1** [comment]
it shows all my commits in #390 .

**Comment by 991rajat** [comment]
@pritamkr1 It is OK #390 is PR no and issue no is different from it.
I was addressing to link the issue rightly i.e, 
In description remove square brackets, it will link your issue
> closes #331

**Comment by pritamkr1** [comment]
squash the commits mean ??

**Comment by pritamkr1** [comment]
I don't know what I did please fix it, sir??

**Comment by 991rajat** [comment]
I will link the issue No worries.
What squashing does is it combines multiple commits into single commit removing unnecessary commits and add descriptive message. what you need to do is to squash them into one
squash only your 10 commits into one.
https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc
You try yourself 
Let me know if need any help.

**Pull request merged**
