### PR TITLE
 Added auto response when pr is merged

### PR DESCRIPTION
**Pull request by AB-san**
## Related Issue

Closes: #941 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by 991rajat** [comment]
@Vishal-raj-1 Look into this.

**Comment by AB-san** [comment]
@ridsuteri  @Vishal-raj-1  please kindly review this pr

**Comment by ridsuteri** [comment]
@urvashi-code1255

**Comment by AB-san** [comment]
@urvashi-code1255  @Vishal-raj-1 please review this pr

**Comment by AB-san** [comment]
@Vishal-raj-1 I think you forgot about adding level tags?

**Comment by AB-san** [comment]
> @Vishal-raj-1 I think you forgot about adding level tags?

@urvashi-code1255 @ridsuteri @991rajat

**Pull request merged**
