### PR TITLE
3d flip card added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
3d flip card added
Closes: #1663

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/119831722-2cb4ca00-bf1b-11eb-88e8-656aebc44b0c.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri Sir Please review my PR .

**Comment by Vishal-raj-1** [comment]
Resolve conflicts please

**Comment by Ankita297** [comment]
done sir

**Comment by Vishal-raj-1** [comment]
@Ankita297 Good going !! I hope to see you in top 25. All the best 👍🏻

**Comment by Ankita297** [comment]
thank you Sir

**Pull request merged**
