### PR TITLE
modify video player project #1129

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - modify video player project #1129

Closes: #1129 

### Describe the changes you've made
- Fix the Fullscreen issue.
- Added PIP feature.
- Modify styling.
- Make well responsive.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Before 

video-player

After

videoPlayer

### CODE REVIEW

**Comment by Vedant-Rahane** [comment]
@991rajat Can you please tell, why it is showing kanisshka name in my commit? 
I had just pull upstream before making PR.

**Review by 991rajat — APPROVED** [review]
Looks Sleek. Great work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by Vedant-Rahane** [comment]
@991rajat Can you please change the label to `level2`. I have added more features and the old project was having many bugs.

**Pull request merged**
