### PR TITLE
gifs is updated  of some projects

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
  - Gifs of some projects is not displayed

Closes: #992 

### Describe the changes you've made
I have made the gifs and updated it .

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Projects _ Awesome JavaScript - Google Chrome 16-04-2021 14_15_28
Projects _ Awesome JavaScript - Google Chrome 16-04-2021 14_17_04

Projects _ Awesome JavaScript - Google Chrome 16-04-2021 14_20_34

### CODE REVIEW

**Comment by Ankita297** [comment]
color-flipper
flappy-bird
Text-voice converter

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri @urvashi-code1255  Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri @urvashi-code1255  Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri @urvashi-code1255  Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri @urvashi-code1255 Please review my PR .

**Comment by 991rajat** [comment]
Good Work. Keep Contributing.

**Pull request merged**
