### PR TITLE
Changed the Positon of Dark-Mode Toggler

### PR DESCRIPTION
**Pull request by Atif0604**
## Related Issue
  - Changed the Positon of Dark-Mode Toggler

Closes: #1847 will be closed through this PR(Position of Dark Mode icon #1847)

### Describe the changes you've made
Changed the Positon of Dark-Mode Toggler and placed it just above the scroll to top toggler

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [✔️ ] My code follows the style guidelines of this project.
- [✔️ ] I have performed a self-review of my own code.
- [✔️ ] I have commented my code, particularly in hard-to-understand areas.
- [✔️ ] I have made corresponding changes to the documentation.
- [✔️ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot 2021-06-29 144000
Screenshot 2021-06-29 144023
Screenshot 2021-06-29 144041

### CODE REVIEW

**Comment by Atif0604** [comment]
Please Review my PR @Ankita297

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Hey, Can you put the button on top right corner?

**Comment by Atif0604** [comment]
> Hey, Can you put the button on top right corner?

image
is it fine @Rizwan-S

**Comment by Rizwan-S** [comment]
Yes! Absolutely.

**Pull request merged**
