### PR TITLE
Smooth Transition while hovering

### PR DESCRIPTION
**Pull request by Ankit0225**
Signed-off-by: Ankit <ankitmaurya0225@gmail.com>

## Related Issue
  - Info about Issue or bug

Closes: #196

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
cou

### CODE REVIEW

**Comment by Ankit0225** [comment]
also, add 3d effect while hovering

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @Ankit0225 fill the PR template!!

**Comment by Ankit0225** [comment]
I had filled the PR template and added a screenshot of the contribution that I have done

**Comment by urvashi-code1255** [comment]
Hey @Ankit0225 you have to write "Closes: #issue_number"

**Comment by Ankit0225** [comment]
See Now

**Comment by Ankit0225** [comment]
@urvashi-code1255

**Review by urvashi-code1255 — APPROVED** [review]
It LGTM @Ankit0225 :)

**Pull request merged**
