### PR TITLE
Welcome bot added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
Welcome bot added
Closes: #1149 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11

### CODE REVIEW

**Review by urvashi-code1255 — APPROVED** [review]
Good work @Ankita297

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 Please merge my PR .

**Comment by Ankita297** [comment]
@991rajat @Vishal-raj-1 @ridsuteri Please review my PR .

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 :)

**Pull request merged**
