### PR TITLE
Image changed

### PR DESCRIPTION
**Pull request by Iftu119**
The card image has been changed so that people can relate easily rather than seeing the image of the webpage. Also removed an extra white space.

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
Thanks for contribution !! LGTM But before I merge can you please share the preview using github pages or video clip or screenshots.

**Comment by Iftu119** [comment]
Hello @Vishal-raj-1 , I don't know why my browser failed to show the images. Hence I could not view the images before I made the PR.

**Comment by Vishal-raj-1** [comment]
Hello @Iftu119 Can you just show me the preview by hosting the website using github pages. This PR contains conflicts as well . Please resolve them as well.

**Comment by Iftu119** [comment]
Okay. I shall be resolving the conflicts and post the visual here in 2-3 days.

**Comment by Iftu119** [comment]
I cannot understand why the images are not showing up. Got some conflicts as well. I guess **we can close this PR** and I will be trying once again with new PR.

image

**Comment by Vishal-raj-1** [comment]
Okay, I am closing this PR !! Looking forward to more PR from your side !!

**Pull request closed without merging**
