### PR TITLE
music-box added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
music-box added
Closes: #330 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/116006700-005f1280-a62a-11eb-9d26-504558193fac.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri @harshgupta20 @urvashi-code1255 Please review my PR .

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 , thanks for contributing :)

**Comment by Ankita297** [comment]
@harshgupta20 @ridsuteri @urvashi-code1255 is this issue is not of level 3.

**Comment by Ankita297** [comment]
Please label it .

**Comment by Ankita297** [comment]
@harshgupta20 @ridsuteri @urvashi-code1255 is this issue is not of level 3.
So, i have a request please label it .

**Comment by Ankita297** [comment]
@991rajat ?

**Comment by Ankita297** [comment]
Thank You @991rajat .

**Pull request merged**
