### PR TITLE
Line replacing js project project

### PR DESCRIPTION
**Pull request by mahesh-11102**
## About `Line replacing` Js project 
- This project contains a box where you type some text .
- After typing you need to click on the submit button to replace the below line.

### I have made the following changes :-
- Added Line replacing `html` file.
- Added line replacing `js` file.
- Added  line replacings `css` file.
- Added `gif` for line replacing project.
- Updated `script.js` file.

## Describe if there is any unusual behaviour of your code
`NA`

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots
line-replacing-project (1)

@ridsuteri  @Harshal0902  @urvashi-code1255  @991rajat  @Vishal-raj-1  , please verify the changes and guide me if any changes are required :)

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@mahesh-11102 project looks good ,but the project is not linked with the project card
i.e project is not opening when line replacing card in projects section is being clicked

**Comment by mahesh-11102** [comment]
@ridsuteri  i have updated the script.js file now my project is working on clicking on the project card also i have  removed duplicate project name and updated missing gif :)
please verify it

**Review by ridsuteri — APPROVED** [review]
looks great @mahesh-11102 ,thanks for contributing :)

**Comment by mahesh-11102** [comment]
Thank you @ridsuteri  sir :)

**Pull request merged**
