### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by sneha-nitdgp**
## Related Issue
  - Updated the footer

Closes: #[322](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/issues/322)

### Describe the changes you've made
Improved the footer. Added links, tech stacks used and contact us.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [✔️ ] My code follows the style guidelines of this project.
- [ ✔️] I have performed a self-review of my own code.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.
- [✔️ ] I have made corresponding changes to the documentation.
- [✔️ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
footer latest

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@sneha-nitdgp the changes you made are not responsive, try to make them responsive :)

**Comment by sneha-nitdgp** [comment]
@ridsuteri It was responsive..please check once more.

**Comment by ridsuteri** [comment]
@sneha-nitdgp have a look 
Screenshot (12)

**Comment by sneha-nitdgp** [comment]
@ridsuteri I had checked in inspect mode for all screen sizes. Don't know why it's coming this way. I'm looking after it.

**Comment by ridsuteri** [comment]
@sneha-nitdgp any updates ?

**Comment by ridsuteri** [comment]
@sneha-nitdgp any progress ?

**Comment by urvashi-code1255** [comment]
@sneha-nitdgp ?

**Comment by ridsuteri** [comment]
it's beeen so long ! i am closing this PR now @sneha-nitdgp  :(

**Pull request closed without merging**
