### PR TITLE
add love calculator code

### PR DESCRIPTION
**Pull request by sonalisonawane**
## Related Issue
  JavaScript Love Calculator

Closes: #469

### Describe the changes you've made
I had added The code of Love Calculator, It includes Event listeners, pre-loader, audio file control from js and various inbuilt functions of JavaScript like Math.random etc

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

love-1

### CODE REVIEW

**Comment by sonalisonawane** [comment]
@ridsuteri sir can you plz merge my pull request.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@sonalisonawane kindly resolve the merge conflicts

**Comment by sonalisonawane** [comment]
Conflicts Resolved.

**Review by ridsuteri — APPROVED** [review]
thanks for contributing @sonalisonawane :)

**Comment by sonalisonawane** [comment]
Thank you @ridsuteri Sir :)

**Pull request merged**
