### PR TITLE
RotatingNavigation[ggsoc21]

### PR DESCRIPTION
**Pull request by Deeksha-Rawat**
## Related Issue
  - Info about Issue or bug

Closes: #446

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Deeksha-Rawat** [comment]
Its a rotating navigation bar made completely using vanilla javascript

**Comment by ridsuteri** [comment]
@Deeksha-Rawat kindly resolve the conflicts

**Comment by Deeksha-Rawat** [comment]
Hi @ridsuteri I am not able to figure out whats the issue with the file. As it is working properly in my local server.
Could you please help me with the issue.

**Comment by ridsuteri** [comment]
@Deeksha-Rawat  ya sure
Screenshot (1)
see here is the conflict 
refer to this : https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by Deeksha-Rawat** [comment]
I have made the required changes. Hope it will work now
please look into it.
Thanks

**Review by ridsuteri — APPROVED** [review]

**Comment by ridsuteri** [comment]
good work @Deeksha-Rawat ! thanks for contributing :)

**Comment by Deeksha-Rawat** [comment]
@ridsuteri @urvashi-code1255  @Vishal-raj-1   please add labels to my PR. It will help me to get the score.
label is assigned only in the issue and not in PR so it is not added to my score

**Pull request merged**
