### PR TITLE
selection sort visualizer in javascript added

### PR DESCRIPTION
**Pull request by shivammahajancse**
## Related Issue
  - Info about Issue or bug

Closes: #1201  

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@shivammahajancse project looks really nice! just fix the project's gif/screenshot in the script file :)

**Comment by shivammahajancse** [comment]
Changes done sir @ridsuteri

**Comment by 991rajat** [comment]
@shivammahajancse Its png type. not assets/GIFs/selection-visualizing.jpg.

**Comment by shivammahajancse** [comment]
Changes done sir @991rajat

**Comment by 991rajat** [comment]
Thanks for contributing.

**Comment by 991rajat** [comment]
Keep Contributing.

**Pull request merged**
