### PR TITLE
added typewriter-effect using vanilla js

### PR DESCRIPTION
**Pull request by SanskaarPatni**
## Related Issue
  - Typewriter effect using vanilla js
Closes: #282 

### Describe the changes you've made
I've added 3 files.
1.typewriter.html - HTML code for the project.  public/typewriter.html
2.typewriter.css - CSS code for the project.   assets/css/typewriter.css
3.typewriter.js - Javascript code for the project. assets/js/typewriter.js

Added two methods to achieve the typewriter effect!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot from 2021-03-14 12-00-49

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@SanskaarPatni Add your project details in script.js like the other projects

**Comment by SanskaarPatni** [comment]
Added gif and project details to script.js

**Comment by SanskaarPatni** [comment]
Added gif and project details to script.js @urvashi-code1255

**Comment by 991rajat** [comment]
@SanskaarPatni Please Resolve the conflict and squash commit.
Let me know if you need any help.

**Comment by SanskaarPatni** [comment]
I was trying to squash commits but in the end always ran into some problem.
I've opened a new pr- added typewriter effect #680 
Kindly merge that one. By your permission I'll close this pull request.
@Vishal-raj-1 @urvashi-code1255

**Pull request closed without merging**
