### PR TITLE
Search bar updated

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
Search bar updated
Closes: #1324 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/117580008-60b67f80-b113-11eb-8e11-7635375dd047.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@harshgupta20 @urvashi-code1255 @Vishal-raj-1 @991rajat Please review my PR .

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR.

**Comment by 991rajat** [comment]
@Ankita297 Animation is bit off I think, It needs two click to search, Fix it After one click it should search.

**Comment by Ankita297** [comment]
Sir i am closing this PR  I have opened a new PR #1518 .

**Pull request closed without merging**
