### PR TITLE
Added the new breakout game with music  and replaced the old one.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
## Related Issue
  - To add the breakout game by replacing old one.
 
Closes: #1164 

### Describe the changes you've made
Added the brick breaker /breakout game implementwd in javascript with sounds and music in it.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot from 2021-04-25 01-42-44
Screenshot from 2021-04-25 01-43-14
Screenshot from 2021-04-25 01-44-10

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
Please Review.@991rajat

**Comment by 991rajat** [comment]
Hey @Shivangi-ch Game looks good, just replace the old gif with new one of yours.
If the gif you create is of more than 1MB you can use static image.
image

**Comment by Shivangi-ch** [comment]
@991rajat I have done the requested changes. Please review

**Comment by 991rajat** [comment]
image
Hey @Shivangi-ch Just fix the path of image script.js.
Now its png.

**Comment by Shivangi-ch** [comment]
Please Review.@991rajat

**Comment by 991rajat** [comment]
Looks Good. Great Work

**Comment by 991rajat** [comment]
Thanks for the contribution.
Keep Contributing.

**Pull request merged**
