### PR TITLE
add word couter app

### PR DESCRIPTION
**Pull request by swapnilbhakare**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
word-counter-short

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Resolve the merge conflicts

**Comment by swapnilbhakare** [comment]
Hello sir 
I  removed conflict

**Comment by Vishal-raj-1** [comment]
@swapnilbhakare Could you please enable github pages on your forked repo as well so that I can see your changes too.

**Comment by swapnilbhakare** [comment]
Ok I will

**Comment by swapnilbhakare** [comment]
All conflicts are solved.

**Comment by urvashi-code1255** [comment]
Hey @swapnilbhakare Read [this](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) for enabling the github pages.

**Comment by swapnilbhakare** [comment]
Done

**Comment by urvashi-code1255** [comment]
> Done

Share the link of your hosted site here.

**Comment by swapnilbhakare** [comment]
Sure! @urvashi-code1255 mam , here it is :
https://swapnilbhakare.github.io/Awesome-JavaScript-Projects/

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM

**Pull request merged**
