### PR TITLE
DarkMode

### PR DESCRIPTION
**Pull request by vasanthgk02**
## Created a new project

I have mistakenly closed this issue #439. So I made a new pull request.

### Describe the changes you've made
I have add new files of DarkMode. It changes theme from white mode to dark mode when clicking the toggle button and vice versa.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [Y] My code follows the style guidelines of this project.
- [Y] I have performed a self-review of my own code.
- [Y] I have commented my code, particularly in hard-to-understand areas.
- [Y] I have made corresponding changes to the documentation.
- [Y] New and existing unit tests pass locally with my changes.

### White Mode
DarkMode 1

### Dark Mode
DarkMode 2

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@vasanthgk02 kindly add this project to the script.js

**Comment by vasanthgk02** [comment]
Now I have updated the script.js file..
Please check @ridsuteri @urvashi-code1255

**Review by vasanthgk02 — COMMENTED** [review]
I have updated script.js
Please have a look @ridsuteri and @urvashi-code1255

**Comment by vasanthgk02** [comment]
I have updated script.js
Please have a look @urvashi-code1255 and @ridsuteri

**Review by ridsuteri — APPROVED** [review]
good work @vasanthgk02 ,thanks for contributing :)

**Pull request merged**
