### PR TITLE
Face detector added

### PR DESCRIPTION
**Pull request by Ananya-Misra**
## Related Issue
  - Info about Issue or bug

Closes: #1374

### Describe the changes you've made
I have added a face detector app that opens/closes your webcam and detects your face with the click of a button.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Face Detector

### CODE REVIEW

**Comment by Ananya-Misra** [comment]
@ridsuteri @991rajat Please review my PR.

**Comment by Ananya-Misra** [comment]
@ridsuteri @991rajat Kindly review my PR.

**Comment by Ananya-Misra** [comment]
@urvashi-code1255 @ridsuteri @991rajat Please review this PR.

**Comment by Ananya-Misra** [comment]
@Vishal-raj-1 Please review this PR

**Review by ridsuteri — APPROVED** [review]
good work @Ananya-Misra :)

**Pull request merged**
