### PR TITLE
Login Credential is made

### PR DESCRIPTION
**Pull request by diptendunandi**
## New Feature
  - Login Credential

### Describe the changes you've made
Added an Authentication Process

### Describe if there is any unusual behavior of my code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (80)

### CODE REVIEW

**Comment by diptendunandi** [comment]
Please add this feature @urvashi-code1255

**Comment by Vishal-raj-1** [comment]
@diptendunandi Resolve conflicts first

**Comment by urvashi-code1255** [comment]
Hey @diptendunandi Any updates on this PR?

**Comment by diptendunandi** [comment]
> Hey @diptendunandi Any updates on this PR?

I will do it on Wednesday.  Sorry for the inconvenience

**Comment by urvashi-code1255** [comment]
> I will do it on Wednesday. Sorry for the inconvenience

Hey @diptendunandi Any updates on this PR?

**Comment by urvashi-code1255** [comment]
Hey, @diptendunandi Any updates?

**Comment by diptendunandi** [comment]
After 17 th March for sure. Due to exam I can not focus in it. Sorry for that

**Comment by Vishal-raj-1** [comment]
@diptendunandi ?

**Pull request closed without merging**
