### PR TITLE
fixed issue 920

### PR DESCRIPTION
**Pull request by hritikgupta92**
Closes: #920 

### Describe the changes you've made
Created a simple webpage for a web development course that was organised by 3rd year Students for fellow juniors using  HTML,CSS and JS which provides details of the faculty on clicking the button for that,and generate  data for students on clicking another button
 
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
 

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Comment by hritikgupta92** [comment]
@991rajat  plz reivew this

**Comment by 991rajat** [comment]
Add the project to script.js. Reduce the size of the gif. If not able to do reduce the duration and resolution, try again. If not able tow work replace it with static image.
Make the gif under 500KB or so.
Also break the file in html/css/js
move it in different files like css content in css.

**Comment by hritikgupta92** [comment]
> Add the project to script.js. Reduce the size of the gif. If not able to do reduce the duration and resolution, try again. If not able tow work replace it with static image.
> Make the gif under 500KB or so.
> Also break the file in html/css/js
> move it in different files like css content in css.

ok i'll make the changes

**Comment by 991rajat** [comment]
@hritikgupta92 Any Updates?

**Comment by hritikgupta92** [comment]
> @hritikgupta92 Any Updates?

sorry sir,was busy from 5-6 days after that got stuck by covid 19 so,was resting from 3-4 days,I will complete it asap

**Comment by 991rajat** [comment]
Hey @hritikgupta92  no Worries. Be Safe and Healthy. Don't work now. Take rest and recover for 2-2.5 Weeks atleast, I understand.
After that you can work, no problem. You can push it later.

**Comment by hritikgupta92** [comment]
> Hey @hritikgupta92 no Worries. Be Safe and Healthy. Don't work now. Take rest and recover for 2-2.5 Weeks atleast, I understand.
> After that you can work, no problem. You can push it later.

ok,thankyou

**Comment by harshgupta20** [comment]
@hritikgupta92 No problem.

**Pull request closed without merging**
