### PR TITLE
added maze game

### LINKED ISSUE #57: Maze game in js
## Is your feature request related to a problem? Please describe.
YES
## Describe the solution you'd like
Would like to add a maze game that will be having different levels and built using js, html, css
## Additional context
Add any other context about the feature request here.
would like to work n this as part of crossWoc

### PR DESCRIPTION
**Pull request by Sloth-Panda**
#### Issue Number
fixes #57 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Implemented a maze game using js in which there are 4 different levels and  atlast when someone reaches a target the game displays the number of steps in which it was completed.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
No unusual behaviour
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
By checking the main site after the pr gets merged
#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
Hello @Sloth-Panda, let me explain you how you & we both can see the changes without merging the PR. Go to your forked repo => Setting => General => Github Pages. Enable github pages by choosing the branch and theme, every time you can send the PR, send your local site using github pages link. 


Apart from that, We should also focus on code formatting means unnecessary line gap, spaces is not accepted. You are doing great Man !! Keep it Up 👍🏻

**Comment by Sloth-Panda** [comment]
@Vishal-raj-1 can you please check this, I have resolved the conflict.

**Comment by Sloth-Panda** [comment]
> Hello @Sloth-Panda, let me explain you how you & we both can see the changes without merging the PR. Go to your forked repo => Setting => General => Github Pages. Enable github pages by choosing the branch and theme, every time you can send the PR, send your local site using github pages link.
> 
> Apart from that, We should also focus on code formatting means unnecessary line gap, spaces is not accepted. You are doing great Man !! Keep it Up 👍🏻

In that dont I have to again name that file's name to "index.html" like the projects main  html file?

**Comment by urvashi-code1255** [comment]
> In that dont I have to again name that file's name to "index.html" like the projects main  html file?

No @Sloth-Panda you don't have to name it index.html

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I pushed the code for this "maze game issue"  from branch "m2" and then I went ahead and on my forked repo 
I went to github pages and published branch "m2" from there https://sloth-panda.github.io/Awesome-JavaScript-Projects/

but it says 404 ? what  is the issue?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 I pushed the code for this "maze game issue" from branch "m2" and then I went ahead and on my forked repo
> I went to github pages and published branch "m2" from there https://sloth-panda.github.io/Awesome-JavaScript-Projects/
> 
> but it says 404 ? what is the issue?

Hey @Sloth-Panda This hosted link is working fine for me!!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I  think it took some time to load the content probably more than 5mins. Have u checked the prs? I am thinking of closing these two prs and making a single pr for both the two issues as there was some problem and i was not able to push the code

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda I think all your assigned three issues changes have been merged through your first PR which @Vishal-raj-1 has merged!! 

So, I think you can close both of these issues!!

And I will mark your points for all three of them!!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 but I can just see one commit getting merged can you confirm?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 but I can just see one commit getting merged can you confirm?

Okay @Sloth-Panda So for confirmation you can check your both projects have merged in the website [here](https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/)

and you can check the name of the PR template which you did is correct now [here](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/pull_request_template.md)

**Comment by urvashi-code1255** [comment]
> U mean this one?

Yes @Sloth-Panda As @Vishal-raj-1 has squashed your three commits into 1 so its looking like one but its three.

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I am closing the issues and prs then for both the issues? You are marking the points for all of the merged "3" right?

**Comment by Sloth-Panda** [comment]
> Hello @Sloth-Panda, let me explain you how you & we both can see the changes without merging the PR. Go to your forked repo => Setting => General => Github Pages. Enable github pages by choosing the branch and theme, every time you can send the PR, send your local site using github pages link.
> 
> Apart from that, We should also focus on code formatting means unnecessary line gap, spaces is not accepted. You are doing great Man !! Keep it Up 👍🏻

Should I  publish the branch from which I am making pr?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 I am closing the issues and prs then for both the issues? You are marking the points for all of the merged "3" right?

Yes @Sloth-Panda !!

**Comment by Sloth-Panda** [comment]
@urvashi-code1255, I have some doubts (1). I see when I am making one pr, it is having commits of the previous prs I mean how can  I make commits for only one issue in one pr? Like here you saw what should have been 3 prs commits got merged in 1pr?
(2) how can I get this site or sites like this to work https://Sloth-Panda.github.io/

**Pull request closed without merging**
