### PR TITLE
Revamp the Analog Clock 

### PR DESCRIPTION
**Pull request by chaitanyashimpi**
## Related Issue
 @urvashi-code1255  The design of the clock was not modern and attractive.

Closes: #216 

### Describe the changes you've made
I have changed the code of the Analog clock from HTML, CSS to js. I was used less code and had used the glassmorphism style.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [  ] I have commented on my code, particularly in hard-to-understand areas.
- [  ] I have made corresponding changes to the documentation.
- [ x ] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255  It will be great if you check out my update. So that I can work on a new project for Awesome JavaScript Projects.

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM !!

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 Can you please tag this merge with the tag of GSSOC `21 and the proper level

**Comment by Vishal-raj-1** [comment]
@chaitanyashimpi Brother I have merged this issue on 7 march. Now if I add the labels then also it will not be calculated as gssoc is started from 8 march.

**Pull request merged**
