### PR TITLE
css gadient background project added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
css gadient background project added
Closes: #1626

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/119322128-f9fc9e80-bc9a-11eb-9355-6ddf0b931a4f.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri Sir Please review my PR .

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR .

**Comment by Ankita297** [comment]
@ridsuteri Sir Please review my PR .

**Comment by ridsuteri** [comment]
@Ankita297 closing this as similar project already exists :(

**Comment by Ankita297** [comment]
@ridsuteri 
screencapture-vishal-raj-1-github-io-Awesome-JavaScript-Projects-public-gradientBackgroundGen-html-2021-05-26-12_50_29

@ridsuteri Sir the peoject is different from that one in this the background moves automatically and color changes

**Comment by ridsuteri** [comment]
> @ridsuteri this is Project you are talking about right in this on clicking the button you get different background
> screencapture-vishal-raj-1-github-io-Awesome-JavaScript-Projects-public-gradientBackgroundGen-html-2021-05-26-12_50_29
> 
> @ridsuteri Sir the project is different from that one in this the background moves automatically and color changes
> So can you kindly take a look into it .

ok ok sorry my bad !

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 :)

**Pull request merged**
