### PR TITLE
UI updated - Palindrome checker

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed- #774 
UI Updated and made responsive.

Screenshots:

pc-1

pc-2

pc-3

pc-4

@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Bhavya-Sehgal  looks good ! just update the gif in the script file

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal looks good ! just update the gif in the script file

okay, sure.

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal looks good ! just update the gif in the script file

Added file @Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri

**Review by ridsuteri — APPROVED** [review]
good work @Bhavya-Sehgal :)

**Pull request merged**
