### PR TITLE
Added project Pig Game

### PR DESCRIPTION
**Pull request by aashi2912**
## Related Issue
  successfully added the project pig game.

Closes: #1376 

### Describe the changes you've made
Added project files: PigGame.html, PigGame.css, PigGame.js, project related data in script.js, related images and PigGame.GIF too added.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

Do review it, all functionalities working fine. @ridsuteri 

### Screenshots

pig game
ss1_piggame
ss2_piggame
winner

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
project looks cool @aashi2912 , but the dice img is not loading on my side :(
Screenshot (70)

please verify and resolve :)

**Comment by aashi2912** [comment]
Hi, made changes. Check now.

**Comment by aashi2912** [comment]
Also add the labels of level. @ridsuteri

**Review by ridsuteri — APPROVED** [review]
good work @aashi2912 :)

**Comment by aashi2912** [comment]
> good work @aashi2912 :)

Thank you!😄🙂

**Pull request merged**
