### PR TITLE
Finish bubble sort

### PR DESCRIPTION
**Pull request by akshitadixit**
My PR for adding bubble sort was merged, and the algorithm for it was supposed to be added another person assigned the same issue who did not do it.

This PR adds algorithm for color changing array with bubble sort.

### CODE REVIEW

**Comment by akshitadixit** [comment]
I'm a gssoc participant

**Comment by Vishal-raj-1** [comment]
What are you doing here ? There are 54 files changed. Make changes in your files only

**Comment by urvashi-code1255** [comment]
I think @akshitadixit  has accidentally taken changes of many PRs!!

**Comment by akshitadixit** [comment]
I just pulled the repo.

**Comment by 991rajat** [comment]
@akshitadixit What you can do is create a new PR, if not able to resolve,
Sync the main branch -> create a new branch -> add the code -> PR

**Comment by akshitadixit** [comment]
> @akshitadixit What you can do is create a new PR, if not able to resolve
> Sync the main branch -> create a new branch -> add the code -> PR

thank you for replying

**Comment by 991rajat** [comment]
When you create new PR close this one or let us know we will close it.

**Pull request closed without merging**
