### PR TITLE
Added Filter_Search in Awesome-JavaScript-Projects/public

### PR DESCRIPTION
**Pull request by Maitryee-Choudhary**
## Related Issue
  The project aims that it will have list of items/images and based on user filter it will display the item/image that corresponds 
  to required filter.
 It will be easy for the user to have the content by filtering the items.
 I will be displaying group of images and after applying filter, corresponding list of images will be display.

Closes: #[issue number that will be closed through this PR]
           Issue Number: 297

### Describe the changes you've made
   I have added a new file name Filter_Search.html in Awesome-JavaScript-Projects/public.
  

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
  NA

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
    The project  looks like:
  
Screenshot

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@Maitryee-Choudhary Please pull the recent changes!

**Comment by Maitryee-Choudhary** [comment]
> @Maitryee-Choudhary Please pull the recent changes!

Done. Please have a look.

**Comment by urvashi-code1255** [comment]
@Maitryee-Choudhary Please resolve the merge conflicts and tag me when you are done :)

**Comment by Maitryee-Choudhary** [comment]
> @Maitryee-Choudhary Please resolve the merge conflicts and tag me when you are done :)

Done.Please have a look @urvashi-code1255

**Comment by urvashi-code1255** [comment]
@Maitryee-Choudhary

**Comment by Maitryee-Choudhary** [comment]
> @Maitryee-Choudhary

Done.Now it is correct?

**Review by 991rajat — CHANGES_REQUESTED** [review]
Please squash the commits into 1 or 2 commit.
Resolve the conflict.
Also link the issue no.

**Review by Vishal-raj-1 — APPROVED** [review]
Everything is fine. Just make three seperate file of html,css,js

**Review by 991rajat — APPROVED** [review]

**Comment by 991rajat** [comment]
Yes please separate the css/js/html

**Comment by urvashi-code1255** [comment]
@Maitryee-Choudhary any updates?

**Comment by Maitryee-Choudhary** [comment]
> @Maitryee-Choudhary any updates?

Yes done.

**Comment by 991rajat** [comment]
@Maitryee-Choudhary Looks like you haven't added the project to script.js. Please add the file to script.js.
Also don't make gif or image of bigger size, compress it please.

**Comment by Maitryee-Choudhary** [comment]
Is it correct now? I have added the script.js.

**Comment by 991rajat** [comment]
Fix the gif.
image

Also lot of projects were removed from script.js add them too please.

**Comment by urvashi-code1255** [comment]
@Maitryee-Choudhary any updates?

**Comment by Vishal-raj-1** [comment]
@Maitryee-Choudhary Please Update this PR, as GSSOC is going to end !!

**Pull request merged**
