### PR TITLE
css transform added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
css transform added
Closes: #1666 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/119786452-d4b39e80-beed-11eb-9ee1-ddfbf133b722.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @ridsuteri Sir Please review my PR .

**Comment by Vishal-raj-1** [comment]
Please resolve conflicts

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please see now

**Comment by Ankita297** [comment]
Sir Please review the PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 :)

**Pull request merged**
