### PR TITLE
Parallex effect

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue
  - Parallax Effect using RellaxJS Library, js, HTML and CSS. Parallax scrolling is a web site trend where the background content (i.e. an image) is moved at a different speed than the foreground content while scrolling. 

Closes: #1393 

### Describe the changes you've made
I have made the respective HTML, CSS and js files with images added in it. I have used RellaxJS Library for Basic Markup , Optional Speed , Use the data-rellax-speed attribute to set the speed of a .rellax element to something other than the default value (which is -2), Use responsive speed attributes for breakpoint levels that require a different speed, also to to sort the elements properly in the Z space

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot from 2021-05-13 13-11-30

### CODE REVIEW

**Comment by subhangi2731** [comment]
@Vishal-raj-1 @ridsuteri please review my pr and merge it

**Comment by subhangi2731** [comment]
@ridsuteri please review my pr

**Comment by subhangi2731** [comment]
@urvashi-code1255 @harshgupta20 @ridsuteri @991rajat please review and merge my pr

**Comment by subhangi2731** [comment]
@Vishal-raj-1 please review and merge my pr

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@subhangi2731 the project is not working on my side , bcz you have not linked the css and js file properly :( and also please add this project to the script file as well

**Comment by subhangi2731** [comment]
okay @ridsuteri I will fix this and make a different pr

**Pull request closed without merging**
