### PR TITLE
#22 Days of week

### PR DESCRIPTION
**Pull request by Aayushi-Mittal**
## 22 Day of the Week 
Closes: #22 

### Describe the changes you've made
A webpage showing today's date, day, time. It has a video background too which changes with time.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
[View It Live](https://aayushi-mittal.github.io/Awesome-JavaScript-Projects//public/DaysOfWeek.html)

### During Day Time
Screenshot (248)

### During Afternoon
Screenshot (247)

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @Aayushi-Mittal Add a card for your project like the other projects in the index.html

**Review by Vishal-raj-1 — COMMENTED** [review]
@Aayushi-Mittal Website looks nice. But Please follow structure of this project. Make seperate css, javascript file. And also add project card in index.html

**Comment by Aayushi-Mittal** [comment]
Made the required changes.

**Comment by urvashi-code1255** [comment]
> Made the required changes.

@Aayushi-Mittal Please remove the merge conflicts.

**Comment by Aayushi-Mittal** [comment]
@urvashi-code1255, Resolved the conflict.

**Review by Vishal-raj-1 — COMMENTED** [review]
@Aayushi-Mittal now we are using `Awesome-JavaScript-Projects/script.js` for adding project detail. So you can remove project card from index.html and add details of the project in mentioned file.

**Comment by urvashi-code1255** [comment]
@Aayushi-Mittal Any updates on this PR?

**Comment by Aayushi-Mittal** [comment]
> @Aayushi-Mittal Any updates on this PR?

Working on it.

**Comment by Aayushi-Mittal** [comment]
Made the required changes. Please check @urvashi-code1255 if it is fine or not.

**Review by urvashi-code1255 — COMMENTED** [review]
@Aayushi-Mittal Please see your changes locally. They are distorting the website.

**Comment by Aayushi-Mittal** [comment]
I hope now everything is fine now. Please review it.

**Review by urvashi-code1255 — APPROVED** [review]
Yes, everything is good now @Aayushi-Mittal 

Thanks for incorporating the suggested changes :)

**Comment by Aayushi-Mittal** [comment]
Thank you for your help. 😊

**Pull request merged**
