### PR TITLE
New project addition : Avatar Maker

### PR DESCRIPTION
**Pull request by jhamadhav**
## Describe the changes you've made
I have Made a project called Avatar Maker, to generate a simple and slick profile pic using the user's name.

## Describe if there is any unusual behavior of your code(Write NA if there isn't)
NA

## Checklist:

My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots
Put any screenshot(s) of the project here :
avatarMaker-demo

### CODE REVIEW

**Comment by jhamadhav** [comment]
@Vishal-raj-1 and @urvashi-code1255  , please check the PR for merge. Thank you

**Review by Vishal-raj-1 — COMMENTED** [review]
Thanks for the contributions @jhamadhav . Please squash the commits into one commit.

**Comment by jhamadhav** [comment]
> 
> 
> Thanks for the contributions @jhamadhav . Please squash the commits into one commit.

So should I close this pull request and then make another one with all commits squashed into one?

**Comment by Vishal-raj-1** [comment]
No squash commits in this PR only.

**Comment by jhamadhav** [comment]
How to do that, could you please explain?
I tried searching online but they all show squashing through git terminal .

**Comment by jhamadhav** [comment]
I have squashed the previous 11 [commits ](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/664/commits/bab25439edcf46ab87372157617aa9a814d9e0f1) please check again.

**Comment by jhamadhav** [comment]
@Vishal-raj-1 please add GSSOC'21 and level2 tag to the PR as well!

**Comment by jhamadhav** [comment]
@991rajat Please add GSSOC'21 and Level tag

**Pull request merged**
