### PR TITLE
Added Files for FlappyBird Game

### PR DESCRIPTION
**Pull request by deeptea22**
## Related Issue
  FlappyBird Game

Closes: #404 

### Describe the changes you've made
I have added the HTML, CSS, JS and Image Files of the Flappy Bird Game

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by deeptea22** [comment]
Hey @991rajat @ridsuteri @urvashi-code1255 @Vishal-raj-1 Please take a look.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@deeptea22 project looks nice ,just resolve the  merge conflicts :)

**Comment by deeptea22** [comment]
@ridsuteri Hey i have solved the merge conflicts :)

**Review by ridsuteri — APPROVED** [review]
good work @deeptea22 ,thanks for contributing :)

**Pull request merged**
