### PR TITLE
Modified looks of the projects website

### PR DESCRIPTION
**Pull request by chaitanyashimpi**
## Related Issue
  - @urvashi-code1255 @Vishal-raj-1  Changed the whole design of the website. The contribution things are the same, no need to change the process.

Closes: #215 

### Describe the changes you've made
I have changed the overall look of the website.

###Suggestion
<h5>Do not add the gif files to showcase the projects, because it's causing a huge load to the website. The Image is good for the website to get load fast.<h5>

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots

image

image

image

### CODE REVIEW

**Comment by chaitanyashimpi** [comment]
@urvashi-code1255 @Vishal-raj-1 I have made quite good changes to the site. I hope you will merge it as soon as possible before the contributors find it hard to think on. 

Review it fast so that I can work on different projects for Awesome JavaScript Project

**Comment by Vishal-raj-1** [comment]
@chaitanyashimpi You have to squash your commit into single commit. Then I would merge this PR into codebase.

**Comment by chaitanyashimpi** [comment]
@Vishal-raj-1 Can you please guide me on how to do it.

**Comment by Vishal-raj-1** [comment]
Checkout [this](https://youtu.be/V5KrD7CmO4o)

**Comment by chaitanyashimpi** [comment]
I squashdd them, but while pushing, it is saying that everything is up to date

**Comment by chaitanyashimpi** [comment]
@Vishal-raj-1 I squashed the commits, but while pushing its saying, that everything is up to date.

**Comment by chaitanyashimpi** [comment]
@Vishal-raj-1 I have finally squashed it. You can go further to merge it.

**Review by ridsuteri — APPROVED** [review]
this looks preety good @chaitanyashimpi 😻,thanks for contributing :)

**Review by 991rajat — APPROVED** [review]

**Pull request merged**
