### PR TITLE
Guessing Game.html

### PR DESCRIPTION
**Pull request by kmryashasvi**
Closes: #224

### Describe the changes you've made
added new file

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image
image
image
image

### CODE REVIEW

**Comment by kmryashasvi** [comment]
I have added html file of my game in the "Public" directory but I am having problem in listing it in the "index.html" file,
Please guide me.

**Comment by kmryashasvi** [comment]
> @kmryashasvi First of all welcome to this awesome Project !! @kmryashasvi You have to made three different files .html, .css, .js.
> 
> And add details of this project in script.js like others project. You don't have to change in index.html

I have done as you have told,
Please have a look
Please don't worry, you may think,  the files uploaded are not necessary, but believe me , they are

**Comment by kmryashasvi** [comment]
Please Guide me if there is an error or modification needed @Vishal-raj-1

**Review by urvashi-code1255 — COMMENTED** [review]
@kmryashasvi Replace the image with the GIF in script.js

Also remove all the unwanted images.

Squash your commits into one!!

**Pull request closed without merging**
