### PR TITLE
Tertris Game

### PR DESCRIPTION
**Pull request by Harshal0902**
## Related Issue
Build a Tetris Game

Closes: #221 

### Describe the changes you've made
Build a Tetris Game using HTML, CSS and Js.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
TetrisGame

### CODE REVIEW

**Comment by 991rajat** [comment]
@Harshal0902 Please add the project to script.js

**Comment by Vishal-raj-1** [comment]
@Harshal0902 ??

**Review by 991rajat — APPROVED** [review]
Good Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck:

**Pull request merged**
