### PR TITLE
UserListFilter project added

### PR DESCRIPTION
**Pull request by LazySukanta**
A javaScript based project User List Filter is added.
1. Fetched random user data from "https://randomuser.me/api/".
2. Process the data and create "li" items.
3. From any search items(Like :- name, city, or country) from the Input box rearrange the related results.
UserListFilter

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@LazySukanta remove the .vscode folder and pull the recent changes.

**Comment by LazySukanta** [comment]
I have removed .vscode file.

**Comment by urvashi-code1255** [comment]
@LazySukanta Resolve the merge conflicts!

**Review by urvashi-code1255 — APPROVED** [review]
Its looking good to me @LazySukanta :)

Thanks for contributing!!

**Pull request merged**
