### PR TITLE
fixed DrumKit issue#296

### PR DESCRIPTION
**Pull request by Ishikakhurana**
Closes: #296

### Changes :
  - Changed js file to response and produce sound on click.
  - Also Fixed wrong sound file for A and F keys.(were same before)

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@Ishikakhurana Please make cursor pointer on hover

**Comment by Ishikakhurana** [comment]
@urvashi-code1255 i've added the required. Please review the change and add tags. Thankyou.

**Comment by Ishikakhurana** [comment]
@urvashi-code1255 is the issue closed?

**Comment by 991rajat** [comment]
@Ishikakhurana Please resolve the conflict and Squash the commits
Let me know if you need any help.

**Comment by harshgupta20** [comment]
Hello @Ishikakhurana , Kindly respond within 2 days or we will resign this issue to others.

**Comment by Ishikakhurana** [comment]
hey @harshgupta20 i might need some help to resolve conflict. Who can i contact?

**Comment by 991rajat** [comment]
What problem you are facing let me know? DM on discord.

**Comment by urvashi-code1255** [comment]
@Ishikakhurana Any updates?

**Comment by harshgupta20** [comment]
This issue has been resolved.

**Pull request closed without merging**
