### PR TITLE
image gallery 

### LINKED ISSUE #386: Image-gallery Project in Javascript
This is beginner kind project  and i would love to add some more features from my side.

Features : -
1. User can add on more photos to the gallery 
2. Each photo will have a category and photos with same category will be queue in same row
3. On clicking at particular pic user can view that pic in bigger font

---With some animations----

### PR DESCRIPTION
**Pull request by Aarti002**
closes #386

### CODE REVIEW

**Review by 991rajat — CHANGES_REQUESTED** [review]
I edited the description. See it how to link issues.
- Add a proper name to html file, js file and css file so that It don't create conflict in future
Something like this ImageGallery.html. Change name of all files
- Make it responsive.
- Add the project to the script.js
> Let me know if you need any help

**Comment by Aarti002** [comment]
@991rajat , i think i can do much better than this one give me sometime i will show you much better one!
Thank you!

**Comment by Aarti002** [comment]
hey @991rajat i am facing small problem in this project how should i insert a close button when image font increases on clicking 
actually i have done it but its not working in the way i want, problem is once i click  the cross button it does not appear again with other images, i hope u understood my problem, can you help me out in this?
Thank you!

**Comment by 991rajat** [comment]
@Aarti002 RIghtnow cross is working fine.
For your problem you will need to create a event listener and listen which will fire and it it you can check the font size of particular element and do you logic according to that. But right now its okay if you are not able to do.
Just fix the filenames and add the project to script.js and some overflow.

**Comment by Aarti002** [comment]
Hey @991rajat i have made a new pull request for this project and that one is much better , please review that one , sorry for the inconvenience 
Thank you!

**Comment by Aarti002** [comment]
and also i have PR for quiz project which was assigned to me, can you please review it ,it's been already 10 days since i made pull request
Thank you!

**Comment by 991rajat** [comment]
Since you made a similar PR which you mentioned. I'm closing this now.

**Pull request closed without merging**
