### PR TITLE
Fixed spacing issue between Home and About sections

### PR DESCRIPTION
**Pull request by shakmg**
Reduced the large gap seen in the screenshot on issue 28 between the Home and About sections to a more reasonable amount of spacing between the sections - updated version below.

image

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @shakmg you have reduced the space a little bit much. Please reduce the space like that so that Home section will take a whole page and about section also take whole page space. Also, there should be a little space at the top of the Home section(between navbar and Home section).

**Comment by shakmg** [comment]
@urvashi-code1255 Thanks for the comments, I've added a bit of spacing below the Nav section and increased some of the spacing between the home and about sections. It's hard to judge how much spacing to give as in the original issue there was too much, hopefully this is closer.

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 Thanks for the comments, I've added a bit of spacing below the Nav section and increased some of the spacing between the home and about sections. It's hard to judge how much spacing to give as in the original issue there was too much, hopefully this is closer.

Hey @shakmg Please add a UI image  here so that I can see the changes it will be easy to review for me

**Comment by shakmg** [comment]
Here you go @urvashi-code1255 

Screenshot 2021-02-11 at 01 56 46

Screenshot 2021-02-11 at 01 56 39

**Comment by urvashi-code1255** [comment]
> Here you go @urvashi-code1255 

LGTM @shakmg

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @shakmg

**Comment by shakmg** [comment]
@urvashi-code1255 Should I be able to see that I contributed to this repo from my forked repo? I don't see any links, do you know what happened? Thanks for any information.

**Pull request merged**
