### PR TITLE
Add birthday reminder project -#411

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - Add birthday reminder project

Closes: #411 

### Describe the changes you've made
Added javascript based birthday reminder project which shows people if there birthdate matches current date and shows there age dynamically from there birthdates.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
birthday-reminder-final

### CODE REVIEW

**Comment by Vedant-Rahane** [comment]
@991rajat Can you please review and merge this.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Vedant-Rahane kindly resolve the conflicts

**Comment by Vedant-Rahane** [comment]
> @Vedant-Rahane kindly resolve the conflicts

@ridsuteri  solved 👍

**Review by ridsuteri — APPROVED** [review]
good work @Vedant-Rahane ,thanks for contributing :)

**Pull request merged**
