### PR TITLE
Digital clock responsiveness #418

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - Make Digital clock project responsive.

Closes: #418 

### Describe the changes you've made
Made Digital clock project responsive.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

digitalClock-res

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@Vedant-Rahane Please resolve the merge conflicts

**Comment by Vedant-Rahane** [comment]
> @Vedant-Rahane Please resolve the merge conflicts

@urvashi-code1255 Done

**Review by urvashi-code1255 — APPROVED** [review]
@Vedant-Rahane Good work :)

**Comment by Vedant-Rahane** [comment]
@urvashi-code1255 Thank you.
Can you check issue #300 
My last comment about changing UI of this project.

**Pull request merged**
