### PR TITLE
Added a new feature to change the theme

### PR DESCRIPTION
**Pull request by anjali-tejasvi**
## Feature: Drumkit  - added a new feature to change the theme 

closes: #377

### 
I have added a new button that will change the theme of this drumKit web app.

### Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.

### A brief description of what I changed
I have made some changes in the HTML, CSS, and js file of the drumKit web app. And it will change the theme of this by clicking the change theme button which I have added.

### Screenshots

Screenshot from 2021-03-13 22-02-23
Screenshot from 2021-03-13 22-02-17

### CODE REVIEW

**Comment by anjali-tejasvi** [comment]
@urvashi-code1255  pls have a look.

**Review by urvashi-code1255 — COMMENTED** [review]
@anjali-tejasvi Please pull the recent changes

**Comment by anjali-tejasvi** [comment]
urvashi-code1255  I've already pulled the request. Now what I have to do?

**Comment by anjali-tejasvi** [comment]
@urvashi-code1255  I have already pulled the request. Now what I have to do?

**Comment by anjali-tejasvi** [comment]
@urvashi-code1255 I'm a newbie. Please suggest to me what else I can do? Any other changes you want?

**Review by 991rajat — APPROVED** [review]
Great work @anjali-tejasvi !!
Congratulations on first contribution 🎉

**Comment by anjali-tejasvi** [comment]
@991rajat  Thank u soo much:)

**Pull request merged**
