### PR TITLE
Update particle_style.css

### PR DESCRIPTION
**Pull request by NOiR-07**
## Related Issue
  - 

Closes: #456 

### Describe the changes you've made
 I changed the background theme of the particle js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@NOiR-07 Update the GIF of the project

**Comment by NOiR-07** [comment]
You want me to replace the old particle gif file with an updated one?

**Comment by 991rajat** [comment]
@NOiR-07 Yes replace old gif with new black one

**Comment by NOiR-07** [comment]
please check it , i made the changes

**Comment by harshgupta20** [comment]
Hello @NOiR-07 , please don't commit on master branch, Kindly create a separate branch and then commit it.

**Review by 991rajat — APPROVED** [review]
Good Work

**Comment by 991rajat** [comment]
Congratulations of merging on your first PR. :tada: 
Keep Contributing.

**Pull request merged**
