### PR TITLE
Favicon added

### PR DESCRIPTION
**Pull request by aniketsingh98571**
## Related Issue
 #200 

Closes: #200 

### Describe the changes you've made
Added favicon to `index.html`

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
@urvashi-code1255 Please look into it for #200

**Comment by urvashi-code1255** [comment]
@aniketsingh98571 write "Closes: #issue_number" in the PR template

**Comment by aniketsingh98571** [comment]
@urvashi-code1255 Done with the changes in PR template

**Review by urvashi-code1255 — COMMENTED** [review]
@aniketsingh98571 path will be ../assets/Images/favicons/10.png

**Comment by aniketsingh98571** [comment]
@urvashi-code1255 Path has been changed please look into it.

**Review by urvashi-code1255 — APPROVED** [review]

**Comment by aniketsingh98571** [comment]
@urvashi-code1255 Can you add GSSoC 21 label to it because I have contributed as a part of GSSoC., so it will help mentors to assign points.

**Pull request merged**
