### PR TITLE
Changes made "CHESS GAME"

### PR DESCRIPTION
**Pull request by kanisshka**
Closes: #1233 

### Describe the changes you've made
Done some changes to Chess Game.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
  
Chess Game 

image

Logo also added
 
image

### CODE REVIEW

**Comment by 991rajat** [comment]
Looks Good Just Replace the old image with the new one
image

**Comment by 991rajat** [comment]
@kanisshka Replace the old gif with new one of yours.

**Comment by kanisshka** [comment]
sure sir

> @kanisshka Replace the old gif with new one of yours.
> Jus Replace the image in main project section,It's of old project.

sure sir

**Comment by kanisshka** [comment]
@991rajat 
It's showing that my access is denied 
so, I'll make a new PR for that and link that with the issue
thank you

**Pull request merged**
