### PR TITLE
Added Laptop Portfolio Project

### PR DESCRIPTION
**Pull request by K-jais**
It solves issue #1467 

Its working video,

https://user-images.githubusercontent.com/75881393/118400105-dc697c80-b67d-11eb-9144-98a56e612c79.mp4

### CODE REVIEW

**Comment by K-jais** [comment]
Please @ridsuteri @991rajat @urvashi-code1255 review this PR.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@K-jais you have mistakenly linked restaurant menu project with laptop portfolio card in the project section , please fix it :)

**Comment by K-jais** [comment]
Sir @ridsuteri @991rajat @urvashi-code1255 I have done the respective changes. Please review the PR now.

**Review by ridsuteri — APPROVED** [review]
good work @K-jais :)

**Pull request merged**
