### PR TITLE
Lyrics Search App

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue
  - Info about Issue or bug

Closes: #1593

### Describe the changes you've made
Added Lyrics Search App

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Amit366** [comment]
@991rajat @ridsuteri please review

**Review by ridsuteri — CHANGES_REQUESTED** [review]
sorry @Amit366 a similar project already exists :(

**Comment by Amit366** [comment]
@ridsuteri then I why was I assigned this project??

**Comment by Amit366** [comment]
In that time I could have done some other project

**Comment by ridsuteri** [comment]
> @ridsuteri then why was I assigned this project??

ohk let me ask harsh about it

**Comment by Vishal-raj-1** [comment]
@Amit366 Resolve merge conflicts, I will merge it asap !!

**Comment by Amit366** [comment]
@Vishal-raj-1 done

**Pull request merged**
