### PR TITLE
Palindrome checker updated

### PR DESCRIPTION
**Pull request by Aarti002**
issue #385 updated
PLease @harshgupta20 review it once and let me know if something more is required
Thank you!

### CODE REVIEW

**Comment by 991rajat** [comment]
@Aarti002  Resolve the conflict.
Why Guess the song project is added again. Remove it please

**Comment by Aarti002** [comment]
@991rajat please can u review again ?
Thank you!

**Comment by 991rajat** [comment]
@Aarti002 Look at this. Is this happening on your side. Fix this Please
image

**Comment by Aarti002** [comment]
@991rajat no....., it's working perfectly fine in my system , see....
image

**Comment by Aarti002** [comment]
@991rajat is this still not working ?

**Comment by 991rajat** [comment]
No it's not fixed. Look into it have you pushed all the changes? Compare in File Changed Section

**Comment by Aarti002** [comment]
@991rajat i don't know what's happing, i have pushed all changes, can you help?

**Comment by 991rajat** [comment]
Hey @Aarti002 If you are in discord, DM me, 
I believe there is CSS issue, I checked out this project with other mentor too, there also CSS is breaking.

**Comment by Aarti002** [comment]
sounds good!

**Comment by Aarti002** [comment]
@991rajat i dm u on discord, please reply.

**Comment by 991rajat** [comment]
@Aarti002 The CSS that u sent on discord is working fine, replace it.

**Comment by Aarti002** [comment]
that was same css which i have committed before but i don't know why its
not working

**Comment by 991rajat** [comment]
Update the HTML file as well, which you shared in discord. 
It's working

**Comment by Aarti002** [comment]
hey @991rajat i have made new PR please review that one , there were some issue in this PR
Thank you!

**Comment by Aarti002** [comment]
issue number is #1525

**Comment by 991rajat** [comment]
Its Resolved with new PR. I'm closing this one

**Pull request closed without merging**
