### PR TITLE
Added newyear wish with crackers

### PR DESCRIPTION
**Pull request by kumarankm**
## Related Issue
  - New year crackers Firework with JS

Closes: #415

### Describe the changes you've made
I have added a new year wish with a bursting crackers effect with sound in the background.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
new

### CODE REVIEW

**Comment by kumarankm** [comment]
I have finished the assigned one, Kindly review it @991rajat  @urvashi-code1255

**Review by 991rajat — APPROVED** [review]
Great Work :fire:

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing

**Comment by kumarankm** [comment]
> Great Work 🔥

Thanks :)

**Pull request merged**
