### PR TITLE
Etch-Sketch

### PR DESCRIPTION
**Pull request by prachibansal2000**
## Related Issue
  - Made Etch-a-Sketch using js

Closes: #504 

### Describe the changes you've made
Made Etch-A-Sketch using js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@prachibansal2000 Resolve conflicts Please

**Comment by prachibansal2000** [comment]
I have resolved the conflicts @Vishal-raj-1 

> @prachibansal2000 Resolve conflicts Please

**Comment by 991rajat** [comment]
Hey @prachibansal2000 Project is not working, Is it working on your side?

**Comment by prachibansal2000** [comment]
> Hey @prachibansal2000 Project is not working, Is it working on your side?

ohh sorry forgot to mention that we can draw using the arrow keys

**Review by 991rajat — APPROVED** [review]
Looks Good.

**Comment by 991rajat** [comment]
Thank you for this awesome contribution. Keep Contributing.

**Pull request merged**
