### PR TITLE
 #127-Issue | Open every card on new tab

### PR DESCRIPTION
**Pull request by asimaries**
## Related Issue
  -Cards were not opening in the new tab
Closes: #127 

### Describe the changes you've made
I have added a target="_blank" in the script.js file Now all cards can be open in a new tab with a left click too.
change also 

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
Also I the Github repo link is also be updated as It will also open in a new tab for better use
*PLEASE MERGE IT AND HELP ME TO MAKE MY FIRST CONTRIBUTION TO OPEN-SOURCE*
https://asimaries.github.io/Awesome-JavaScript-Projects.github.io/

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@asimaries Please enable github pages for your fork and share the link here. It will be easy for me to review it.

**Comment by asimaries** [comment]
> @asimaries Please enable github pages for your fork and share the link here. It will be easy for me to review it.

https://asimaries.github.io/Awesome-JavaScript-Projects.github.io/

**Comment by asimaries** [comment]
the commits of #192 (I don't know-how SORRY )have also been added here if you merge this the #192 will also get fixed BUT everything is working fine

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by Vishal-raj-1** [comment]
@asimaries Squash your commits into one commit.

**Pull request merged**
