### PR TITLE
Adding project PlayBeats.

### PR DESCRIPTION
**Pull request by icoderharshit**
Resolving issue #403  @Vishal-raj-1 Do see to it.

## Related Issue
  - Info about Issue or bug
Adding new project i.e a soundplayer which uses SoundCloud API, built in Vanilla JS.
Closes: #[issue number that will be closed through this PR]
#403 
### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Addition of new project i.e it's files to the respective paths and update in projectData object in script.js 
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
Not unusual behaviour, but found 3 commits already done in main branch after forking and cloning the repo on my desktop. So, I didn't push them, and just did my commits and pushed to the new branch for my issue #403 . 
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
playbeats

### CODE REVIEW

**Comment by icoderharshit** [comment]
@Vishal-raj-1 Please see to this PR, and merge it !

**Comment by icoderharshit** [comment]
I mistakenly clicked on "Close with comment", kindly ignore that closed pr thing. Please @991rajat @Vishal-raj-1 see to this, and help me getting it merged into the main branch.

**Comment by icoderharshit** [comment]
@991rajat @Vishal-raj-1 , please merge this in the main branch. I am already running low on GSSoC'21 leaderboard.

**Review by 991rajat — APPROVED** [review]
Fabulous work :fire:

**Comment by 991rajat** [comment]
Congratulations on merging of your first PR. :tada: 
Keep Contributing.

**Pull request merged**
