### PR TITLE
feat: app to plot scatter plot of input data

### PR DESCRIPTION
**Pull request by Diksha02**
## Related Issue
  - An app to plot a scatter plot of input data

Closes: #1866 

### Describe the changes you've made
I have created an application using vanilla JS, html5 and css to plot a scattered plot of the input data using the library Chart.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
(1/2)
image

(2/2)
image

### CODE REVIEW

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Excellent Work! However, you have not updated script.js file. Please update script.js file.

**Comment by Diksha02** [comment]
> Excellent Work! However, you have not updated script.js file. Please update script.js file.

okay, I just have to add, project name, image and URL right?

**Comment by Rizwan-S** [comment]
yup

**Comment by Diksha02** [comment]
Hey actually I accidentally merged main of this repo to my fork's branch and I'm having some issue is it okay if I start this Pull request over again. Is there any way you can delete this PR so that I can start over again on some new branch.

**Comment by Diksha02** [comment]
i am not able to change the branch because of some conflicts

**Comment by Rizwan-S** [comment]
Hello @Diksha02! Luckily, git provides methods to undo changes too. Refer to this video to undo the changes: https://youtu.be/hA3vYDyaZQQ . For getting the commit I'd, use git log --oneline .

**Comment by Rizwan-S** [comment]
> i am not able to change the branch because of some conflicts

Can you please share the error message that you are getting.

**Comment by Diksha02** [comment]
> > i am not able to change the branch because of some conflicts
> 
> Can you please share the error message that you are getting.

image

**Comment by Diksha02** [comment]
Actually I did that on Github fork and that isn't yet on my local fork clone yet

**Comment by Diksha02** [comment]
Can I close this PR and make a new one with a new branch instead?

**Comment by Rizwan-S** [comment]
> Can I close this PR and make a new one with a new branch instead?

Yeah Sure!

**Pull request closed without merging**
