### PR TITLE
Add a awesome project(ACE_EYE)

### PR DESCRIPTION
**Pull request by Ace-07**
## Related Issue
  - #1155 

Closes: #1155

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (371)

### CODE REVIEW

**Comment by 991rajat** [comment]
@Ace-07  Add the project to scipt.js

**Comment by 991rajat** [comment]
@Ace-07 Is it working on your side?

**Comment by Ace-07** [comment]
now working fine😁

**Comment by 991rajat** [comment]
Looks Good. Great Work

**Comment by 991rajat** [comment]
@Ace-07 Remove the chess game
You have added it again. It'll become duplicate

**Comment by Ace-07** [comment]
Now solved.

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
