### PR TITLE
Issue 555

### PR DESCRIPTION
**Pull request by tushartiwari7**
## uppercase Letters bug

Closes: #555 

### Describe the changes you've made
converts uppercase letters to lowercase for a more unified approach.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by tushartiwari7** [comment]
please add labels for gssoc and level2 for it

**Comment by tushartiwari7** [comment]
please add labels for gssoc'21 and level2 for ithis PR ;)

**Comment by ridsuteri** [comment]
@tushartiwari7 i guess level 1 would be good enough for this PR since you have done minor changes ,level 2 is given when you add a new project :)

**Comment by tushartiwari7** [comment]
okay thank you so much ☺️

**Pull request merged**
