### PR TITLE
Project addition: Bridge N Torch

### PR DESCRIPTION
**Pull request by jhamadhav**
# Bridge N Torch

The bridge and torch problem (also known as The Midnight Train and Dangerous crossing) is a logic puzzle that deals with four people, a bridge, and a torch. It is in the category of river crossing puzzles, where a number of objects must move across a river, with some constraints.
[source - wikipedia](https://en.wikipedia.org/wiki/Bridge_and_torch_problem)

Closes: #1504 

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)

NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Output

bridgeNtorch

### CODE REVIEW

**Comment by jhamadhav** [comment]
@Vishal-raj-1 @991rajat @urvashi-code1255 Please review the PR and add gssoc'21 and level tags.

**Comment by 991rajat** [comment]
Looks Good, Resolve the conflict.

**Comment by jhamadhav** [comment]
@991rajat Done 👍

**Review by 991rajat — APPROVED** [review]
Great

**Pull request merged**
