### PR TITLE
Pomodoro timer added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
Pomodoro timer added
Closes: #502 

### Describe the changes you've made
Pomodoro timer added

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/115281262-6fd68d00-a166-11eb-886d-da7c1434d66f.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@Vishal-raj-1 @harshgupta20 @urvashi-code1255  Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 @harshgupta20 @urvashi-code1255 Please review my PR .

**Review by urvashi-code1255 — APPROVED** [review]
@Ankita297 I am impressed with yor work. Keep it up dear 😊

**Comment by urvashi-code1255** [comment]
But you have linked a PR in this PR template. Please link respective issue

**Comment by Ankita297** [comment]
@urvashi-code1255  now is it okay ?

**Comment by Ankita297** [comment]
Thank You @urvashi-code1255 .

**Comment by 991rajat** [comment]
Great Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing.

**Pull request merged**
