### PR TITLE
#176 - Showing Boostrap Alert when note is empty

### PR DESCRIPTION
**Pull request by mtwn105**
## Related Issue
  - Issue #176 - Showing Boostrap Alert when the note is empty

Closes: #176 

### Describe the changes you've made
Added an alert div in the HTML and added logic to show and dismiss the alert in javascript when the note is empty.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
@mtwn105 I mean we don't need to show alert all the time. We have to show alert iff user click add note and title is missing.

**Comment by mtwn105** [comment]
Hi @Vishal-raj-1

Yes it will only appear when user clicks add note and title is missing. And if there's alert shown and then user types something it will dismiss. You can let me know if any changes required.

**Comment by Vishal-raj-1** [comment]
@mtwn105 Great !! You can enable github page for your forked repo, and it here everytime you raise a PR . It will easy for me to review

**Comment by mtwn105** [comment]
Sure.. @Vishal-raj-1 You can see changes here https://mtwn105.github.io/Awesome-JavaScript-Projects/

**Review by urvashi-code1255 — APPROVED** [review]
@mtwn105 It LGTM

**Comment by Vishal-raj-1** [comment]
It doesn't show bootstrap alert box.

qu

**Comment by mtwn105** [comment]
Hi @Vishal-raj-1 seems like my changes were overridden and removed after you backmerged main into forked branch.

**Review by mtwn105 — COMMENTED** [review]
Here the code to show error div instead of alert has been removed. :(

**Comment by mtwn105** [comment]
You can check now and merge this one @Vishal-raj-1 @urvashi-code1255

**Comment by Vishal-raj-1** [comment]
@mtwn105 Could you please send one videoclip ? I am not able to add note.

**Review by urvashi-code1255 — COMMENTED** [review]
@mtwn105 I am not able to add a note after your recent changes.

**Comment by Vishal-raj-1** [comment]
Thanks for your contribution @mtwn105

**Pull request merged**
