### PR TITLE
Added slider-js project (#1054)

### PR DESCRIPTION
**Pull request by anushree71199**
## Related Issue
  - [GSSOC'21] Added a new project of a slider in JavaScript for animation of navbars

Closes: #1054

### Describe the changes you've made
I've made a JavaScript project slider animation using APIs. This API will let the user to click on a button and see four different animations from right,left,top,bottom directions. It will help for nav bar animations which many beginners find difficult to code at the first time. I have used plain JavaScript for this project and the API is made by me as the name of Pushbar where the function of animation is taking place through open() and close() functions. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
slider-js

### CODE REVIEW

**Comment by anushree71199** [comment]
@991rajat and @harshgupta20 please review my PR under GSSOC'21 participation. Let me know about the necessary changes to be made if there are any. And if there isn't any then please merge this PR to your project. Thanks.

**Review by 991rajat — APPROVED** [review]
Looks Good. Great Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by anushree71199** [comment]
thank you so much, will make another issue soon :)

**Pull request merged**
