### PR TITLE
Added Live Code Editor In Awesome Javascript Project

### PR DESCRIPTION
**Pull request by LalitMishra1504**
Added Live Code Editor 
Feature Added #358

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@LalitMishra1504 Resolve the merge conflicts

**Comment by LalitMishra1504** [comment]
@urvashi-code1255 Please Check

**Comment by LalitMishra1504** [comment]
@Vishal-raj-1 @guruc-134 please Review my pr

**Comment by 991rajat** [comment]
@LalitMishra1504 Good Work
Squash the commits.
Let me know if you need any help.

**Comment by LalitMishra1504** [comment]
I resolved the conflict can you please review it @991rajat

**Pull request merged**
