### PR TITLE
Added scroll to top button in main webpage itself issues #37

### PR DESCRIPTION
**Pull request by Nagsenwaghmare**

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @Nagsenwaghmare Please follow the PR template given in the project and also the changes I have told you to do in the issue thread

**Comment by urvashi-code1255** [comment]
Hey @Nagsenwaghmare Add a demo video here and also resolve the merge conflicts...

**Comment by Nagsenwaghmare** [comment]
> Hey @Nagsenwaghmare Add a demo video here and also resolve the merge conflicts...


https://user-images.githubusercontent.com/64947831/107867674-d1e2ef80-6ea2-11eb-9db5-60f6a1a97aab.mp4

**Comment by Nagsenwaghmare** [comment]
@urvashi-code1255  should I push the code and raise pull request?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 should I push the code and raise pull request?

No, it's good to go now

**Review by urvashi-code1255 — APPROVED** [review]
LGTM 👍🏻

**Comment by urvashi-code1255** [comment]
Hey @Nagsenwaghmare After merging your PR. Website had so many bugs!! So i have removed that commit!! 

Send a new PR with a different branch!!

Make sure to pull all the changes from main!!

**Comment by Nagsenwaghmare** [comment]
ok urvashi I will do it shortly

**Pull request merged**
