### PR TITLE
UI of Weight Converter

### PR DESCRIPTION
**Pull request by AnshikaAgrawal5501**
## Related Issue
Ui of weight converter was simple and not responsive.

Closes: #1103

### Describe the changes you've made
- Files were not linked properly, fixed that.
- Earlier the converter was only converting measurements from kg to others and not vice versa. I have made the changes in the js file and so now it is converting in all the measurements.
- Added background
- Added bootstrap to the input fields and buttons
- Changed the heading style
- Made the project responsive for all types of devices

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Before
Untitled4

After
WeightConverter

### CODE REVIEW

**Comment by AnshikaAgrawal5501** [comment]
Hey @Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri 
Please review the PR.
Thanks.

**Review by 991rajat — APPROVED** [review]
Nice Work. Looks Good.

**Comment by 991rajat** [comment]
Thank you for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by AnshikaAgrawal5501** [comment]
Hey @991rajat, Thanks for the encouragement. :smile:

**Pull request merged**
