### PR TITLE
Auto close tooltip added

### PR DESCRIPTION
**Pull request by ishani02**
## Related Issue
  The tooltip in the password generator had to be closed manually by clicking on the close button on top right corner.

Closes: #574 

### Describe the changes you've made
The tooltip in the password generator now closes automatically after 3 seconds.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by ishani02** [comment]
@urvashi-code1255 @991rajat I have made the necessary changes. Kindly review it.

**Review by 991rajat — APPROVED** [review]
Good Work

**Comment by 991rajat** [comment]
Congratulations of merging of your first PR. :tada: 
Keep Contributing.

**Comment by ishani02** [comment]
Thank you so much @991rajat 😊

**Comment by ishani02** [comment]
@991rajat can you please add the labels as it will help in updating my score in GSSoC'21?

**Pull request merged**
