### PR TITLE
Modified Flappy bird game.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
## Related Issue
  - To modify flappy bird.

Closes: #1288 

### Describe the changes you've made
Modified flappy bird game.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
flappy-bird

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@ridsuteri @991rajat Please review.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Shivangi-ch the project doesn't work well on my side :(
it looks like this !
Screenshot (78)
kindly check once again and fix the issue :)

**Comment by Shivangi-ch** [comment]
@ridsuteri @991rajat I have fixed the issue now.

**Review by ridsuteri — APPROVED** [review]
good work @Shivangi-ch :)

**Pull request merged**
