### PR TITLE
updated yoga app #978

### PR DESCRIPTION
**Pull request by anshika208**
## Related Issue
  - updated the yoga app

Closes: #978

### Describe the changes you've made
i have added more timing options to choose for meditation as well as added more music modes and vidoes in the background and changed the overall look of the yoga app

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

ezgif com-gif-maker

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by anshika208** [comment]
it has different music too for different modes , as the video was becoming more in size that is why sound effects could not be shown in the video

**Comment by 991rajat** [comment]
@anshika208 Looks Good, Size of the video is huge, Is there a way to reduce the size or change to different video something lite.
Like under 2-4 MB video 480P resolution will also look good, 
Reduce the size of the gif, use static image

And there are conflicts tags in script. Look into it, If not able to resolve let me know but Reduce the size of files is important.

**Comment by anshika208** [comment]
ohkay!! sure @991rajat i will make the changes in the video . But pls do add the labels.

**Comment by 991rajat** [comment]
@anshika208 Looks good just remove the memurl which you uncommented, it not works so remove it.

**Comment by anshika208** [comment]
done!! @991rajat .

**Review by 991rajat — APPROVED** [review]
Great. Looks Good

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :tada: 
Keep Contributing.

**Comment by anshika208** [comment]
Happy to contribute . Thanku!!

**Pull request merged**
