### PR TITLE
Modify Todo App project #1001

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - Modify Todo App project #1001

Closes: #1001 

### Describe the changes you've made
- Completely changed project with new one.
- Make todo list stored in local storage.
- Make project responsive.
- Add pending task feature.
- Add clear all feature.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

todo-app

### CODE REVIEW

**Comment by Vedant-Rahane** [comment]
@urvashi-code1255 Please review this.

**Comment by Vedant-Rahane** [comment]
Can you please increase level to 2. It took too much time to modify, add local storage and other feature. We can now also remove old local storage project which is having many bugs. Also will fix many issues such as #942 and #761

**Review by 991rajat — APPROVED** [review]
Great work. 🔥 
Looks great.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing.

**Comment by 991rajat** [comment]
Hey @Vedant-Rahane how do you make gif? It is small in size. 
Any software or compression ?
Do tell need to recommend others to do the same.

**Comment by Vedant-Rahane** [comment]
@991rajat 
I use [Free Cam](https://www.freescreenrecording.com/) for video recording. And to convert it into gif I use an online tool [EZGIF](https://ezgif.com/video-to-gif).
We can select the area we want to capture in the video recording app. Also after converting into gif there is an option of cropping in the online tool.

**Pull request merged**
