### PR TITLE
 assets/js/pingpong added

### PR DESCRIPTION
**Pull request by Riya764**
#328 
  - Ping pong Game

 "closes: #328 "

Describe the changes you've made
I have added the html file, css file and script file for the Ping Pong  game.

Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
 Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
 
- [x] I have commented my code, particularly in hard-to-understand areas.
-  [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (435)

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@Riya764 Please add your project details in script.js like the other projects

**Comment by Riya764** [comment]
@urvashi-code1255 done!

**Comment by Riya764** [comment]
@urvashi-code1255 I am facing problem in resolving conflict. Please help me

**Review by 991rajat — CHANGES_REQUESTED** [review]
- Good Work
- Please resolve the conflict
- Squash the commits, Add a descriptive commit message.

> Let me know if you need help.

**Pull request merged**
