### PR TITLE
Made Responsive Image Slide 

### PR DESCRIPTION
**Pull request by agamjotsingh18**
## Related Issue
  - pictures were not responsive

Closes: #854 

### Describe the changes you've made
changed the height, width display and organised in a better manner

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot (36)
Screenshot (37)

### CODE REVIEW

**Comment by ridsuteri** [comment]
@agamjotsingh18 any updates?

**Comment by agamjotsingh18** [comment]
> @agamjotsingh18 any updates?

Yes sir, I updated it

**Comment by ridsuteri** [comment]
@agamjotsingh18 i am unable to see any updation in this PR? 
or you opened a fresh PR?

**Comment by urvashi-code1255** [comment]
@agamjotsingh18 Any updates?

**Pull request closed without merging**
