### PR TITLE
Add Dice Game

### PR DESCRIPTION
**Pull request by iamrishavraj1**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by iamrishavraj1** [comment]
Good Evening Sir, My previous pull request have some issue so sent a another pull request . Please Check the issue

**Comment by iamrishavraj1** [comment]
Please Review My Code

**Review by Vishal-raj-1 — APPROVED** [review]
Sorry for the delay !! Good Work

**Comment by Vishal-raj-1** [comment]
@iamrishavraj1 Please resolve conflicts !!

**Comment by iamrishavraj1** [comment]
Done Sir.

**Comment by iamrishavraj1** [comment]
> @iamrishavraj1 Please resolve conflicts !!

Done sir @Vishal-raj-1

**Comment by urvashi-code1255** [comment]
@iamrishavraj1 please resolve them again

**Comment by iamrishavraj1** [comment]
> @iamrishavraj1 please resolve them again

done mam

**Comment by iamrishavraj1** [comment]
@Vishal-raj-1 @urvashi-code1255 @harshgupta20  Please review my work

**Pull request merged**
