### PR TITLE
Real-Time-Chat-Application (1417)

### PR DESCRIPTION
**Pull request by Jyoti6828**
# Real Time Chat Application using PHP with MySQL & Ajax
	- Creating a Real-Time Chat Application with PHP with MySQL & Ajax.
	- It will keep track on the users and save chat history with respective person.
	- And it also keep track on the conversations, so its also safe.
	- It has LOGIN/LOGOUT feature, so security and privacy is also maintain. 

## TECHNOLOGY USED: 

1. PHP
2. MYSQL
3. JQUERY
4. BOOTSTRAP 
5. HTML
6. CSS

### CODE REVIEW

**Comment by Rizwan-S** [comment]
Hello @Jyoti6828 ! I really appreciate the amount of work that you put in the code. However, this repo strictly contains projects made using HTML, CSS and vanilla javascript. I'm really sorry but we cannot merge your pr. Hope you understand.

**Comment by Jyoti6828** [comment]
Okay.. So can I build this application using HTML, CSS, vanilla JavaScript.

**Comment by Rizwan-S** [comment]
Sure! Please go ahead.

**Comment by Jyoti6828** [comment]
@Rizwan-S  Sure!.. Thank You So Much!! 
I will do it ...

**Comment by Rizwan-S** [comment]
@Jyoti6828 what's the update?

**Comment by Jyoti6828** [comment]
@Rizwan-S I'm working on it. I will push the code as soon as possible.

**Pull request closed without merging**
