### PR TITLE
creating GuessingGame.html

### PR DESCRIPTION
**Pull request by kmryashasvi**
Closes: #224

### Describe the changes you've made
added files related to guessing game

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by kmryashasvi** [comment]
I have done the required changes,
but i am not able to squash all the commits into one,
Please be kind enough to merge this request

**Comment by urvashi-code1255** [comment]
> I have done the required changes,
> but i am not able to squash all the commits into one,
> Please be kind enough to merge this request

@kmryashasvi Read [this](https://www.git-tower.com/learn/git/faq/git-squash/) to squash the commits.

**Comment by kmryashasvi** [comment]
That article is tedious for me,
but you can also do the following in one click,
but I have to go the long way
image

Please tolerate and (squash and merge) this time,
I will not create unnecessary commits by next time.

**Comment by urvashi-code1255** [comment]
@kmryashasvi Sorry but these are 33 commits. You should squash them by your own and learn how to do squashing :)

I know I can squash them but these are much more than expected!!

**Pull request closed without merging**
