### PR TITLE
Added Dice Game files issue#162

### PR DESCRIPTION
**Pull request by bilal-23**
## Related Issue #162
  - 

Closes: #162 

### Describe the changes you've made
Added files for Dice Game and added details of project in script.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
dice

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@bilal-23 Please resolve the merge conflicts

**Comment by bilal-23** [comment]
@urvashi-code1255 Resolved

**Review by urvashi-code1255 — COMMENTED** [review]
@bilal-23 Projects are not visible to me after your changes.

Please check the website locally.

**Comment by bilal-23** [comment]
image

My Project "Dice Game" is visible as well as working locally.

**Comment by bilal-23** [comment]
Please check again. I have fixed the issue

**Pull request closed without merging**
