### PR TITLE
button style changed

### PR DESCRIPTION
**Pull request by khushi935**
UI style of buttons changed and resize the image.

### CODE REVIEW

**Review by Vishal-raj-1 — APPROVED** [review]
Thanks for your contributions

**Comment by Vishal-raj-1** [comment]
@khushi935 

remove


solve this issue

**Comment by Vishal-raj-1** [comment]
@khushi935 I have reverted your changes for now !! Would you please solve this above issue and sent the PR again !! Thanks

**Comment by khushi935** [comment]
Can you specify to me please what I need to change?

**Comment by khushi935** [comment]
Should I apply the same button design or different?

**Comment by khushi935** [comment]
Screenshot (50)
Is it fine?

**Pull request merged**
