### PR TITLE
Added  scroll to top button

### PR DESCRIPTION
**Pull request by Nagsenwaghmare**
## Related Issue #37 
  - I have added Scroll to top button to the main webpage itself

Closes: #37 

### Describe the changes you've made
Added scroll to top button which  should be visible at every part of the page(not only at the bottom).

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Awesome JavaScript Project - Google Chrome 15-02-2021 09_49_41

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @Nagsenwaghmare Your branch has so many unwanted changes!!

**Comment by Nagsenwaghmare** [comment]
> Hey @Nagsenwaghmare Your branch has so many unwanted changes!!

@urvashi-code1255  can you please help me out  so that I can fix them?

**Comment by urvashi-code1255** [comment]
Hey @Nagsenwaghmare You can do a simple thing for now!

Delete your fork and fork it again and add your changes in it and make a new PR!

Make sure to not to touch any single line other than your required changes!!

**Comment by Nagsenwaghmare** [comment]
ok @urvashi-code1255   I have just  made new PR  after  please have a look .

**Pull request closed without merging**
