### PR TITLE
Added Random Maze Generator

### PR DESCRIPTION
**Pull request by Ananya-Misra**
## Related Issue
  - Info about Issue or bug

Closes: #1373

### Describe the changes you've made
I have added a maze generator web app that displays random mazes on refreshing the page.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Comment by Ananya-Misra** [comment]
@ridsuteri @991rajat Please review my PR.

**Comment by Ananya-Misra** [comment]
@urvashi-code1255 @ridsuteri @991rajat  Please review this PR.

**Comment by Ananya-Misra** [comment]
@urvashi-code1255 @ridsuteri @991rajat Please review this PR.

**Comment by Ananya-Misra** [comment]
@Vishal-raj-1 Please review this PR

**Review by ridsuteri — APPROVED** [review]
good work @Ananya-Misra :)

**Pull request merged**
