### PR TITLE
Fixed GIF image and Toggle Button Bug

### PR DESCRIPTION
**Pull request by Rohan27s**
## Related Issue
  - Info about Issue or bug

Closes: #1014 
Closes: #1012

### Describe the changes you've made
I have fixed the GIF loading error in Projects.html on the Text to Voice Generator project as mentioned in #1012  and Fixed the Toggle button Bug as mentioned in issue #1014 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Before(GIF  BUG)-
image
After(GIF BUG RESOLVED)-
image

Before(TOGGLE BUTTON BUG):-
image

After(TOGGLE BUTTON FIXED):-
image

### CODE REVIEW

**Comment by Rohan27s** [comment]
I have fixed both the issues please merge my PR

**Comment by 991rajat** [comment]
@Rohan27s Good Work Please you fix flappy bird too.

**Comment by Rohan27s** [comment]
ok @991rajat

**Comment by Rohan27s** [comment]
@991rajat Fixed the Flappy Bird too
image

**Comment by Rohan27s** [comment]
Can you also please level up my issue because I have solved 3 issues in one PR

**Comment by Rohan27s** [comment]
Can any admin look over my PR?

**Comment by 991rajat** [comment]
Thank you for the contribution. 🤩

**Comment by Rohan27s** [comment]
thank you <3

**Pull request merged**
