### PR TITLE
Click-And-Drag

### PR DESCRIPTION
**Pull request by Meghag5**
## Related Issue
  - Info about Issue or bug

Closes: #68 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
in this project when we drag sideways it will show more pictures and no.s like in netflix when we click and drag it shows more movies.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/65459236/108065580-3c9f5100-7084-11eb-8408-6e1cedce48db.mp4

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @Meghag5 write "closes #68" and remove the extra text in front of closes!!

**Comment by Meghag5** [comment]
> Hey @Meghag5 write "closes #68" and remove the extra text in front of closes!!
> 
> Also, pull the recent changes!!

done

**Comment by urvashi-code1255** [comment]
@Meghag5 Pull the recent changes!!

**Comment by urvashi-code1255** [comment]
Hey @Meghag5 I can't see a single line changed i n your PR!!

**Comment by Meghag5** [comment]
> @Meghag5 Pull the recent changes!!

yes done

**Comment by Meghag5** [comment]
> Hey @Meghag5 I can't see a single line changed i n your PR!!

let me recheck

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @Meghag5 :)

**Pull request merged**
