### PR TITLE
dice game added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
  - Dice game is added 
  - 
Closes: #285

### Describe the changes you've made
I have added the dice game .

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
https://user-images.githubusercontent.com/67833077/114307470-61043080-9afd-11eb-8bd5-49da91c77479.mp4

### CODE REVIEW

**Comment by Ankita297** [comment]
@ridsuteri @Vishal-raj-1 @urvashi-code1255 please review my PR .

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Ankita297 project looks nice, kindly add this project to the script.js file

**Comment by Ankita297** [comment]
@ridsuteri is it okay now ?

**Comment by Ankita297** [comment]
Projects _ Awesome JavaScript - Google Chrome 11-04-2021 20_50_00

**Review by ridsuteri — APPROVED** [review]
good work @Ankita297 ,thanks for contributing :)

**Pull request merged**
