### PR TITLE
Make match game

### PR DESCRIPTION
**Pull request by codDoc98**
## Related Issue
  - #1145 , make match game is now ready!

Closes: #1145 

### Describe the changes you've made
I have added these files 
- public/makeMatchGame.html
- assets/Images/makeMatchGame
- assets/js/makeMatchGame.js
- assets/css/makeMatchGame.css

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
make-match

### CODE REVIEW

**Comment by codDoc98** [comment]
@991rajat  please review Pr of issue #1145 "make match game"

**Review by 991rajat — APPROVED** [review]
Looks Great. Good Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by codDoc98** [comment]
> Thanks for this awesome contribution. 🤩
> Keep Contributing.

thanks @991rajat thnks for giving it level 3 label.

**Pull request merged**
