### PR TITLE
Added payment integration gateway website

### PR DESCRIPTION
**Pull request by siddhi-244**
## Related Issue
  - II have added a payment integration gateway  website 

Closes: #1802 

### Describe the changes you've made
I have made a donation website and in that I have integrated a payment gateway.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
Cool !! Just add details of this project in project list

**Comment by siddhi-244** [comment]
Where is the project list ?

**Comment by siddhi-244** [comment]
@Vishal-raj-1  sir is it done?

**Comment by siddhi-244** [comment]
@Vishal-raj-1 plz check it

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by siddhi-244** [comment]
@Vishal-raj-1  Sir plzz add lgmsoc labels

**Pull request merged**
