### PR TITLE
Train Schedule Manager added

### PR DESCRIPTION
**Pull request by neha07kumari**
## Related Issue
  -Train Schedule Manager

Closes: #1361 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
train_schedule

### CODE REVIEW

**Comment by neha07kumari** [comment]
@ridsuteri Please review my PR and let me know if there are any conflicts.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@neha07kumari the project looks good , but it is not working on my side i.e. when i tried adding trains it didn't appear on the list ,
Kindly check once and fix it :)

**Comment by neha07kumari** [comment]
> @neha07kumari the project looks good , but it is not working on my side i.e. when i tried adding trains it didn't appear on the list ,
> Kindly check once and fix it :)

@ridsuteri I have made the necessary changes. Please review it.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@neha07kumari please resolve the merge conflicts :)

**Pull request merged**
