### PR TITLE
New Project - Temperature Converter

### PR DESCRIPTION
**Pull request by AnshikaAgrawal5501**
## Related Issue
  - Added a new project called Temperature Converter

Closes: #1143

### Describe the changes you've made
- Added a project called Temperature Converter which converts temperature given in any unit to others.
- Added html, css and js file.
- Added a menu bar icon
- Added back cover gif
- The project is completely responsive for all kind of devices.
- Tried to keep the UI clean 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Temperature_Converter_Backcover

### CODE REVIEW

**Comment by AnshikaAgrawal5501** [comment]
Hey @Vishal-raj-1 @urvashi-code1255 @991rajat @ridsuteri @harshgupta20 ,
Please review the PR.
Thanks.

**Review by 991rajat — APPROVED** [review]
Good work. Looks great.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. Keep Contributing.

**Comment by AnshikaAgrawal5501** [comment]
> Good work. Looks great.

Hey @991rajat , Thanks for encouraging.

**Pull request merged**
