### PR TITLE
Added 3d cube effect and AND,OR,XOR Converter

### PR DESCRIPTION
**Pull request by Avishake007**
## Related Issue
  Here I have created 3d cube effect . If you scroll over a div then it will be scrolled in a cubic fashion
I have created the html, css and js file of AND,OR,XOR Converter
Closes: #308  and #312

### Describe the changes you've made
I have created the html, css and js files of 3d cube effect 
I have created the html, css and js file of AND,OR,XOR Converter
### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
3d Effect
ezgif com-gif-maker
AND ,OR,XOR Converter
andorxor(1)

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@Avishake007 Resolve the merge conflicts

**Comment by Avishake007** [comment]
@urvashi-code1255  could you please how to resolve merge conflicts as I am new to this platform

**Comment by Avishake007** [comment]
@urvashi-code1255 I have resolved the merge conflicts

**Review by urvashi-code1255 — COMMENTED** [review]
@Avishake007 Website is looking disbalanced after your changes. PLease have a look

**Comment by Avishake007** [comment]
@urvashi-code1255  I have made the necessary changes but if it is wrong could you please explain me in details about the changes which I have to do

**Pull request closed without merging**
