### PR TITLE
Updation of Pinpad

### PR DESCRIPTION
**Pull request by codeakki**
## Related Issue
  Updation of Pinpad

Closes: #975 

### Describe the changes you've made
-->Addition of Zero in the pin pad.
-->Improvement in CSS
-->Addition of website-icon
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
WhatsApp Image 2021-04-13 at 12 30 46

WhatsApp Image 2021-04-13 at 12 31 02

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@codeakki Please update the GIF of the card

**Comment by codeakki** [comment]
@urvashi-code1255  sure but please first assign me this issue with level

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 sure but please first assign me this issue with level

Done @codeakki :)

**Comment by codeakki** [comment]
@urvashi-code1255  i have added please review mty PR

**Comment by codeakki** [comment]
nd also please add level of issue it was

**Comment by codeakki** [comment]
@harshgupta20

**Comment by codeakki** [comment]
@harshgupta20 sir please merge my PR

**Review by 991rajat — APPROVED** [review]
Good Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
Keep Contributing

**Pull request merged**
