### PR TITLE
Infix expression evaluator added

### PR DESCRIPTION
**Pull request by shivammahajancse**
## Related Issue
  - Info about Issue or bug

Closes: #969 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Infix Evaluator in JavaScript - Google Chrome 18-04-2021 18_55_41

### CODE REVIEW

**Comment by shivammahajancse** [comment]
Please review @ridsuteri @Vishal-raj-1

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@shivammahajancse the project is not working properly on my side,kindly check once again..
and also add this project to script.js file

**Comment by shivammahajancse** [comment]
Sir its working fine
image

**Comment by ridsuteri** [comment]
@shivammahajancse this is how it looks on my side 
Screenshot (29)

**Comment by shivammahajancse** [comment]
Sir i think at your side css is not loaded

**Comment by shivammahajancse** [comment]
sir its working or not can you please enter value

**Comment by shivammahajancse** [comment]
Sir i will check

**Comment by shivammahajancse** [comment]
Sir now check all changes done @ridsuteri

**Review by ridsuteri — APPROVED** [review]
good work @shivammahajancse , thanks for contributing :)

**Pull request merged**
