### PR TITLE
Stop watch page added and image with heading added in home page

### PR DESCRIPTION
**Pull request by khushi935**
Added a stop watch page, added an image and heading in home page.

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @khushi935 Please seperate the html css and js files and add them in their respective folders.
Like html in public etc..

**Comment by khushi935** [comment]
okay.

**Comment by khushi935** [comment]
okay.

**Comment by khushi935** [comment]
I separated the file. Please check it.

**Review by urvashi-code1255 — APPROVED** [review]
Great!! @khushi935 . LGTM 👍

**Pull request merged**
