### PR TITLE
Desgin responsive Landing Page #1343

### PR DESCRIPTION
**Pull request by WebVishal**
Hi @991rajat  @ridsuteri  complete task- #1343 Review the pr and merge in the main branch 

I have added a gif below of the project

https://user-images.githubusercontent.com/76445546/119840139-54f3f700-bf22-11eb-946e-1d576145d5dc.mp4

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@WebVishal Squash commits into one commit and resolve the merge conflicts !!

**Comment by WebVishal** [comment]
@Vishal-raj-1  check now please

**Review by ridsuteri — APPROVED** [review]

**Comment by WebVishal** [comment]
Hey @ridsuteri  thanks to merged my pr but if you not problem can you give me on Level3 on this project I have worked on so hard  😛

**Comment by ridsuteri** [comment]
> Hey @ridsuteri thanks to merged my pr but if you not problem can you give me on Level3 on this project I have worked on so hard 😛

done ! and thanks for contributing :)

**Pull request merged**
