### PR TITLE
Battery Indicator

### PR DESCRIPTION
**Pull request by Ayushjain2205**
## Related Issue

Closes: #1322 

### Describe the changes you've made
Battery indicator with dark mode toggle

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
screenrecording (1)

### CODE REVIEW

**Review by 991rajat — APPROVED** [review]
Looks Good. Good Work

**Comment by 991rajat** [comment]
Just Use static image if you cant reduce the size of the gif.
Use smaller size image.

**Comment by Ayushjain2205** [comment]
@991rajat changes made please take a look

**Review by 991rajat — APPROVED** [review]
Great. Looks Good.

**Pull request merged**
