### PR TITLE
Real-Time-Chat-Application 

### PR DESCRIPTION
**Pull request by Jyoti6828**
**FrontEnd Technologies** - HTML, CSS
**BackEnd Technologies** - JavaScript, Node.js
Used **Socket.io** module for a two-way connection between client and server.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
I am not able to see any files.

**Comment by Jyoti6828** [comment]
Should I make new PR?

**Comment by Vishal-raj-1** [comment]
yes !!

**Comment by Jyoti6828** [comment]
I tried many times but everytime same problem occurred.  What should I do?

**Comment by Vishal-raj-1** [comment]
You can try other project !!

**Comment by Jyoti6828** [comment]
Sure.

**Pull request closed without merging**
