### PR TITLE
Added Bouncing Balls Project

### PR DESCRIPTION
**Pull request by urvashi-code1255**
Capture

@Vishal-raj-1 Have a Look.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Hey @urvashi-code1255 could you please host the site on github page and then show it to me !!

**Comment by urvashi-code1255** [comment]
> Hey @urvashi-code1255 could you please host the site on github page and then show it to me !!

Sure Please have a look [here](https://urvashi-code1255.github.io/Awesome-JavaScript-Projects/)

**Comment by urvashi-code1255** [comment]
I will squash them up when you will be ready to merge :)

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
Well Done @urvashi-code1255 !! This is awesome. Just one change required is change `var` to `let` or `const`.

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM !!

**Pull request merged**
