### PR TITLE
Meme Generator Added

### PR DESCRIPTION
**Pull request by affan880**
## Related Issue
  - Added Meme Generator in which you can explore or create your own meme

Closes: #674 

### Describe the changes you've made
I have added a meme generator through which we can explore and create a meme . I have done it with pure vannla js.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
home page
create page
explorepage

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@affan880 project look great,just resolve the conflicts

**Comment by affan880** [comment]
Resolved the conflict.

**Comment by affan880** [comment]
resolved the conflicts @ridsuteri

**Review by ridsuteri — APPROVED** [review]
good work @affan880 ,thanks for contributing :)
and congrats on your first PR 🎉

**Pull request merged**
