### PR TITLE
New project addition : Rose | ( Mathematics )

### LINKED ISSUE #749: Project Idea : Rose | ( Mathematics )
# rose-mathematics
In mathematics, a rose or rhodonea curve is a sinusoid specified by either the cosine or sine functions with no phase angle that is plotted in polar coordinates. Rose curves or "rhodonea" were named by the Italian mathematician who studied them, Guido Grandi, between the years 1723 and 1728.
This project is an attempt to showcase its visualization.
[*Source-wikipedia*](https://en.m.wikipedia.org/wiki/Rose_(mathematics))

## Main goal
1. Visualize rhondonea curve
2. Educate user about the mathematics behind it
3. Make it interesting and visually easy to understand.

## Tech stack
- **Frontend**: HTML, SCSS/CSS and JavaScript.

## Examples :
image

### PR DESCRIPTION
**Pull request by jhamadhav**
## Describe the changes you've made
I have Made a project called rose-mathematics, to generate beautiful rose patterns using mathematical formulas.
Closes #749 

## Describe if there is any unusual behavior of your code(Write NA if there isn't)
NA

## Checklist:

My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots
Put any screenshot(s) of the project here :
rose

### CODE REVIEW

**Comment by 991rajat** [comment]
Looks Good to me. Just change reduce the size of the gif.
If you know squashing could you squash the commits.
If not leave it. Just reduce the size of the gif.

**Comment by jhamadhav** [comment]
I tried adding the project to `script.js` it gave merge conflict, that's why there are few `issue resolving` commits. Could you please help me with that.
And please add GSSOC'21 and Level tags to the PR.
Thank you !

**Comment by 991rajat** [comment]
@jhamadhav Learn about resolving merge commits. Basically you need to accept both changes.
DM on discord if face any issues.

**Comment by jhamadhav** [comment]
I will do asap

**Comment by jhamadhav** [comment]
@991rajat Please check I have resolved the conflict and added my project to `script.js`

**Review by 991rajat — APPROVED** [review]
Awesome Work. Look Good

**Comment by 991rajat** [comment]
Learn about squashing the commits.It's a good practice.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by jhamadhav** [comment]
Thanks, I surely will!

**Pull request merged**
