### PR TITLE
extra space removed

### LINKED ISSUE #42: Bug in Project Section after recent PR
## Describe the bug
Spacing between project section and about section is increased. Project section has bug.

## Expected behavior
- Reduce the spacing between About and project section. 
- Make all the cards as same as the cards in first row.

## Screenshots
Capture1
Capture2

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

## Additional context
- Please check the whole website before sending a PR(including responsiveness)

### PR DESCRIPTION
**Pull request by khushi935**
#### Issue Number
fixed #42 

#### Describe the changes you've made
Screenshot (57)
Screenshot (59)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
I change the image size only.

#### Test plan (OPTIONAL)
NA

#### Checklist
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
hey @khushi935 Please write fixes #42 in place of #42

**Comment by khushi935** [comment]
Done. Please check it.

**Comment by urvashi-code1255** [comment]
> Done. Please check it.

hey @khushi935 please increase the spacing a little bit from bottom so that text of project section will not be visible in about section

**Comment by khushi935** [comment]
Done.

**Comment by urvashi-code1255** [comment]
@khushi935 please attach the image of the screen after clicking about us in navbar

**Comment by khushi935** [comment]
Screenshot (69)

**Comment by urvashi-code1255** [comment]
@khushi935 See in the picture you attached now. Project section is also interfering in the About section. I want you to adjust the sections so that on clicking the home only home shows and same for about and project section.

**Comment by khushi935** [comment]
> @khushi935 See in the picture you attached now. Project section is also interfering in the About section. I want you to adjust the sections so that on clicking the home only home section shows and same for about and project section.

okay

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107839517-78ab8b00-6dd2-11eb-822c-5f8a9178b659.mp4

I did it please have a look.

**Comment by urvashi-code1255** [comment]
@khushi935 Please resolve the merge conflicts.

**Comment by khushi935** [comment]
I did.

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @khushi935 Thanks for incorporating changes :)

**Pull request merged**
