### PR TITLE
UI of Live Code Editor

### PR DESCRIPTION
**Pull request by AnshikaAgrawal5501**
## Related Issue
Wanted to change the UI of Live Code Editor project

Closes: #1101

### Describe the changes you've made
- Made the CSS and JS file completely separate. Earlier they were included in the HTML file.
- Added bootstrap.
- Changed the UI completely.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Before
Untitled2

After
LiveEditor

### CODE REVIEW

**Comment by AnshikaAgrawal5501** [comment]
Hey @Vishal-raj-1 @urvashi-code1255 @991rajat @harshgupta20 @ridsuteri 
Please review the PR.
Thanks.

**Review by 991rajat — APPROVED** [review]
Good Work. Looks great. :fire:

**Comment by 991rajat** [comment]
Thank You for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by AnshikaAgrawal5501** [comment]
Hey @991rajat, Thanks for the encouragement. 😄

**Pull request merged**
