### PR TITLE
ADDED DarkMode to AJP 

### PR DESCRIPTION
**Pull request by mohammedjameel24**
## Feature
ADDED DARK MODE TO THE AJP WEBSITE.

Closes: #683 

### Describe the changes you've made
changes in file index.html
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

## BEFORE
Screenshot 2021-04-04 234553

## AFTER
Screenshot 2021-04-04 234657

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
please merge my pull request @Vishal-raj-1

**Comment by mohammedjameel24** [comment]
Hello ?

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@mohammedjameel24 looks great on home page , but this theme is not added to other pages like projects ,contact etc..can you add it to them also?
also there are conflcts with index,memeurl and script file 
please resolve the

**Comment by mohammedjameel24** [comment]
Ok

**Comment by ridsuteri** [comment]
@mohammedjameel24 your PR #937 fixed this issue hence i am closing this PR :)

**Pull request closed without merging**
