### PR TITLE
activeLink

### PR DESCRIPTION
**Pull request by Amrutha1101**
## Related Issue
  -  Active link : highlight which link is active in navbar 
  - 
Closes: #1668 

### Describe the changes you've made
I've made changes in script.js file and index.html

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Rizwan-S** [comment]
Hello @Amrutha1101! I don't see any changes reflected from this pr. Can you put a screenshot and explain the changes done.

**Review by Rizwan-S — COMMENTED** [review]
Hello @Amrutha1101! I don't see any changes reflected from this pr. Can you put a screenshot and explain the changes done.

**Comment by Amrutha1101** [comment]
Before: 
Screenshot (131)
After:
Screenshot (133)

In navbar the link wasn't active when clicked before and hence made the changes.

**Comment by Rizwan-S** [comment]
Issue

Hello @Amrutha1101! Although you have solved the issue correctly, you have created another issue as well! As you can see, the effect indicated in the picture is not working properly. Kindly look into it.

**Comment by Amrutha1101** [comment]
I'll resolve the conflicts @Rizwan-S

**Comment by Rizwan-S** [comment]
Hello @Amrutha1101! The work is fantastic! However, it looks like you didn't pull the latest changes locally in your system. As a result, some of the commits made by others have been reverted. Please pull the latest changes and make the pr :)

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Hello @Amrutha1101! The work is fantastic! However, it looks like you didn't pull the latest changes locally in your system. As a result, some of the commits made by others have been reverted. Please pull the latest changes, resolve the conflicts and make the pr :)

**Comment by Amrutha1101** [comment]
There were merge conflicts with this can u delete this PR I've created one more pl

**Pull request closed without merging**
