### PR TITLE
Footer updation

### PR DESCRIPTION
**Pull request by nilisha-jais**
Added github repo link to the footer using github icon.
Screenshot (29)

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @nilisha-jais Shift the github icon to the left of the footer and add some animations to it!!

**Comment by nilisha-jais** [comment]
Animation as in....did you meant hover or something which is strictly animated that changes color or moves with time. Can you please explain!!

**Comment by urvashi-code1255** [comment]
Yeah @nilisha-jais I m talking about the hover effects

**Comment by nilisha-jais** [comment]
1.The font size of the icon now increases on hover
2.The github icon is on the left side

**Review by urvashi-code1255 — CHANGES_REQUESTED** [review]
@nilisha-jais I mean the github icon should be at the extreme left of the footer!!

Also, increase the size of the icon!

And make sure to check the footer responsiveness also!

**Comment by nilisha-jais** [comment]
IMG_20210216_113031

**Comment by nilisha-jais** [comment]
@urvashi-code1255 ma'am please check the screenshot. I guess this position of the icon is looking better in both view whereas when the icon is in extreme left it's not looking cool in both views.

Please share your suggestion then i'll make a pr

**Comment by urvashi-code1255** [comment]
Hey @nilisha-jais Please share a picture with icon in the extreme left!
then I can compare!!

**Comment by nilisha-jais** [comment]
IMG_20210216_165238

**Comment by nilisha-jais** [comment]
@urvashi-code1255 ma'am please check

**Comment by urvashi-code1255** [comment]
@nilisha-jais Do one thing make it left align for larger screens and middle for small screens

Also, resolve the merge conflicts!!

**Comment by nilisha-jais** [comment]
Should I close this pull request and make a new one @urvashi-code1255 ma'am

**Comment by urvashi-code1255** [comment]
> Should I close this pull request and make a new one @urvashi-code1255 ma'am

No @nilisha-jais just resolve the merge conflicts!! you can search on google for how to resolve merge conflicts

**Comment by urvashi-code1255** [comment]
Hey @nilisha-jais I can't see your changes!!

**Comment by nilisha-jais** [comment]
ma'am check now....I made that update to resolve the conflicts

**Comment by nilisha-jais** [comment]
@urvashi-code1255 ma'am

**Comment by Vishal-raj-1** [comment]
Hi @nilisha-jais Could you please squash your commits to single commit ?

**Comment by nilisha-jais** [comment]
It's a single commit only.....after 2 commits I have updated the fork which is the 3rd commit and 4th one is the final one

**Comment by nilisha-jais** [comment]
> Hi @nilisha-jais Could you please squash your commits to single commit ?

facing some error message....should i close this pr  and make a new one

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM !! Thanks for your contribution

**Pull request merged**
