### PR TITLE
rock game updated

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
rock game updated
Closes: #349 

### Describe the changes you've made
I have made the rock paper game responsive.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Rock Paper Scissors - Google Chrome 21-04-2021 11_07_41

Rock Paper Scissors - Google Chrome 21-04-2021 11_07_28

### CODE REVIEW

**Comment by Ankita297** [comment]
@ridsuteri @urvashi-code1255 @harshgupta20 @urvashi-code1255 Please review my PR.

**Comment by Ankita297** [comment]
@ridsuteri @urvashi-code1255 @harshgupta20 @Vishal-raj-1  Please review my PR.

**Comment by Ankita297** [comment]
@ridsuteri @urvashi-code1255 @harshgupta20 @Vishal-raj-1 Please review my PR.

**Comment by 991rajat** [comment]
@Ankita297 Looks Good and work great.
There is a typo in script.js public/Rock-paper-sesssior.html 
Spelling is wrong of "sesssior" due to which it is not able to link properly. Fix that.

**Comment by Ankita297** [comment]
@991rajat Please review it now .

**Review by urvashi-code1255 — COMMENTED** [review]
@Ankita297 please resolve merge conflicts

**Comment by Ankita297** [comment]
@urvashi-code1255 @harshgupta20 @Vishal-raj-1 Please review it now .

**Comment by 991rajat** [comment]
@Ankita297 Great work, everything works fine,
Just don't push script.js As you have only changes css,html
There are lot of projects added again when you pushed script.js.
Just remove script.js and push.

**Comment by Ankita297** [comment]
@991rajat @urvashi-code1255 @ridsuteri Please review it now .

**Review by 991rajat — APPROVED** [review]
Looks Good. Great Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. star_struck
Keep Contributing.

**Pull request merged**
