### PR TITLE
currency converter

### PR DESCRIPTION
**Pull request by Sapna2001**
## Related Issue
Closes: #208

### Describe the changes you've made
Made a currency convertor

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot from 2021-03-09 10-34-44

### CODE REVIEW

**Comment by Sapna2001** [comment]
@urvashi-code1255 @Vishal-raj-1 please review this

**Comment by Vishal-raj-1** [comment]
@Sapna2001 Resolve Conflicts please !!

**Comment by Sapna2001** [comment]
@Vishal-raj-1 resolved

**Review by 991rajat — APPROVED** [review]
Looks Good. Good Work

**Comment by 991rajat** [comment]
Thanks for this awesome contributon. 🤩 
Keep Contributing.

**Pull request merged**
