### PR TITLE
Sejal Code Converter

### PR DESCRIPTION
**Pull request by sejalxz**
## Related Issue
  - Added files of the project Code Converter

Closes: #380 

### Describe the changes you've made
* I added the necessary JavaScript, HTML and CSS files for my Code Converter project.
* Updated script.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

Code_Converter

### CODE REVIEW

**Review by 991rajat — COMMENTED** [review]
@sejalxz 
Good Work Code Works Fine. But
I believe You created branch from previous TV-show branch and added code converter code to it.
Now both project exist in this PR. This is causing issue as you have opened another PR also with TV-show code. Fix it by
creating a different branch from main branch and add code to it. It will be cleaner
Always create branch from main branch if you are implementing new feat and keep main branch sync

**Comment by 991rajat** [comment]
Also Please squash the commits before Pushing

**Comment by sejalxz** [comment]
@991rajat Can you help me with how to pull the changes made in the main repository on your set-up?

**Comment by 991rajat** [comment]
@sejalxz What you could do is pull the latest changes from main branch.
Create a new branch and add your code to it. and Create a PR.
https://levelup.gitconnected.com/how-to-update-fork-repo-from-original-repo-b853387dd471

**Pull request closed without merging**
