### PR TITLE
Added a new Js Project - Movie Seat Booking

### LINKED ISSUE #581: Add Movie Seat Booking
<h1>Movie Seat Booking</h1>
Movie Seat Booking is a vanilla javascript project.

<h2>Functionalities:</h2>

1. Pick a movie
2. Select available seat
3. See the total selected seat number
4. See the total ticket price

### PR DESCRIPTION
**Pull request by Bhavyal9**
Fixed #581 issue
Closes: #581 

### Describe the changes you've made
Added a new js project - movie seat booking

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

Screenshot

> 
Screenshot (12)
Screenshot (13)

### CODE REVIEW

**Comment by Bhavyal9** [comment]
hello @ridsuteri @Alik-Kumar-Ghosh @Vishal-raj-1 please review my pull request, it'll be my first PR under GSSOC'21

**Comment by Bhavyal9** [comment]
hello @ridsuteri @Vishal-raj-1  @Alik-Kumar-Ghosh  please review my pull request, it'll be my first PR under GSSOC'21

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Bhavyal9 the project website and  script.js file has been changed recently ,and your  project section isn't working correctly with the new version.kindly check locally and do the necessary changes

**Comment by Bhavyal9** [comment]
@ridsuteri created a new pull request. Sorry, I'm not well versed with Github. Can you please look into it.

**Pull request closed without merging**
