### PR TITLE
modify local storage project #942

### PR DESCRIPTION
**Pull request by Vedant-Rahane**
## Related Issue
  - modify local storage project #942

Closes: #942 

### Describe the changes you've made
- Modify styling.
- Change UI of project.
- Removed unwanted content.
- Make well responsive.
- Make code clean.

### Describe if there is any unusual behavior of your code
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

Before : 

local-storage-before

After :

local-storage-after

### CODE REVIEW

**Comment by 991rajat** [comment]
@Vedant-Rahane Are you using any kind of formatter when saving the file?
Script js is changed very much and conflicts are there, Please resolve them, Technically script.js would not required to be changed as you are working only on UI part.

**Comment by Vedant-Rahane** [comment]
As Project UI is changed we need to update new Project Image so I had changed script.js
I had removed conflicts. @991rajat can you please review again.

**Comment by 991rajat** [comment]
@Vedant-Rahane  That requires only change one line in script.js of Image portion,
But lot of projects are removed what you are pushing, Merging this PR will lead to removal of a lot of existing projects.
Fix the script.js, Let me know If you need any help, DM on discord if not available  on github

**Comment by Vedant-Rahane** [comment]
@991rajat I am really sorry but I don't know how this happened. While pushing I had only made one change in project image. 
I have resolved conflicts is it ok now ?

**Comment by 991rajat** [comment]
Yeah Looks Good.

**Comment by 991rajat** [comment]
Thanks for this contribution.
Keep Contributing.

**Pull request merged**
