### PR TITLE
URL Shortner updated

### PR DESCRIPTION
**Pull request by yashikabhargava**
## Related Issue
  - URL Shortner : Alignment and hover

Closes: #204 

### Describe the changes you've made
alignment of text & button to the center and changes in styling of button.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

URL Shortner - 1

URL Shortner - 2

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@yashikabhargava Please update the GIF too

**Comment by yashikabhargava** [comment]
Can you please tell me which GIF do I have to update?

**Comment by urvashi-code1255** [comment]
@yashikabhargava please update the GIF of the url shortner project from script.js

**Comment by yashikabhargava** [comment]
okay

**Review by urvashi-code1255 — APPROVED** [review]
@yashikabhargava Its looking good now. Thanks for your contribution :)

**Comment by yashikabhargava** [comment]
hey, I made this PR under gssoc21 can you please label it because I am not getting a proper score on the scoreboard.

**Comment by yashikabhargava** [comment]
Hi, Can you please label it with gssoc label, I'm not getting proper score on leaderboard.

**Pull request merged**
