### PR TITLE
Fixed bug of more projects button

### PR DESCRIPTION
**Pull request by Atif0604**
## Related Issue
  - Fixed bug of more projects button

Closes: #1855  will be closed through this PR](Bug in More Project Button on Home Page #1855)

### Describe the changes you've made
Fixed the mis-aligned button

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [✔️ ] My code follows the style guidelines of this project.
- [ ✔️] I have performed a self-review of my own code.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.
- [✔️] I have made corresponding changes to the documentation.
- [ ✔️] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image
image

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @Rizwan-S 
Please Review my PR

**Comment by Rizwan-S** [comment]
Bro, please pull the changes before making a pr. It looks like this pr ate up some people's codes.

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Bro, please pull the latest changes before making a pr. This pr ate up other people's codes. 👀

**Comment by Atif0604** [comment]
😢 ohk let me make a pull
@Rizwan-S

**Comment by Atif0604** [comment]
is it Good to go now?
@Rizwan-S

**Review by Rizwan-S — APPROVED** [review]
Yes it is!

**Pull request merged**
