### PR TITLE
Added Error page

### PR DESCRIPTION
**Pull request by anjali1102**
## Related Issue
  - Info about Issue or bug

Closes: #891 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Error-Page

### CODE REVIEW

**Comment by anjali1102** [comment]
Error-Page

**Comment by anjali1102** [comment]
@harshgupta20  review pls

**Comment by 991rajat** [comment]
@anjali1102 How it will be shown? If you are linking with some links which are not working do so 
If not I have an idea you can create a project named Error Pages add it there.

**Comment by Furquan712** [comment]
I would like to work on this issue, will you assign me ?

**Comment by anjali1102** [comment]
PR has been given.

**Comment by anjali1102** [comment]
> @anjali1102 How it will be shown? If you are linking with some links which are not working do so
> If not I have an idea you can create a project named Error Pages add it there.

I didn't get question. As far I understood your question, I design 404 error page as default page doesn't soothing for eyes. Once you deploy these changes on github pages, it will redirect to this new page @991rajat

**Comment by anjali1102** [comment]
Sorry for delay response. I was unwell from few days @991rajat

**Comment by 991rajat** [comment]
No Problem, Stay Safe and Healthy.
I thought It's need to link it somewhere so that when we hit any wrong url it will direct us to error page.
Will merge it, Good Work

**Comment by 991rajat** [comment]
Thanks for this contribution. :star_struck: 
Keep Contributing.

**Pull request merged**
