### PR TITLE
Project addition : John Conway's Game of life

### LINKED ISSUE #730: Project Idea : John Conway's game of life
# Game-of-life
A project inspired by John Conway's game of life. 
The Game of Life, also known simply as Life, is a cellular automaton devised by the British mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves.
*Source - wikipedia*

## Main goal
1. Make a simulator to simulate the rules in the game of life
2. Let the user make or change the patterns
3. Add different preloaded and known patterns
4. Add info regarding the concept
5. Add slider to increase and see each individual steps

## Tech stack
- **Frontend**: HTML, SCSS/CSS and JavaScript.

## Examples :
image

### PR DESCRIPTION
**Pull request by jhamadhav**
## Describe the changes you've made

A project inspired by John Conway's game of life.
The Game of Life, also known simply as Life, is a cellular automaton devised by the British mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves

Closes #730

## Describe if there is any unusual behavior of your code(Write NA if there isn't)

NA

## Checklist:

My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots
Put any screenshot(s) of the project here : 
demo

### CODE REVIEW

**Comment by jhamadhav** [comment]
@991rajat @Vishal-raj-1 please check the PR for merge and add GSSOC'21 and level tag.
Thank you!

**Comment by urvashi-code1255** [comment]
@jhamadhav I just loved your project.

Please squash your 39 commits into 1.
Please resolve the merge conflicts.

**Comment by jhamadhav** [comment]
@urvashi-code1255 Thank you!
How do I squash? I tried `git rebase -i Head` in another PR but it just creates another PR ?
The conflict with script.js is quite a blunder, I checked the main repo; there are many duplicate projects.
Can you please help?

**Comment by 991rajat** [comment]
Hey @jhamadhav Awesome Work. Just one thing more you know about squashing ? could you perform it.
Squash them into 1 commit. If not please let me know.

**Comment by jhamadhav** [comment]
@991rajat the same issue is coming up while squashing this too 😥
Please squash this via UI.
and add GSSOC'21 and level tag too!
Thank you!

**Review by 991rajat — APPROVED** [review]
Looks Good.

**Comment by 991rajat** [comment]
Thnaks for this awesome contribution. 🤩 
Keep Contributing.

**Comment by jhamadhav** [comment]
Thank you!

**Pull request merged**
