### PR TITLE
fixed issue 920

### PR DESCRIPTION
**Pull request by hritikgupta92**
## Related Issue
  -Closes: #920  
Created WebDevelopment Course webpage

### Describe the changes you've made
Created a webpage for a webdevelopment course organised by the 3rd year Student of DTU,for 1st and 2nd year students,basically showing their details.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image
image

### CODE REVIEW

**Comment by hritikgupta92** [comment]
@991rajat  please review it

**Comment by 991rajat** [comment]
CSS is broken. Please Look at this at once.
image

**Comment by hritikgupta92** [comment]
ok

**Comment by hritikgupta92** [comment]
I am closing this pr and  I'll create a new one

**Pull request closed without merging**
