### PR TITLE
Adding placeholder in the required fields in contact us section.

### PR DESCRIPTION
**Pull request by RubenFalcao14**
I have added the placeholder  in the required fields in contact us section.
Closes: #688 

### Describe the changes you've made
I have added the placeholder  in the required fields in contact us section.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@RubenFalcao14 Why did you make this PR as draft. Are you still working on it ?

**Comment by RubenFalcao14** [comment]
@Vishal-raj-1 No . Sorry 😓

**Comment by RubenFalcao14** [comment]
@Vishal-raj-1 Should I make a new PR ?

**Review by urvashi-code1255 — APPROVED** [review]
No Problem @RubenFalcao14 I have made it a Normal PR :)

Thanks for contributing :)

**Pull request merged**
