### PR TITLE
Adding Falling leaves theme to Word counter project

### PR DESCRIPTION
**Pull request by mahesh-11102**
## Related Issue
  - Added falling leaves theme to the Word Counter project to make the project look more catchy :)
## Describe the changes you've made
I have made the following changes :-
- updated wordCounter.html file
- updated  wordCounter.css file
- added leaves folder to the Image section
- updated script.js file'
- updated wordCount.gif file

## Describe if there is any unusual behaviour of your code
- `NA`

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
wordCounter

@ridsuteri  @harshgupta20 @991rajat  @Vishal-raj-1  , please review the changes and guide me if any changes are required.
Thank you :-)

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@mahesh-11102 kindly resolve merge conflicts

**Comment by mahesh-11102** [comment]
@ridsuteri  sir i resolved the conflicts and updated the gif path for some projects which weremissing in the main website :)

image

**Review by ridsuteri — APPROVED** [review]
good work @mahesh-11102 ,thanks for contributing :)

**Comment by mahesh-11102** [comment]
THANK YOU @ridsuteri  sir  :)

**Pull request merged**
