### PR TITLE
fixed bug and added features in local storage

### PR DESCRIPTION
**Pull request by Saumya-07**
## Related Issue
  - Fixed bug in local storage project and added few functionalities

Closes: #307

### Describe the changes you've made
Fixed issue of item was not getting checked
Added functionalities like a trash-can for deleting the item 
and refresh button to clear the list.

### Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
localStorage

### CODE REVIEW

**Comment by Saumya-07** [comment]
Please give any feedback regarding the PR#707 @Vishal-raj-1 @urvashi-code1255

**Comment by 991rajat** [comment]
Please resolve the conflicts.
Could you specify on which PR for the feedback?

**Comment by Saumya-07** [comment]
I was talking about this PR only, whatever changes I made and added features, are they fine? 
or any changes are required?

**Review by Vishal-raj-1 — APPROVED** [review]
Thanks for your contribution !!

**Pull request merged**
