### PR TITLE
Added Progress Steps JavaScript Project

### PR DESCRIPTION
**Pull request by gaurav24072002**
## Related Issue

Closes: #847 

### Describe the changes you've made
I Have created an Awesome JavaScript Project : Progress Steps which will be useful to map the Progress Bar or any other use.

### Checklist:
- [x] Added gif in ```assets/GIFs/Progress_steps.gif```
- [x] I have performed a self-review of my own code.
- [x] Added JSON in script.js
- [x] Opened an issue for this PR

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@gaurav24072002 Resolve conflicts Please

**Comment by gaurav24072002** [comment]
@Vishal-raj-1 I have solved the conflicts now you can merge...

**Comment by 991rajat** [comment]
Thanks for the contribution. star_struck

**Comment by 991rajat** [comment]
Learn about Squashing the commits it's a good practice.

**Pull request merged**
