### PR TITLE
Chess Application Project Added

### PR DESCRIPTION
**Pull request by Subhampreet**
## Related Issue
  - A Chess Game Application

Closes: #527 

### Describe the changes you've made
I have developed a 2-Player Chess Game Project using Vanilla JavaScript and added it to the Repository. The Chess Application shows the possible moves and also toggles as per the game from Black to white and vice versa.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
c1
c2

### CODE REVIEW

**Comment by 991rajat** [comment]
Add the project to script.js. Also remember don't create big size gif for the project. Reduce the size of the gif too.

**Comment by urvashi-code1255** [comment]
@Subhampreet Any updates on this?

**Comment by Vishal-raj-1** [comment]
@Subhampreet Update this PRs else I will Close this PR in next two days !!

**Comment by Vishal-raj-1** [comment]
****

**Pull request closed without merging**
