### PR TITLE
Document to Handwritting

### PR DESCRIPTION
**Pull request by Priyadarshan2000**
## Related Issue
-  **I have created Document to Handwriting.**

Closes: #679

### Describe the changes you've made
This is a Document to Handwriting a website using HTML, CSS, JS and Google font API. We type our work in the text box and our work will be converted to handwriting. On this site, we can change 10 different types of font. On this site we can change the font width On this site, we can upload our own font. our work will be downloaded into a png Format. This site also available in Dark Mode.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@Priyadarshan2000 Squash your commits into one commit

**Comment by Priyadarshan2000** [comment]
@Vishal-raj-1 sir I change any commit?

**Comment by 991rajat** [comment]
@Priyadarshan2000 Follow the file structure. 
HTML file in public
JS,CSS in assets
Add the project to script.js
Why there is readme file

**Comment by Priyadarshan2000** [comment]
sir any changes

**Comment by 991rajat** [comment]
You have to follow the structure. In current codebase.
Add whatever files necessary to run the your project.
Readme is not required.

**Comment by Priyadarshan2000** [comment]
ok sir I deleted the readme file or any changes sir..?

**Comment by 991rajat** [comment]
Follow the file structure please, yours rightnow having a another folder name /Document to Handwritting
Just fix the structure.
And add project to script.js.

**Comment by Priyadarshan2000** [comment]
@991rajat sir I have done my changes

**Review by 991rajat — APPROVED** [review]
Looks good. Good Work

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. 🤩 
 Keep Contributing.

**Comment by Priyadarshan2000** [comment]
thank you, @991rajat sir..

**Pull request merged**
