### PR TITLE
added Reaction Game

### PR DESCRIPTION
**Pull request by Rishika-05**
## Related Issue
  - This is not an issue. This a reaction game where a person has to click on the shape within 1 second to score a maximum of 15 points else they lose.

Closes: #1141

### Describe the changes you've made
I've have made the changes in the public, assets(css,js,Images) and script.js file.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
js

### CODE REVIEW

**Comment by Rishika-05** [comment]
@991rajat Please review the PR. I've closed the last PR as I was facing two many conflicts.

**Review by 991rajat — APPROVED** [review]
Good Work. Looks Good

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing.

**Comment by Rishika-05** [comment]
Thank you @991rajat . Looking forward to contribute more. ☺
And learn form your suggestions as well.

**Pull request merged**
