### PR TITLE
Added the Custom Styled Vide Player

### PR DESCRIPTION
**Pull request by K-jais**
It solves issue #974

Its working video,

https://user-images.githubusercontent.com/75881393/114943665-fa1baa00-9e63-11eb-8593-31324266e463.mp4

### CODE REVIEW

**Comment by K-jais** [comment]
Please @991rajat review this PR

**Comment by K-jais** [comment]
@991rajat @harshgupta20

**Comment by K-jais** [comment]
@ridsuteri

**Comment by K-jais** [comment]
@991rajat @ridsuteri @harshgupta20 @urvashi-code1255 @Vishal-raj-1 ?

**Comment by K-jais** [comment]
@urvashi-code1255 ?

**Comment by 991rajat** [comment]
Good Work.Please reduce the file of gif.
If possible reduce the size of video also. If not leave it no problem

**Comment by K-jais** [comment]
Sir @991rajat I have reduced the size. Above that, it can't be reduced.

**Comment by K-jais** [comment]
Please review this Pr @991rajat

**Comment by 991rajat** [comment]
I guess it can't be reduced further. Just change it to static image of the project.

**Comment by K-jais** [comment]
Sir @991rajat, the gif has been replaced by an image. Please review the PR now.

**Comment by K-jais** [comment]
@991rajat  please look into this

**Comment by K-jais** [comment]
Please @991rajat sir review this PR.

**Comment by K-jais** [comment]
@991rajat  @Vishal-raj-1 @ridsuteri

**Comment by K-jais** [comment]
@urvashi-code1255

**Comment by K-jais** [comment]
@ridsuteri sir look into this?

**Review by ridsuteri — APPROVED** [review]
good work @K-jais , thanks for contributing :)

**Pull request merged**
