### PR TITLE
Project addition : Fractal tree

### LINKED ISSUE #980: Project idea : Fractal tree
# fractal-tree
The Pythagoras tree is a plane fractal constructed from squares. Invented by the Dutch mathematics teacher Albert E. Bosman in 1942, it is named after the ancient Greek mathematician Pythagoras because each triple of touching squares encloses a right triangle, in a configuration traditionally used to depict the Pythagorean theorem. It is also known as `Fractal tree`.
This project is an attempt to showcase its visualization.
[*Source-wikipedia*](https://en.wikipedia.org/wiki/Pythagoras_tree_(fractal))

## Main goal
1. Visualize fractal tree
2. Educate user about the mathematics behind it

## Tech stack
- **Frontend**: HTML, SCSS/CSS and JavaScript.

## Examples : 
image

Under GSSOC'21 , I would love to develop it and contribute to this project.

### PR DESCRIPTION
**Pull request by jhamadhav**
## Describe the changes you've made

Project `Fractal Tree` added.

Closes #980 

## Describe if there is any unusual behavior of your code(Write NA if there isn't)
NA

## Checklist:

My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Screenshots
Put any screenshot(s) of the project here :
fractalTree

### CODE REVIEW

**Comment by jhamadhav** [comment]
@991rajat @Vishal-raj-1 please review the PR.

**Review by urvashi-code1255 — APPROVED** [review]
It's looking good to me @jhamadhav

**Comment by jhamadhav** [comment]
@urvashi-code1255 please add GSSOC'21 and level tag too

**Comment by urvashi-code1255** [comment]
Just add your project details in main script.js @jhamadhav

**Comment by jhamadhav** [comment]
@urvashi-code1255 please refer to issue #1080 before resolving that adding anything to script.js will result in many merge conflicts

**Comment by urvashi-code1255** [comment]
@jhamadhav I have assigned that issue to you. Please add your project details in it while solving that issue.

**Comment by jhamadhav** [comment]
Cool I will do resolve it as soon as possible 👍

**Pull request merged**
