### PR TITLE
Created Knapsack Project

### PR DESCRIPTION
**Pull request by wahfei**
…is in the assets folder

## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
I created a KnapSack.html file together with its .css and .js file.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
Please add the project details in 'script.js' file.

**Comment by wahfei** [comment]
i have added the project details into script.js

**Comment by Rizwan-S** [comment]
Hello! Is this fractional Knapsack or 1-0 knapsack?

**Comment by wahfei** [comment]
it is 0/1 knapsack

**Review by Rizwan-S — CHANGES_REQUESTED** [review]
1. Can you please put the description of problem in the html page.
2. For the input W = 50, weight = {10,20,30} & value = {60, 100, 120}, I get the output as (1, 1, 0). I'm not able to make out anything from this output. If its the indices of the weight array, I believe that the solution is wrong since the output should  be (0, 1, 1). 
Please look into it.

**Comment by wahfei** [comment]
Hello, i think this is one of the limitation of knapsack greedy which will not give the optimal solution but will give the profit which is maximized, i calculate each of their profit by weight which gives me p/w ={6,5,4} respectively for the input that you've given, and it will take the largest profit by weight first and so on. Therefore, 10 and 20 is taken without 30 with the final profit of 160 where in return give the profit by weight of ( 160/30 = 5.3333).

if the algorithm would to take 0,1,1 , the maximum profit will be 240 and the profit/weight will be (240/50 = 4.8) which is lesser than 1,1,0

**Comment by Rizwan-S** [comment]
Thanks for the explanation! However, can you put the description in the html page. This will help new users to understand the problem statement and relate the solution.

**Comment by wahfei** [comment]
hello, i have done adding the description about the project.

**Review by Rizwan-S — APPROVED** [review]
Excellent!

**Pull request merged**
