### PR TITLE
Resolved rockpaperscissors

### PR DESCRIPTION
**Pull request by nagasaisriya**
## Related Issue
  - Info about Issue or bug resolved responsiveness of RockpaperScissors Project

Closes: #[issue number that will be closed through this PR]
#349

### Describe the changes you've made
Have modified Grid Columns  and added flex to css to make it responsive
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
A clear and concise description of it.

### Checklist:

- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ]  I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have made corresponding changes to the documentation.
- [ x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
Few suggestions On Desktop view the format is breaking 
| Original | Yours |
|   |   |
|---|---|

**Comment by nagasaisriya** [comment]
> Few suggestions On Desktop view the format is breaking
> | Original | Yours |
> 
> 	
> Make mobile responsive
> Let me know if you need any help.

Hey @991rajat , I'm trying to make the mobile view responsive, but it changed the desktop version, can you help with it? Thanks in advance.

**Comment by 991rajat** [comment]
What problem are you facing? DM on discord

**Comment by urvashi-code1255** [comment]
@nagasaisriya Any updates?

**Comment by nagasaisriya** [comment]
> @nagasaisriya Any updates?

sorry, I can't get anymore ideas to improve, can you merge it please?,I've been trying hard but it has many conflicts, you can open it for others.

**Comment by 991rajat** [comment]
Okay Resolve the commits Please.

**Comment by ridsuteri** [comment]
@nagasaisriya any updates ? or should i close this PR and open the issue for others ?

**Comment by nagasaisriya** [comment]
> @nagasaisriya any updates ? or should i close this PR and open the issue for others ?

You can open this issue for others

**Pull request closed without merging**
