### PR TITLE
spellings correction

### PR DESCRIPTION
**Pull request by lakshita15**
##661 resolved
  - Spelling Correction.

I updated the spellings of scissor in the code

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@lakshita15 you missed this one
Screenshot (13)_LI

**Comment by lakshita15** [comment]
Ok

**Comment by lakshita15** [comment]
@ridsuteri plss merge the files..

**Comment by lakshita15** [comment]
Changes done!

**Comment by lakshita15** [comment]
@ridsuteri plss check this and tell me

**Comment by lakshita15** [comment]
@Vishal-raj-1 plss check this request,.....

**Comment by lakshita15** [comment]
@harshgupta20 check the pr plss

**Comment by harshgupta20** [comment]
@lakshita15  Please don't commit on Master Branch, Create your separate branch for it.

**Comment by lakshita15** [comment]
Okay I’have deleted this and made new fork and do the suggested changes in
that . It’ll be clean.

**Comment by ridsuteri** [comment]
@lakshita15 i am closing this PR since your PR #814 has resolved the issue

**Pull request closed without merging**
