### PR TITLE
added sidenav and card for index.html page

### LINKED ISSUE #80: add sidenav
## Is your feature request related to a problem? Please describe.
Yes, this feature is useful for any websites to simply access the menu 

## Describe the solution you'd like
I would like to add a Sidenav .made by JAVASCRIPT, HTML, CSS

## Additional context
Useful to show/hide the menu in any website 

Demo
Sidenav

### PR DESCRIPTION
**Pull request by fsafarkhani**
Issue Number 
fixes #80
Describe the changes you've made
I have just added a simple kind of sidenav that anyone can use easily on any websites to access the menu simply

Describe if there is any unusual behavior of your code(Write NA if there isn't)
NA  

Checklist
•	  My code follows the code style of this project.
•	  The title of my pull request is a short description of the requested changes.
•	  Open Source Program names(@fsafarkhani)

Demo uploaded

Sidenav

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hi @fsafarkhani Please edit your PR and follow [this](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/.github/PR_template.md) PR template and fill it accordingly!

Capture
You can edit the PR using this edit option!

**Comment by fsafarkhani** [comment]
Done.
@urvashi-code1255  Thank you for your help

**Comment by urvashi-code1255** [comment]
> Done.
> @urvashi-code1255 Thank you for your help

Hey @fsafarkhani write fixes #issue_no in place of #issue_no

**Comment by fsafarkhani** [comment]
> > Done.
> > @urvashi-code1255 Thank you for your help
> 
> Hey @fsafarkhani write fixes #issue_no in place of #issue_no

Edited

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM

**Pull request merged**
