### PR TITLE
Enhanced the visual of counter

### PR DESCRIPTION
**Pull request by kanisshka**
## Related Issue
  - Info about Issue or bug

Closes: #1005 

### Describe the changes you've made
improved the css of the project-Enhancing the visual of counter

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
After the enhancement of css-
Screenshot (619)

### CODE REVIEW

**Comment by 991rajat** [comment]
Looks Good.

**Comment by 991rajat** [comment]
Thanks for the contribution. Keep Contributing.

**Comment by kanisshka** [comment]
> Looks Good.

Thank uh

**Comment by kanisshka** [comment]
> Thanks for the contribution. Keep Contributing.

Can I have to add GIF for this ??

**Pull request merged**
