### PR TITLE
World Clock

### PR DESCRIPTION
**Pull request by Priyadarshan2000**
## Related Issue
  - I have created World Clock 

Closes: #1350 

### Describe the changes you've made
-Time change
-world any city time show

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by Priyadarshan2000** [comment]
@harshgupta20 I PR my project plz review it

**Comment by Priyadarshan2000** [comment]
@harshgupta20 , @991rajat , @Vishal-raj-1 sir plz review my code and merge it only 2 days left closing Gssoc'21

**Review by 991rajat — APPROVED** [review]
Looks Good

**Comment by Priyadarshan2000** [comment]
@991rajat sir thank you sir

**Pull request merged**
