### PR TITLE
Made Drum-Kit responsive

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed- #854
Made site responsive

Screenshots:
Earlier:

dk-old

NOW:

dk-new

@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR

### CODE REVIEW

**Review by ridsuteri — COMMENTED** [review]
@Bhavya-Sehgal drumkit prject is responsive already...
kindly check once again !
Screenshot (22)

**Comment by Bhavya-Sehgal** [comment]
> @Bhavya-Sehgal drumkit prject is responsive already...
> kindly check once again !

No, its not . On my side its like dis: 

drum
@ridsuteri

**Comment by ridsuteri** [comment]
@Bhavya-Sehgal are you checking it from the main deployed site?

**Comment by Bhavya-Sehgal** [comment]
@ridsuteri  Yess

**Pull request merged**
