### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by Aditya201551**
## Related Issue
  - Added footer at index.html

Closes: #882 

### Describe the changes you've made
- Created footer
- Made it responsive

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (81)

Screenshot (83)

@ridsuteri

### CODE REVIEW

**Comment by Aditya201551** [comment]
dsjchbdskujc

**Review by ridsuteri — COMMENTED** [review]
@Aditya201551 it is showing something like this on my side

Screenshot (27)

have a look !
please verify once again.

**Comment by Aditya201551** [comment]
@ridsuteri IDK what happened, well I am having exams so I cannot work on this issue more, I am closing this pr please assign this issue to someone else

**Comment by ridsuteri** [comment]
ok @Aditya201551 ! and best of luck for the exams :)

**Pull request closed without merging**
