### PR TITLE
Adding Reaction game

### PR DESCRIPTION
**Pull request by Rishika-05**
## Related Issue
  - This is a game where player has to click on the following circles as they appear within 1 second to score maximum of 15 points or they lose.

Closes: #1141 [issue number that will be closed through this PR]

### Describe the changes you've made
I have added the html file(public folder)- ReactionGame.html, CSS and JS file in the assets folder (ReactionGame.css & ReactionGame.js). I've added an image in the images folder.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
js

### CODE REVIEW

**Comment by Rishika-05** [comment]
Please review my PR. @991rajat @urvashi-code1255 @Vishal-raj-1

**Comment by 991rajat** [comment]
@Rishika-05 Add the game to script.js

**Comment by Rishika-05** [comment]
@991rajat I've made the required changes. Please review it.

**Comment by 991rajat** [comment]
@Rishika-05 Projects works fine. All good, There's a issue with script.js 
A lot of changes are done there which were not required. Lot of projects removed and changed. Fix that only 4-5 lines needed to seen there i.em only of your project.

Let me know if need any help. DM on discord if not available at git.

**Comment by 991rajat** [comment]
@Rishika-05 What happened You closed the issue. Not interested ?

**Comment by Rishika-05** [comment]
Sorry for the inconvenience @991rajat . I tried to resolve the issue but wasn't able to so I've closed this issue and opened a new one instead. Please review that.

**Pull request closed without merging**
