### PR TITLE
Issue 413

### PR DESCRIPTION
**Pull request by narasimhareddy04**
## Related Issue
  This is the pull request of an issue no 413, which is to add an SGPA and CGPA calculator created using HTML, CSS and Java 
  script.

Closes: #413

### Describe the changes you've made
I've created a new Javascript project called SGPA and CGPA calculator. I've created a new branch callled issue-413 as requested by @ridsuteri. And also I've added my project to the script.js file as requested by @ridsuteri . Please merge my project with the Awesome Javascript projects. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
gssoc_ss2
gssoc_ss1

### CODE REVIEW

**Comment by narasimhareddy04** [comment]
@ridsuteri I've created a custom branch called **issue-413** instead of using **main** branch. Please take a look at my PR and merge it. I can't understand how to resolve the conflicts in the script.js file. I've added my project details in the script.js file just like everyone, but I don't know why there has been conflicts with it. Can you please help me?

**Comment by ridsuteri** [comment]
@narasimhareddy04 shared a article link with you kindly have a look

**Review by ridsuteri — APPROVED** [review]
good work @narasimhareddy04 , thanks for contributing and congrats on your first PR 🎉🎉

**Comment by narasimhareddy04** [comment]
Thank you @ridsuteri  on merging my project.

**Pull request merged**
