### PR TITLE
button removed and redirect added on image

### PR DESCRIPTION
**Pull request by khushi935**
#31

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Hey @khushi935 please resolve the merge conflicts .

**Comment by khushi935** [comment]
How to solve merge conflicts? Please guide me.

**Comment by urvashi-code1255** [comment]
> How to solve merge conflicts? Please guide me.

You can refer [this](https://youtu.be/JtIX3HJKwfo) @khushi935

**Comment by khushi935** [comment]
I closed this PR and raise another, now it does not have conflicts.

**Pull request closed without merging**
