### PR TITLE
styled navbar 

### PR DESCRIPTION
**Pull request by Muskan-creator**
## Related Issue
  Navbar is blurred when scrolling down .
I have solved bug and also added animations to navbar

Closes: #998 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

https://user-images.githubusercontent.com/59757988/115053424-be80ee80-9efc-11eb-88fa-5fbe73b983b3.mp4

### CODE REVIEW

**Comment by Muskan-creator** [comment]
@urvashi-code1255 I have styled navbar please review and merge my PR
Thanks :)

**Review by urvashi-code1255 — COMMENTED** [review]
@Muskan-creator please remove these two GitHub icons from the home page navbar and put only one there

**Comment by Muskan-creator** [comment]
> @Muskan-creator please remove these two GitHub icons from the home page navbar and put only one there

@urvashi-code1255  Actually I have not created that two github links It has alreadycreated before my PR .I have not removed this because someone  has raised issue of two github links and has assigned that issue so for that I thought He/she has working already on that and if I change it brought conflicts to him/her

**Comment by urvashi-code1255** [comment]
@Muskan-creator now that PR is merged so please you do this as it's not looking good 😊

**Comment by Muskan-creator** [comment]
Please see issue #1027 (it is already assigned).

**Comment by Muskan-creator** [comment]
> Please see issue #1027 (it is already assigned).

@urvashi-code1255

**Comment by urvashi-code1255** [comment]
Okay thanks for informing me @Muskan-creator 😊

**Pull request merged**
