### PR TITLE
added sudoku game

### LINKED ISSUE #1174: addition of sudoku game
## Is your feature request related to a problem? Please describe.
No its not a problem. Its a  addition of new script
## Describe the solution you'd like
I would like to add a sudoku game which will be completely build with plain js,html and css

## Additional context
I am a GSSOC participant.
Please assign this to me.
@Vishal-raj-1

### PR DESCRIPTION
**Pull request by robin025**
## Related Issue
  - fixes #1174 

Closes: #1174 

### Describe the changes you've made
I Have added a Sudoku game written in completely plain js, html and css
- Here user can set the difficulty of the game
- User can set the game view in mobile mode as well as desktop mode

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [X ] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
sudoku

### CODE REVIEW

**Comment by 991rajat** [comment]
Looks Good. Great work.

**Comment by 991rajat** [comment]
Next time always create a new branch don't work on main branch.

**Comment by 991rajat** [comment]
Congratulation on merging of first PR. 
Thanks for this awesome contribution. :tada: 
Keep Contributing.

**Comment by robin025** [comment]
> Next time always create a new branch don't work on main branch.

Really sorry for the inconvenience

**Comment by 991rajat** [comment]
No problem brother. Keep Working

**Pull request merged**
