### PR TITLE
Added a password generator app

### PR DESCRIPTION
**Pull request by vanshikachokhani**
### Changes made
I have created a basic javascript application to generate password of desired length and characteristics such a uppercase, lowercase letters, symbols and numbers

- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot from 2021-02-18 23-01-35

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
@vanshikachokhani Nice Project. Thanks for your contribution !!

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by vanshikachokhani** [comment]
I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted?
Please help @991rajat @ridsuteri @ @harshgupta20

**Comment by ridsuteri** [comment]
> I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted?
> Please help @991rajat @ridsuteri @ @harshgupta20

@Vishal-raj-1 @urvashi-code1255

**Comment by ridsuteri** [comment]
> I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted?
> Please help @991rajat @ridsuteri @ @harshgupta20

nopes @vanshikachokhani :( , it won't be counted under gssoc

**Pull request merged**
