### PR TITLE
Old content for About us removed. Only new and improved content exists now.

### PR DESCRIPTION
**Pull request by aastha621**
## Related Issue
  The old content was still there after the new content ended. This was probably because of a merge conflict. It is resolved and only the improved content exists now.

Closes: #1065 1065

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by aastha621** [comment]
@urvashi-code1255 pls review this and merge....the old content looks bad and incorrect.

**Comment by 991rajat** [comment]
I'm not able to get it, what changes did you do here?
were there any mistakes in about us section?

**Comment by aastha621** [comment]
> I'm not able to get it, what changes did you do here?
> were there any mistakes in about us section?

Actually I had improvised the content of About us and my PR got merged. But due to a merge conflict, the old content was not removed and its still there and the content seems too long. SO I have resolved that in this PR.

**Comment by aastha621** [comment]
> I'm not able to get it, what changes did you do here?
> were there any mistakes in about us section?
See, the content should be just this much-

**Review by urvashi-code1255 — APPROVED** [review]

**Pull request merged**
