### PR TITLE
Added a BMI Calculator application

### PR DESCRIPTION
**Pull request by vanshikachokhani**
### Changes made
I have created a basic javascript application for calculating BMI. 
This is a small contribution as a part of GSSoC21.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
BMICalculator

### CODE REVIEW

**Comment by vanshikachokhani** [comment]
@Vishal-raj-1 @urvashi-code1255 If there is any issue with this or require any updations please notify.
I will try to make those updations

**Review by Vishal-raj-1 — APPROVED** [review]
@vanshikachokhani Awesome Work. Thanks for your contribution... Let me in which program you are enrolled in crosswoc OR gssoc ?

**Comment by vanshikachokhani** [comment]
@Vishal-raj-1 Thanks for the approval. I am enrolled in gssoc.

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @vanshikachokhani

**Comment by vanshikachokhani** [comment]
I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted? 
Please help @991rajat @ridsuteri @ @harshgupta20

**Comment by ridsuteri** [comment]
> I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted?
> Please help @991rajat @ridsuteri @ @harshgupta20

@Vishal-raj-1 @urvashi-code1255

**Comment by ridsuteri** [comment]
> I wanted to contribute this project as a part of Gssoc'21 but was not aware of the scores counting procedure then so is there any way I can get the scores for this PR counted?
> Please help @991rajat @ridsuteri @ @harshgupta20

@vanshikachokhani since this project was added and merged before Mar 8, hence it won't be counted under Gssoc :(

**Pull request merged**
