### PR TITLE
Ghost text Project

### PR DESCRIPTION
**Pull request by aastha621**
## Related Issue
Added a new project, Ghost text.

Closes:  #1130

### Describe the changes you've made
Spooky text hover effect project.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x
ghost
 ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
Good Work.

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by 991rajat** [comment]
I've fixed the script.js and index.html conflict, it arised coz of you created branch from some other branch other than synced main branch.
Always create branch from the main branch, it will not bring any unknown commits.

**Comment by aastha621** [comment]
> I've fixed the script.js and index.html conflict, it arised coz of you created branch from some other branch other than synced main branch.
> Always create branch from the main branch, it will not bring any unknown commits.

Thankyou so much! Will take care in future :)

**Pull request merged**
