### PR TITLE
Successfully added styles and a responsive design to coinToss

### PR DESCRIPTION
**Pull request by SilverGraph**
## Related Issue
  - `NA`

Closes: #1024 

### Describe the changes you've made

- Revamped the HTML code
- Added a responsive design to the page
- Committed significant changes to the corresponding CSS file
- Added a background image
- Added new coin images
- Added useful comments to the code

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Desktop-size:
d

iPad-size:
iPad

iPhone-size:
iPhone

### CODE REVIEW

**Comment by 991rajat** [comment]
@SilverGraph Looks Great,
Just update the old gif to new one. If the size of the gif is high use a static image.
Also if possible reduce the size of game-bg.

**Comment by SilverGraph** [comment]
I have compressed game-bg to **489 KB**

I tried to compress the GIF as much as possible and finally compressed to 2.11 MB:
coinToss

**Review by 991rajat — APPROVED** [review]
Great UI. Looks Great :fire:

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. Keep Contributing.

**Pull request merged**
