### PR TITLE
Interest Calculator

### PR DESCRIPTION
**Pull request by archana-9430**
This is a Simple Interest Calculator.

## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@archana-9430 Please enable github pages in your fork and share it everytime. It will help me to review it.

**Review by Vishal-raj-1 — APPROVED** [review]
@archana-9430 Add project detail in `script.js file` .

**Comment by archana-9430** [comment]
> @archana-9430 Add project detail in `script.js file` .

Sure.

**Comment by urvashi-code1255** [comment]
@archana-9430 Any updates?

**Comment by archana-9430** [comment]
> @archana-9430 Any updates?

I've sent the PR for the same. Please either merge it or let me know if some improvements are needed.

**Comment by archana-9430** [comment]
> @archana-9430 Add project detail in `script.js file` .

I've done it. Please merge it to the main file or let me know if some more improvements are needed and close this issue :)
Thanks.

**Comment by urvashi-code1255** [comment]
@archana-9430 You haven't did any extra commit yet!

**Comment by archana-9430** [comment]
> @archana-9430 You haven't did any extra commit yet!

I've already sent the PR, how to make any extra commit?

**Comment by archana-9430** [comment]
> @archana-9430 Add project detail in `script.js file` .

@Vishal-raj-1 , I've add the project details in script.js file, do check that PR.

**Comment by archana-9430** [comment]
@urvashi-code1255 & @Vishal-raj-1 , What I'm supposed to do now?
Please reply for the same.

**Comment by urvashi-code1255** [comment]
Hey @archana-9430 Have  you made another PR? If yes then please mention its number here. I will check that out.

**Comment by archana-9430** [comment]
> Hey @archana-9430 Have you made another PR? If yes then please mention its number here. I will check that out.

#603

**Comment by archana-9430** [comment]
> > Hey @archana-9430 Have you made another PR? If yes then please mention its number here. I will check that out.
> 
> #603

@urvashi-code1255 ,  I've added the project details in the script.js file.

**Comment by Vishal-raj-1** [comment]
@archana-9430 Thanks for your contribution !!

**Comment by Vishal-raj-1** [comment]
@archana-9430 Let me know are you participating in GSSOC or not ?

**Comment by archana-9430** [comment]
> @archana-9430 Let me know are you participating in GSSOC or not ?

@Vishal-raj-1 Yes, I am a GSSoC'21 participant.

**Pull request merged**
