### PR TITLE
Added Weather App

### PR DESCRIPTION
**Pull request by pranabprohit**
## Related Issue
  - build a weather app using openweathermap api

Closes: #172  

### Describe the changes you've made
Build a weather app using openweathermap api which tell the weather of current location and of any particular location.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Weather_app

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@pranabprohit Replace the image with GIF in script.js

**Comment by pranabprohit** [comment]
> @pranabprohit Replace the image with GIF in script.js

Okk

**Comment by pranabprohit** [comment]
> @pranabprohit Replace the image with GIF in script.js

@urvashi-code1255 Done

**Review by urvashi-code1255 — APPROVED** [review]
LGTM @pranabprohit

**Pull request merged**
