### PR TITLE
Bug fix : multiple entry of projects removed

### PR DESCRIPTION
**Pull request by jhamadhav**
## Related Issue

In the file, `script.js`; where data for different projects are stored there are multiple instances of the same project.

Closes: #1060

### Describe the changes you've made

I removed the entries that had multiple instances and left only one

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by jhamadhav** [comment]
@urvashi-code1255 please review this, I have solved the issue and added my project `Fractal Tree` to it too.

**Comment by jhamadhav** [comment]
@urvashi-code1255 please merge this PR as quickly as possible before others add more stuff into `script.js` else it will clutter with more conflits

**Comment by jhamadhav** [comment]
@991rajat @urvashi-code1255  please merge this PR before more people make changes to `script.js` else it won't be able to solve the issue and make multiple merge conflicts.

**Comment by jhamadhav** [comment]
> 
> 
> Hey @jhamadhav There are many projects which aren't added. Please add it too.
> I think the number is around 166.

Yes, when I first made it, it was all good but due to delayed review, more projects got added to it.
I will fix it asap, please review for merge quicky.

**Comment by jhamadhav** [comment]
@991rajat Please review it, I have made the changes

**Comment by 991rajat** [comment]
Looks good.There is typo issue in rock-paper-scissor due to which it not links properly.
Please fix that

**Comment by jhamadhav** [comment]
@991rajat Please check I have fixed the link

**Comment by 991rajat** [comment]
Great, Looks all ok . Good work

**Pull request merged**
