### PR TITLE
Word Counter Issue solved

### PR DESCRIPTION
**Pull request by swapnilbhakare**
## Related Issue
  This issue is related with word counter project

Closes: #786
### Describe the changes you've made
I have Solved an error in the word counter project , previously it was showing the wrong number count for the words type in the input box.

 ## Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
word counter

### CODE REVIEW

**Comment by 991rajat** [comment]
For two words it work fine.
Would you be able to fix this when one word is there it shows zero.
image

**Comment by swapnilbhakare** [comment]
Yes I will

**Comment by 991rajat** [comment]
Hey @swapnilbhakare any updates ? Would you be able to fix it ?

**Comment by 991rajat** [comment]
@swapnilbhakare  Reply Otherwise I'll assign to someone else.

**Comment by neha07kumari** [comment]
@991rajat  I will be able to fix this issue. Please assign it to me.

**Comment by 991rajat** [comment]
@swapnilbhakare Wait for 24 Hrs If he didn't reply You go ahead Create a PR.

**Comment by swapnilbhakare** [comment]
i will do sir

**Comment by swapnilbhakare** [comment]
It's working correctly now even for one word.
image

**Comment by swapnilbhakare** [comment]
Its working well now.

image

**Comment by 991rajat** [comment]
Looks Good.

**Comment by 991rajat** [comment]
Keep Contributing.

**Comment by 991rajat** [comment]
@neha07kumari Will assign you something else.

**Pull request merged**
