### PR TITLE
Make calculator project response in mobile view

### PR DESCRIPTION
**Pull request by Marim99**
## Related Issue
  - Make calculator project response in mobile view

Closes: #783 

### Describe the changes you've made
I have make changes in file  calculator.css to make calculator project response in mobile view 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
###Befour 
Screenshot (167)
###Aftar 
Screenshot (3)

### CODE REVIEW

**Comment by Marim99** [comment]
@Vishal-raj-1 @991rajat  @ridsuteri  please view my PR

**Review by ridsuteri — APPROVED** [review]
good work @Marim99 ,thanks for contributing :)
and congrats on your first PR 🎉🎉

**Comment by Marim99** [comment]
thanks please can you make labels for it ,i'm participant in GSSoc 2021 @ridsuteri

**Comment by Marim99** [comment]
@ridsuteri

**Pull request merged**
