### PR TITLE
added maze game

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue-> #57 

@urvashi-code1255

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda Use PR template for description and always send the video/screenshots or you can setup this repository on your github pages and send the link for the same !!

**Comment by Sloth-Panda** [comment]
checkout the images below,

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 why I am not able to find the code files for this after updating my origin with upstream ?

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda did you commit your changes before updating your origin ?

**Pull request closed without merging**
