### PR TITLE
quiz site added

### PR DESCRIPTION
**Pull request by ridhuridhu**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by ridhuridhu** [comment]
Screenshot (226)
Screenshot (227)
Screenshot (228)
Screenshot (229)
Screenshot (230)
Screenshot (231)

**Comment by ridhuridhu** [comment]
[ checkout site here ](https://ridhuridhu.github.io/Spider_Covid_Quiz/)

**Review by Vishal-raj-1 — COMMENTED** [review]
@ridhuridhu This is awesome Project. Although I have some suggestion but for now just add this project on the main website as well. I mean add card for this project in index.html file.

**Comment by ridhuridhu** [comment]
hey, accidentally I've deleted the fork repo. So currently I'm not able to make any changes in index.html. so you can merge the request after that I have to create a new pull request

**Pull request closed without merging**
