### PR TITLE
added url shortener

### LINKED ISSUE #62: Creation of url shortener
## Is your feature request related to a problem? Please describe.
Creation of url shortener
## Describe the solution you'd like
This js code will be able to make shorter the provided link
## Additional context
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by Sloth-Panda**
## Related Issue
  - Info about Issue or bug
fixes #62 
### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Added a url shortener that makes short any url u provide ny using TinyUrl
### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
No unusal behaviour
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot (135)

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@urvashi-code1255  @Vishal-raj-1

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda write "fixes #62" and remove other text in front of fixes!!

**Comment by urvashi-code1255** [comment]
@Sloth-Panda Resolve the merge conflicts

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 resolved but I am not getting it why these conflicts are coming again and agian without me pullling code from upstream? is it because u have merged code in the meanwhile?

**Comment by urvashi-code1255** [comment]
Yes @Sloth-Panda It's because I have merged some code related to your files meanwhile

**Comment by Sloth-Panda** [comment]
https://sloth-panda.github.io/Awesome-JavaScript-Projects/   This is the link @urvashi-code1255 in case you want to check Its giving a 404 rn though

**Pull request closed without merging**
