### PR TITLE
Calculator UI

### PR DESCRIPTION
**Pull request by mohammedjameel24**
## Related Issue
  - improved calculator UI
Closes: #272 

### Describe the changes you've made
UI changes 
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
please merge @ridsuteri

**Comment by 991rajat** [comment]
image
Don't Look anything like what you shared. Is this happening on my side only.

**Comment by mohammedjameel24** [comment]
Clear cookies of your browser its fine with me

**Comment by 991rajat** [comment]
Send the screenshot. I don't get it what is with cookies will fix it. I tried nothing happend.

**Comment by 991rajat** [comment]
Also why memeUrl, index.html is pushed.
Only push what you changed

**Comment by 991rajat** [comment]
If it's happening on my side, send me screen shot ?
Please fix it and Also why memeUrl, index.html is pushed.

**Comment by mohammedjameel24** [comment]
I tried makeing a new branch but again the previous commits are also being pushed

**Comment by 991rajat** [comment]
@mohammedjameel24 I think you code is not sync with main branch,
What you could do is pull the main branch
Create a branch from there
Add the code 
And push it.

**Comment by mohammedjameel24** [comment]
Ok

**Comment by 991rajat** [comment]
Make a new PR, it will be easy, and close this one.

**Pull request closed without merging**
