### PR TITLE
Typing speed Game

### PR DESCRIPTION
**Pull request by nidhivanjare**
## Related Issue
  - Add a new js project 

Closes: #839 

### Describe the changes you've made
Add a javascript project for typing speed and practice. 

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Screenshot 2021-04-07 at 4 01 44 PM
Screenshot 2021-04-07 at 3 59 04 PM

### CODE REVIEW

**Comment by nidhivanjare** [comment]
@Vishal-raj-1 please view my PR

**Comment by nidhivanjare** [comment]
@ridsuteri please view my PR

**Comment by ridsuteri** [comment]
sorry @nidhivanjare this project is already available in the repo ,so i am closing the PR :(

**Comment by nidhivanjare** [comment]
The project that already exist is for word and my project consists of sentences.

**Comment by ridsuteri** [comment]
so sorry @nidhivanjare :( , i am reopening the issue and the PR

**Review by ridsuteri — APPROVED** [review]
good work @nidhivanjare ,thanks for contributing :)

**Pull request merged**
