### PR TITLE
Created Infinite Scrolling Image Library using Unsplash API #522

### PR DESCRIPTION
**Pull request by PrathmeshSadake**
## Related Issue
  - Infinite Image Gallery

Closes: #522

### Describe the changes you've made
An image gallery which fetches images from unsplash api. It has awesome feature like  infinite scrolling in which images keeps on loading as user scrolls.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
Add the project to script.js. Also remember don't create big size gif for the project. Reduce the size of the gif too.

**Comment by harshgupta20** [comment]
@PrathmeshSadake Please don't commit on main branch. create a separate branch for your PR.

**Comment by PrathmeshSadake** [comment]
@991rajat @harshgupta20 @urvashi-code1255 Completed all required changes. Also added gif and project in script.js

**Comment by 991rajat** [comment]
@PrathmeshSadake I'm not able to see the changes, its not visible here. Look into it.

**Comment by 991rajat** [comment]
Don't push both these files .DS_Store  
just remove them from local and push.

**Review by PrathmeshSadake — COMMENTED** [review]
Added project in script.js along with Gif in assets folder

**Comment by PrathmeshSadake** [comment]
> @PrathmeshSadake I'm not able to see the changes, its not visible here. Look into it.
https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/742/commits/9d1fe03f59dcfbc5b5537572e8772902bb2b7b71

**Comment by 991rajat** [comment]
Hey Projects work fine, Good work
Just few changes 
Size of the gif is too much 7.82 MB, reduce it if it can't be made under 1 MB, replace it with static image.
And remove DS_STORE files,

**Comment by PrathmeshSadake** [comment]
> Hey Projects work fine, Good work
> Just few changes
> Size of the gif is too much 7.82 MB, reduce it if it can't be made under 1 MB, replace it with static image.
> And remove DS_STORE files,

@991rajat @harshgupta20 @synox @urvashi-code1255  Completed

**Comment by 991rajat** [comment]
Fix the image path, It's Images.
Also reduce the size of png, don't put high resolution photo, as it just shown in small screen.

**Comment by PrathmeshSadake** [comment]
> Fix the image path, It's Images.
> Also reduce the size of png, don't put high resolution photo, as it just shown in small screen.

@991rajat  Done👍

**Comment by 991rajat** [comment]
Good Work. Looks Great

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. Keep Contributing.

**Pull request merged**
