### PR TITLE
Adding Colora

### PR DESCRIPTION
**Pull request by rupal11**
## Related Issue
  - Info about Issue or bug
  - No bug
  
Closes: #[issue number that will be closed through this PR]
#1025

### Describe the changes you've made
I have added a new project. It is similar to paint.I n this we can draw, change brush color, brush size, background-color, clear and save the file.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

##
# Screenshots
Put any screenshot(s) of the project here.

colora

### CODE REVIEW

**Comment by 991rajat** [comment]
Add the project to script.js. Reduce the size of the gif. If not able to do reduce the duration and resolution, try again. If not able tow work replace it with static image.
Make the gif under 500KB or so.

**Comment by rupal11** [comment]
Done!

**Comment by 991rajat** [comment]
Looks Good.

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Thank you for this awesome contribution.  :star_struck: 
Keep Contributing.

**Comment by rupal11** [comment]
Thank you.

**Pull request merged**
