### PR TITLE
currency convertor added

### PR DESCRIPTION
**Pull request by Sapna2001**
## Related Issue
Closes: #208

### Describe the changes you've made
Made a currency convertor

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot from 2021-03-09 10-34-44

@Vishal-raj-1 @urvashi-code1255  please review this and let me know if any change is there. I am a GSSOC'2021 participant so please add the relevant labels.

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@Sapna2001 please add your project details in script.js like the other projects

**Comment by Sapna2001** [comment]
@urvashi-code1255 I have made the changes.

**Review by urvashi-code1255 — COMMENTED** [review]
@Sapna2001 Please check the website locally after your changes. I am not able to see all the projects.

**Comment by Sapna2001** [comment]
@urvashi-code1255 which projects are you not able to see? Currency Convertor or some other project?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 which projects are you not able to see? Currency Convertor or some other project?

None of the projects

**Pull request closed without merging**
