### PR TITLE
fixed UI Calculator

### PR DESCRIPTION
**Pull request by mohammedjameel24**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
@mohammedjameel24 Please use separate branches for different feat.
You Added two different PR's in one. Create a separate branch for UI calculator add the code there and then make a PR.

Also remember to squash the commits before pushing

**Review by 991rajat — COMMENTED** [review]
@mohammedjameel24 Please use separate branches for different feat.
You Added two different PR's in one. Create a separate branch for UI calculator add the code there and then make a PR.

Also remember to squash the commits before pushing

**Comment by mohammedjameel24** [comment]
> @mohammedjameel24 Please use separate branches for different feat.
> You Added two different PR's in one. Create a separate branch for UI calculator add the code there and then make a PR.
> 
> Also remember to squash the commits before pushing

How do i delete the latest commits from this branch?

**Comment by 991rajat** [comment]
@mohammedjameel24 Just pull the latest changes in main > create a new branch > add your code to it.
This way will be easy rather than deleting the commits.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@mohammedjameel24 there are many conflicts in the PR,please resolve them

**Pull request closed without merging**
