### PR TITLE
Todo-App

### PR DESCRIPTION
**Pull request by pragati-kumar**
## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
Screenshot 2021-04-14 at 4 08 59 AM
Screenshot 2021-04-14 at 3 40 38 AM

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@pragati-kumar what is this .DS_store doing?

Remove these if these are unncessary.

**Comment by pragati-kumar** [comment]
> @pragati-kumar what is this .DS_store doing?
> 
> Remove these if these are unncessary.

They were used to ensure responsiveness in Mac. I'll use gitignore to get rid of them right away.

**Review by ridsuteri — APPROVED** [review]

**Comment by ridsuteri** [comment]
good work @pragati-kumar , thanks for contributing :)

**Comment by pragati-kumar** [comment]
> good work @pragati-kumar , thanks for contributing :)

Thank you so much!

**Pull request merged**
