### PR TITLE
Movie Search App #304

### PR DESCRIPTION
**Pull request by SatyaPrakash26**
## Movie Search App
  - Created and Added Movie Search App

Closes: #304 

### Describe what you have made
I have used OMDB API to fetch data and displaying the data on my site .
Functionalities:
We can search for any movie with their names.
We can get the entire information about the movie.
We can go to the IMDb of the particular movie by clicking on the link.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

### Screenshots
preview

### CODE REVIEW

**Comment by SatyaPrakash26** [comment]
@991rajat do I need to fork the file again . Will deleting the files from the local machine affect the already merged PRs??

**Comment by 991rajat** [comment]
@SatyaPrakash26 No deleteing files of already merged PR's will not affect our code.
I think what you did is you created a branch from another feature branch in this case i believe from food -> moviesearch
Always create branch from main and keep the main branch synced so that you get latest changes.
Easiest way to fix this is create a new branch from main (Sync the main before creating a branch)
Add the code of movieserach in new branch you created and Push and make new PR.

Otherway around will requires you to not push whatever files which aren't required in this project 
In this case food project all files and fruitslicer flies.

Let me know if need any help. Creating a new PR will be fast and easy.

**Comment by 991rajat** [comment]
If you go with creating a new PR. Close this one.

**Comment by SatyaPrakash26** [comment]
thank you so much for helping . I will create a new PR .

**Pull request closed without merging**
