### PR TITLE
added music player app

### PR DESCRIPTION
**Pull request by Sloth-Panda**
correponds to issue-> #56 

@urvashi-code1255

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@urvashi-code1255  how are you keeping track of the prs and points for a participant of this project?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 how are you keeping track of the prs and points for a participant of this project as part of crossWoc?

@Sloth-Panda After a PR gets merged, your name and pr points will be added to the contributors.md

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda please add a demo video in both of the prs

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I guess its better to add images as video files can be large even if they are from 10-20 seconds or more and it will unnecesarily increase the file size

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda I am not saying to add the image or video in the project. I am saying to show the demo here like either a Google drive link or something

**Comment by Sloth-Panda** [comment]
https://sloth-panda.github.io/MusicPlayer/

@urvashi-code1255 you can checkout this from here

**Comment by urvashi-code1255** [comment]
@Sloth-Panda It looks good to me. Please add a card for this project like other projects in main index.html file

**Comment by Sloth-Panda** [comment]
> @Sloth-Panda It looks good to me. Please add a card for this project like other projects in main index.html file

did not get what card means?

**Comment by Sloth-Panda** [comment]
@urvashi-code1255  I am thiniking of making a separate repo where i will be uploading js projects that i will be submitting and you can then test the code from there by cloning the repo to your system

**Comment by urvashi-code1255** [comment]
> did not get what card means?

@See the website once, in that each project is opened by clicking on its card. I m saying to add a card for this project too

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255  I am thiniking of making a separate repo where i will be uploading js projects that i will be submitting and you can then test the code from there by cloning the repo to your system

You can share the GitHub hosted link like this.

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 I will have to unnecessarily make a lot of repos then as for one repo there can be one hosted project and thats the index one

**Comment by Sloth-Panda** [comment]
Screenshot (112)
what is up with the website ?

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 I will have to unnecessarily make a lot of repos then as for one repo there can be one hosted project and thats the index one

@Sloth-Panda You can simply share a video here.. GitHub supports videos

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 there is something super wrong with the index page
and the website is developed poorly
Screenshot (113)

**Comment by urvashi-code1255** [comment]
> @urvashi-code1255 there is something super wrong with the index page
> and the website is developed poorly
> Screenshot (113)
> 

@Sloth-Panda I will take a look on it...

Till then can you have a look what happened?

**Comment by Sloth-Panda** [comment]
@urvashi-code1255 anyway I have added the card of this music player app to the website , you can merge

**Comment by Vishal-raj-1** [comment]
@Sloth-Panda You don't need to make video or screenshots or to make lot of repos, You can just enable github pages on your forked repo, and then you can send the github pages link.

**Comment by urvashi-code1255** [comment]
Hey @Sloth-Panda Check your branch its having bugs in it!! I have sorted that bug present in the website. But its present in your PR so I can't merge it!! Remove the bugs

**Comment by Sloth-Panda** [comment]
Yes I see I have solved the issue

**Comment by urvashi-code1255** [comment]
> Yes I see I have solved the issue

@Sloth-Panda Resolve the merge conflicts!!

**Comment by Sloth-Panda** [comment]
Screenshot (114)

Its fine now

**Comment by urvashi-code1255** [comment]
Capture

These!! @Sloth-Panda

**Comment by Sloth-Panda** [comment]
Hey, I dont have a write access as you can see anyway I am closing this pr and making another for the same

**Comment by urvashi-code1255** [comment]
> Hey, I dont have a write access as you can see anyway I am closing this pr and making another for the same

hey you can click on resolve conflicts!! @Sloth-Panda

**Comment by Sloth-Panda** [comment]
Screenshot (115)

It says I dont have write access

**Comment by Sloth-Panda** [comment]
PR-> #72 , I am closing this you can merge this pr

**Pull request closed without merging**
