### PR TITLE
Added my dinosaur video game in the projects section

### PR DESCRIPTION
**Pull request by RiyaGupta89**
## Related Issue
  - <b>Added my dinosaur game in the projects section</b>

Closes: #1782

### Describe the changes you've made
I've added a new game in the projects section using JavaScript.

### Describe if there is any unusual behaviour of your code
NA

### Checklist:

- [✔️] My code follows the style guidelines of this project.
- [✔️] I have performed a self-review of my own code.
- [✔️] I have commented my code, particularly in hard-to-understand areas.
- [✔️] I have made corresponding changes to the documentation.
- [✔️] New and existing unit tests pass locally with my changes.

### Screenshots
dino-game

### CODE REVIEW

**Comment by RiyaGupta89** [comment]
I've added my game. Please have a look at it.

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
Everything looks good, but follow the structure of the projects. Make individual .html, .css, and js file. (doesn't matter how much lines of code in it)

**Comment by RiyaGupta89** [comment]
@Vishal-raj-1 But there are no individual .html, .css, .js file for projects. Everything is included in one file in the code.

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 But there are no individual .html, .css, .js file for projects. Everything is included in one file in the code.

I mean you have to make individual file and place html file in public folder and css, js file in assest folder of the repository

**Comment by Ankita297** [comment]
@RiyaGupta89 Please resolve the conflicts and make separate file for html css and js part . See the pattern of other  projects

**Comment by Vishal-raj-1** [comment]
@RiyaGupta89 ??

**Comment by RiyaGupta89** [comment]
@Vishal-raj-1 Yes, I've made the changes.

**Pull request closed without merging**
