### PR TITLE
Updated Infix Evaluator

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed issue #1186 

- [x] Updated its UI
- [x] Added reset button to reset the text entered
- [x] Made site responsive

Screenshot:
Now:
infix-new

Please view my PR  @Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri @991rajat

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Bhavya-Sehgal kindly update the gif/image in the script file

**Comment by Bhavya-Sehgal** [comment]
@ridsuteri  gif file updated. Kindly check it now.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@Bhavya-Sehgal kindly remove restaurant images

**Comment by Bhavya-Sehgal** [comment]
@ridsuteri done.

**Comment by 991rajat** [comment]
@Bhavya-Sehgal Still Restaurant Images are there. Please remove it.

**Comment by Bhavya-Sehgal** [comment]
Please check now @ridsuteri @991rajat

**Comment by 991rajat** [comment]
Looks Good.

**Comment by 991rajat** [comment]
Thanks for contributing.
Keep Contributing.

**Pull request merged**
