### PR TITLE
Final Commit

### PR DESCRIPTION
**Pull request by nidhivanjare**
The code for script.js

## Related Issue
  - The project was not visible as the code for it was not added in the script.js 
  - I have made necessary changes Please take a look

Closes: #839 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by nidhivanjare** [comment]
Can You please merge this PR ?

**Review by urvashi-code1255 — APPROVED** [review]

**Comment by urvashi-code1255** [comment]
@nidhivanjare Please resolve the merge conflicts and I will merge it :)

**Comment by nidhivanjare** [comment]
Done!!

**Comment by nidhivanjare** [comment]
Hey, I have resolved the issues!

**Review by urvashi-code1255 — APPROVED** [review]

**Pull request merged**
