### PR TITLE
Search suggestions

### PR DESCRIPTION
**Pull request by akshay399**
## Related Issue
  - I added suggestions to the search bar for projects.

Closes: #1341

### Describe the changes you've made
I added a search suggestion to the search bar that directs to the project when clicked

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@akshay399 please resolve the merge conflicts

**Comment by Ankita297** [comment]
@akshay1027 Please resolve merge conflicts

**Comment by akshay1027** [comment]
Hey @Ankita297 you have tagged the wrong person, it's @akshay399 I guess

**Comment by Ankita297** [comment]
Sorry @akshay1027 .

**Pull request closed without merging**
