### PR TITLE
Calculator UI

### PR DESCRIPTION
**Pull request by mohammedjameel24**
## Related Issue
  - improved calculator UI
Closes: #272 

### Describe the changes you've made
UI changes 
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
@991rajat

**Comment by 991rajat** [comment]
I told you to sync the main branch and create a new branch from that, 
Did you do it?
There are lot of files changed which I believe were not required in changing UI of calculator.

**Comment by mohammedjameel24** [comment]
Yes i did it 
`git checkout -b CalcUI`
`git pull`

Changes 

`git push-upstream--main`

What else?

**Comment by 991rajat** [comment]
Copy the code somewhere else for bubble sort.
I mean In local
git checkout main
git pull 
git checkout -b new_branch
add the code
git commit
and then push and make PR
This way unncessary changes will not be pushed.

**Comment by 991rajat** [comment]
Hey @mohammedjameel24 Any updates? Are you able to fix it? Let me know if need any help

**Pull request closed without merging**
