### PR TITLE
Adding favicons

### LINKED ISSUE #86: Website Favicon
Design favicons for the website and show the demo here before making  a PR!!

### PR DESCRIPTION
**Pull request by kanishkaa24**
Closes #86 
Adding 6 favicons in the assets folder.  @urvashi-code1255 Mam please review.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@kanishkaa24 You have just upload all fevicon, You have to use fevicon number 3 as mention in #86 as fevicon. Means you have to add `<link rel="icon" href="{path of fevicon number 3}">` in the `<head></head>` of the index.html file.

**Comment by kanishkaa24** [comment]
> @kanishkaa24 You have just upload all fevicon, You have to use fevicon number 3 as mention in #86 as fevicon. Means you have to add `<link rel="icon" href="{path of fevicon number 3}">` in the `<head></head>` of the index.html file.

I am so sorry I got a bit confused.

**Comment by Vishal-raj-1** [comment]
I want this fevicon for now. You can see [this](https://stackoverflow.com/questions/9943771/adding-a-favicon-to-a-static-html-page) to add fevicon on this website.
fevicon

**Comment by kanishkaa24** [comment]
> I want this fevicon for now. You can see [this](https://stackoverflow.com/questions/9943771/adding-a-favicon-to-a-static-html-page) to add fevicon on this website.
> fevicon

Sir urvashi mam asked to put all these in the assets folder. What should I do overall?

**Comment by Vishal-raj-1** [comment]
@kanishkaa24 I mean upload all in folder but set 3rd as fevicon.

**Comment by kanishkaa24** [comment]
I have added this Sir, please review.

**Pull request merged**
