### PR TITLE
Footer changed of home page

### PR DESCRIPTION
**Pull request by sheetalj2205**
## Related Issue
  - footer changed of home page

Closes: 1224

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
@sheetalj2205 Can you make footer of full width.

**Comment by 991rajat** [comment]
Like in Contact Section:
image

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Can you make footer of full width.

now check

**Comment by 991rajat** [comment]
@sheetalj2205 Now it's floating. Use style what contact section has.
image

**Comment by 991rajat** [comment]
@sheetalj2205 Any Updates?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Any Updates?

I will complete it today.

**Comment by sheetalj2205** [comment]
Actually, the problem is I am not able to clone this repository don't know why but it is not working. That's why I made all the changes directly on github.

**Comment by sheetalj2205** [comment]
Check this PR , now the problem is solved

**Review by 991rajat — APPROVED** [review]
Looks Great. Good Work

**Comment by sheetalj2205** [comment]
I didn't receive marks for this PR.

**Comment by sheetalj2205** [comment]
Please assign this PR to me.

**Pull request merged**
