### PR TITLE
 BMI Calculator UI change [gssoc'21]

### PR DESCRIPTION
**Pull request by ishita-sehgal**
## Related Issue
 - on submitting on empty fields the div content moved out
 - the margin and aligning 
 - placeholders in fields were not there and fields were not clearing out after submit

Closes: #259 

### Describe the changes you've made
I rectified the above issues and made the UI a little better looking with added styling.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
BMIcal

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@ishita-sehgal Please pull the recent changes!

**Comment by ishita-sehgal** [comment]
I have pulled the recent changes till now.

**Review by urvashi-code1255 — COMMENTED** [review]
@ishita-sehgal Please change the image of your project to GIF.

**Comment by ishita-sehgal** [comment]
@urvashi-code1255 , I have changed the image to gif.

**Review by urvashi-code1255 — APPROVED** [review]
thanks for contributing @ishita-sehgal :)

**Comment by ishita-sehgal** [comment]
@urvashi-code1255, @991rajat, can you pls add the latest gssoc21 label instead of gssoc'21 so that its score gets counted in leaderboard.

**Comment by ishita-sehgal** [comment]
@991rajat can u pls add the latest gssoc21 tag .

**Comment by 991rajat** [comment]
Thanks for reminding.

**Pull request merged**
