### PR TITLE
I have created a folder and made some changes to add some functions.

### PR DESCRIPTION
**Pull request by ArkajyotiChakraborty**
## Related Issue
  - I have added some functions created my own Css file.

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
There were some basic functions that were present i added few more functions to make the calculator more functionable and can be used in many areas. I have used my own Css file and made significant changes in HTML file and Javascript file.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Screenshots:
Here is a Screenshot of my project. 
image

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
Hey @ArkajyotiChakraborty Please add a card for your Project in index.html like other projects!

**Review by Vishal-raj-1 — COMMENTED** [review]
@ArkajyotiChakraborty Please follow the Structure of this Project. Put html file, css file and javascript file at their place. and put one card on the main website so that anyone can use your projects as well.

**Comment by ArkajyotiChakraborty** [comment]
Extremely sorry sir, I'm new to github and only knew this way of creating a new branch and adding it. I will make the following changes by tomorrow.

**Review by Vishal-raj-1 — COMMENTED** [review]
@ArkajyotiChakraborty everything look perfect to me !! You can add one card for this project in index.html so that we can use this project. Also enable github pages for your forked repo so that you can see your changes locally and We can see your changes without merging as well.

**Comment by ArkajyotiChakraborty** [comment]
image

why it's showing conflicts as i added the card component in the index.html file.

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by ArkajyotiChakraborty** [comment]
Thanks for the approval, is there anything i more need to do like taking any screenshots or it's dealt by you.

thanks for giving me this opportunity means a lot.

**Pull request merged**
