### PR TITLE
Tv search show

### PR DESCRIPTION
**Pull request by sejalxz**
## Related Issue
  - Added TV Show Search Project

Closes: #501 

### Describe the changes you've made
* I added the necessary JavaScript, HTML and CSS files for my TV Show Search project.
* Updated script.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Tv_Show_Search

### CODE REVIEW

**Comment by sejalxz** [comment]
@991rajat I have made the changes please look into it.

**Review by 991rajat — APPROVED** [review]
Great Work :tada:

**Comment by 991rajat** [comment]
Congratulations on merging of first PR :tada: 
Keep Contributing.

**Comment by sejalxz** [comment]
@991rajat Thank you so much! I surely will.

**Pull request merged**
