### PR TITLE
Added a new project - movie seat booking

### LINKED ISSUE #581: Add Movie Seat Booking
<h1>Movie Seat Booking</h1>
Movie Seat Booking is a vanilla javascript project.

<h2>Functionalities:</h2>

1. Pick a movie
2. Select available seat
3. See the total selected seat number
4. See the total ticket price

### PR DESCRIPTION
**Pull request by Bhavyal9**
Fixed #581

## Related Issue
  - Added a new project

Closes: #581 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
[
Screenshot (12)
](URL)

[
Screenshot (14)
](url)

### CODE REVIEW

**Comment by Bhavyal9** [comment]
hello @ridsuteri @Vishal-raj-1 @Alik-Kumar-Ghosh @urvashi-code1255 please review my pull request, it'll be my first PR under GSSOC'21

**Comment by Bhavyal9** [comment]
@ridsuteri Thank you for reviewing my pr. This is the new PR I created for my project. Please look into this.

**Review by ridsuteri — APPROVED** [review]
good work @Bhavyal9 :) thanks for contributing

**Comment by ridsuteri** [comment]
@Bhavyal9 congrats on your first contribution 🎉🎉

**Pull request merged**
