### PR TITLE
Love calculation

### PR DESCRIPTION
**Pull request by EkjotKaur**
Fixed: #712 

## When trying to calculate without filling values

PR-5-1

## When we calculate it with values
- It shows the result and displays try again button.
- Doesn't shows the inputs
- When try again is clicked it shows inputs again. 

PR-5-2

@991rajat @Vishal-raj-1 @urvashi-code1255 Please view this PR.

### CODE REVIEW

**Comment by EkjotKaur** [comment]
@991rajat @Vishal-raj-1 @urvashi-code1255 Please view this PR.

**Comment by EkjotKaur** [comment]
@991rajat @Vishal-raj-1 @urvashi-code1255 Please view this PR.

**Review by 991rajat — APPROVED** [review]
Good Work

**Comment by 991rajat** [comment]
Keep Contributing.

From next time pull latest changes in main branch and create a branch from main.
I believe this way the merge commit will not occur.

**Pull request merged**
