### PR TITLE
Added Project Random Color Generator

### PR DESCRIPTION
**Pull request by jainaayush01**
## Related Issue
  - Issue #466 

Closes:#466 

### Describe the changes you've made
I have added three files for the project (HTML, css, js and png)

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@jainaayush01 Resolve the merge conflicts

**Comment by jainaayush01** [comment]
Okay

**Comment by jainaayush01** [comment]
@urvashi-code1255 have a look!

**Comment by jainaayush01** [comment]
@urvashi-code1255

**Comment by jainaayush01** [comment]
Add GSSoC labels as well

**Comment by jainaayush01** [comment]
@Vishal-raj-1, Kindly check this PR i have resolved the conflicts as of now.

**Comment by 991rajat** [comment]
@jainaayush01 Please squash the commits.
Let me know if you need any help.

**Comment by jainaayush01** [comment]
Is this okay?
@991rajat 
I don't know about squashing it will be helpful if you can help me if it isn't correct.
Thanks

**Review by 991rajat — APPROVED** [review]
Great Work

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing.

**Pull request merged**
