### PR TITLE
Adding waves to color-flicker project

### PR DESCRIPTION
**Pull request by syamala27**
## Related Issue
`NA`

## Describe the changes you've made
- I have added a Waveform to the color-flicker project, have updated the `HTML` file added the `css` file and updated **_GIF_**

## Describe if there is any unusual behaviour of your code
- `NA`

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots

- Before adding the effect
## color-flicker old

- after adding the effect.
## color-flicker

@ridsuteri  @urvashi-code1255  @991rajat  , guide me if any changes are needed image

### CODE REVIEW

**Comment by syamala27** [comment]
@ridsuteri  sir I have updated the HTML as well as gif please verify it :)

**Comment by syamala27** [comment]
@ridsuteri  sir is there still any change I need to do , as  my **_PR_** still not been merged. 
please guide me sir if any changes are needed.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@syamala27 kindly resolve the merge conflicts

**Comment by syamala27** [comment]
@ridsuteri  sir,  now I have resolved the conflicts. please verify it :)

**Comment by ridsuteri** [comment]
@syamala27 project's gif is missing in script file.add that too

**Review by ridsuteri — APPROVED** [review]
thanks for contributing @syamala27 !

**Pull request merged**
