### PR TITLE
Added memorycards

### PR DESCRIPTION
**Pull request by nagasaisriya**
## Related Issue
  - Info about Issue or bug : Added a new project 

Closes: #[issue number that will be closed through this PR]
#337 

### Describe the changes you've made
I've added a project Memory cards.
Memory Cards is a Flash card app for learning, features-display, add and remove memory cards with questions and answers.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by nagasaisriya** [comment]
Hey @urvashi-code1255  do review my pr #440

**Comment by urvashi-code1255** [comment]
@nagasaisriya Resolve the merge conflicts

Pull the recent changes

Link the respective issue in the PR template

**Comment by nagasaisriya** [comment]
Yeah, would look into it, Thank you.

**Comment by nagasaisriya** [comment]
Hey, @urvashi-code1255 can you help me with adding images to the folder ?

**Comment by 991rajat** [comment]
@nagasaisriya Add the project to script.js.
Let me know if you need any help. Happy to help!

**Comment by nagasaisriya** [comment]
> @nagasaisriya Add the project to script.js.
> Let me know if you need any help. Happy to help!

I've added the project to script.js and made a commit, but still it does not resolve the conflicts, can you please help about it, also do we need to add images to the assets folder? @991rajat Thanks in advance!

**Comment by 991rajat** [comment]
Yes add the gif to asset as add to script.js 
So that it will be visible in the project section.

For resolving the conflict what you need to do is to accept both the changes
learn about resolving conflict 
code are seprated by symbols like this {<,>,=} just remove these means accept all changes
Let me know if need help.

One thing More
What squashing does is it combines multiple commits into single commit removing unnecessary commits and add descriptive message. what you need to do is to squash them into one
squash only your 10 commits into one.
https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc
Let me know if need any help.

**Comment by 991rajat** [comment]
Just add your project to script.js.

**Comment by urvashi-code1255** [comment]
@nagasaisriya Any updates?

**Comment by nagasaisriya** [comment]
> @nagasaisriya Any updates?

I saw that already one of the participants implemented the same flip cards and its in the website too, so you can close this😔
Thanks

**Comment by 991rajat** [comment]
We are sorry for not able to respond quickly.
There are plenty of things can be added or modified within Awesome JS Project. Feel free to checkout.
Create or comment on any issue, will be happy to assign you.

**Pull request closed without merging**
