### PR TITLE
Javascript Dragon Game #452

### PR DESCRIPTION
**Pull request by aliya-rahmani**
## Related Issue
  Javascript Dragon Game, I

Closes: #452 

### Describe the changes you've made
I've made a fun dragon game with javascript. t's a dragon game with audio effects and simple UI. Made with HTML, CSS, and Javascript.

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by ridsuteri** [comment]
hey @aliya-rahmani kindly provide description along with PR ,follow PR template under .github folder

**Comment by aliya-rahmani** [comment]
@ridsuteri  Done!

**Comment by ridsuteri** [comment]
@aliya-rahmani also attach necessary screenshots/gifs if possible

**Review by ridsuteri — CHANGES_REQUESTED** [review]
please use seperate branch to add this project and also add this project to script.js in the root level

**Pull request closed without merging**
