### PR TITLE
added student marks calculator project...pls review it

### PR DESCRIPTION
**Pull request by bishalshaw-164**
## Related Issue
  - Add student marks calculator

Closes: #503 

### Checklist:
- [✔ ] My code follows the style guidelines of this project.
- [ ✔] I have performed a self-review of my own code.
- [ ✔] I have commented my code, particularly in hard-to-understand areas.
- [ ✔] I have made corresponding changes to the documentation.
- [✔ ] New and existing unit tests pass locally with my changes.

### Screenshots
studentCalc

### CODE REVIEW

**Comment by bishalshaw-164** [comment]
@Vishal-raj-1 @urvashi-code1255  pls review my PR and guide me if any changes are needed

**Comment by 991rajat** [comment]
@bishalshaw-164 Number more than 100 can be inserted due to which percentage goes beyond 100 fix that please.

**Comment by 991rajat** [comment]
@bishalshaw-164 Number more than 100 can be inserted due to which percentage goes beyond 100 fix that please.

**Comment by Vishal-raj-1** [comment]
@bishalshaw-164 updates ?

**Comment by bishalshaw-164** [comment]
@Vishal-raj-1  done review it

**Comment by 991rajat** [comment]
image
Allow to enter only number under 100

**Comment by bishalshaw-164** [comment]
Okay wait

**Comment by bishalshaw-164** [comment]
@991rajat done review it 😇😇

**Review by 991rajat — APPROVED** [review]
Good Work

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing.

**Comment by bishalshaw-164** [comment]
@991rajat  thanku it means a lot to me🤩🤩😍

**Pull request merged**
