### PR TITLE
Shopping cart added based on rock band

### PR DESCRIPTION
**Pull request by bug-debug-done**
## Related Issue
  - Info about Issue or bug

Closes: #792 

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by 991rajat** [comment]
1. Add the project to script.js
2. Reduce the size of the gif. If not able to do reduce the duration and resolution, try again. If not able tow work replace it with static image.
Make the gif under 500KB or so.

**Comment by bug-debug-done** [comment]
@991rajat I have made the change but now it is showing that i have deleted the files what should i do

**Comment by 991rajat** [comment]
@bug-debug-done Which Files ?
Add the project to script.js

**Comment by bug-debug-done** [comment]
> @bug-debug-done Which Files ?
> Add the project to script.js

I made the changes and after that when I checked git status it showed that the files are deleted

**Comment by bug-debug-done** [comment]
@991rajat @ridsuteri  done with the changes please have a look

**Comment by bug-debug-done** [comment]
@ridsuteri resolved the confilct

**Comment by bug-debug-done** [comment]
@991rajat hey can you please review this pr

**Comment by 991rajat** [comment]
@bug-debug-done Looks Great. Just reduce the size of the gif. If not able to make it under 1MB replace it with static image.
Let me know I'll merge it right awaty.

**Comment by bug-debug-done** [comment]
@991rajat ok

**Comment by 991rajat** [comment]
Let me, when you are done with the changes.

**Comment by bug-debug-done** [comment]
@991rajat I am trying to update the repo but not able to I am grtting " failed to push some refs to 'https://github.com/bug-debug-done/Awesome-JavaScript-Projects.git'"

**Comment by bug-debug-done** [comment]
@991rajat done with every thing

**Comment by bug-debug-done** [comment]
@991rajat hey I have made the changes

**Comment by 991rajat** [comment]
Thanks for this awesome contribution. :star_struck: 
Keep Contributing.

**Comment by bug-debug-done** [comment]
@991rajat thankyou

**Pull request merged**
