### PR TITLE
Added four files related to car avoidance game project (issue-368)

### PR DESCRIPTION
**Pull request by pushpakumari5117**
## Related Issue
  - **I have created a Car Avoidance Game using javaScript.**

Closes: #368 

### Describe the changes you've made
I have added four files (Html, CSS, javascript, and an image). 
The game has features like :
* Score Board
* Movement of cars is controlled by arrow keys
* Has replay option
* UI is made using Canva

### Checklist:

- [ Done ] My code follows the style guidelines of this project.
- [ Done ] I have performed a self-review of my own code.
- [ Done ] I have commented my code, particularly in hard-to-understand areas.
- [ Done ] I have made corresponding changes to the documentation.
- [ Done ] New and existing unit tests pass locally with my changes.

### Screenshots
carAvoidanceGame1
carAvoidanceGame2
carAvoidanceGame3

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@pushpakumari5117 the project looks great !! ,can you add this project to script.js file too also
there is a conflict with bg.png in images folder under assets

**Comment by pushpakumari5117** [comment]
@ridsuteri Hey! I have changed the files. Now it has no conflicts. Have a look.

**Comment by ridsuteri** [comment]
> @ridsuteri Hey! I have changed the files. Now it has no conflicts. Have a look.

please add this project to script.js file as well

**Comment by pushpakumari5117** [comment]
@ridsuteri Hey! I have added the project to script.js file as well.....It was having some conflict , so I resolved the way I knew to resolve this.

**Comment by 991rajat** [comment]
Some of the existing projects have been removed while solving the conflict. What you need to do is to accept both changes
Please fix that. What you could do whatever project you removed add them and push
if conflict occur I'll resolve no worries.

**Comment by pushpakumari5117** [comment]
@991rajat I have added those projects which I removed earlier....Can you please resolve the conflict?

**Comment by 991rajat** [comment]
Congratulations on merging of first PR. :tada: 
Keep Contributing. :smile:

**Comment by pushpakumari5117** [comment]
@991rajat Thank you!!😊

**Pull request merged**
