### PR TITLE
Designed login and signup page

### PR DESCRIPTION
**Pull request by Muskan-creator**
## Related Issue
  - Info about Issue or bug
  - Created a signup and login page for project

Closes: #707 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Created a signup and login form in one page using sliders overlay.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
image
image

Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@Muskan-creator Resolve conflicts Please

**Comment by Muskan-creator** [comment]
@Vishal-raj-1 @Harshal0902 Please merge my PR

**Comment by 991rajat** [comment]
@Muskan-creator Is this a project or needed to be added to Awesome JS authentication, coz I'm not able to view it.

**Comment by Muskan-creator** [comment]
I have made asignup and login page for awesome javascript website

**Comment by Muskan-creator** [comment]
https://user-images.githubusercontent.com/59757988/114663752-6c7f7380-9d18-11eb-919f-964bf1c56067.mp4

**Review by urvashi-code1255 — APPROVED** [review]
Its looking good to me :)

**Pull request merged**
