### PR TITLE
Car Game Project

### PR DESCRIPTION
**Pull request by Mrinal81**
@ridsuteri  Please review it...

### CODE REVIEW

**Review by Vishal-raj-1 — COMMENTED** [review]
what this package.json file do ?

**Comment by Mrinal81** [comment]
@Vishal-raj-1  package.json file do nothing. I think by mistake it came ....I will make pr again..

**Comment by Vishal-raj-1** [comment]
dont need to make new pr. Just delete the file and do git add, commit & push

**Comment by Mrinal81** [comment]
@Vishal-raj-1 done please check once

**Review by urvashi-code1255 — COMMENTED** [review]
@Mrinal81 I like your project!!

Do resolve the merge conflicts and I will merge it :)

**Comment by Mrinal81** [comment]
@urvashi-code1255  Please have a look is it ok or not....

**Review by urvashi-code1255 — COMMENTED** [review]
@Mrinal81 Remove package.json file and why did you overwrite your project details in place of Interest calculator project?

**Comment by Mrinal81** [comment]
@urvashi-code1255  I am new on github and i don't know how to resolve conflicts because i am seeing these conflicts for the first time ..how to solve this problem.

**Comment by Mrinal81** [comment]
@urvashi-code1255 can you please tell me how to solve this...

**Comment by urvashi-code1255** [comment]
Hey, @Mrinal81 You have successfully resolved the merge conflicts.

I just want you to delete that package.json file and,
Re-add this interest calculator project details in the main script.js file.

```
{
    projectName: "JavaScript Interest Calculator",
    projectImage: "assets/Images/InterestCalculator.png",
    projectUrl: "public/InterestCalculator.html",
  },
```

**Comment by Mrinal81** [comment]
@urvashi-code1255 ok

**Comment by Mrinal81** [comment]
@urvashi-code1255 please review the new PR #1004 .....I made a new PR because during change in file by mistake i messed up everything. So i again made PR. Sorry for this Behaviour...

Please review the new PR or If everything is ok then Please merge it....

**Comment by Mrinal81** [comment]
! [rejected] main -> main (fetch first)
error: failed to push some refs to ''Mrinal81/Awesome-JavaScript-Projects"
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


I don't know about this so by mistake i messed up everything...

**Comment by 991rajat** [comment]
@Mrinal81 I'm closing this as created new PR.

**Pull request closed without merging**
