### PR TITLE
Device info

### PR DESCRIPTION
**Pull request by mohammedjameel24**
# GetLocinfo
It is a web app build on top of pure javascript which shows you your device configuration and about the network .

# Features

1. detects device os , device os version , device build properties , IP address
2. detects users gps location if the user approves to give permission 
3. Check button checks device os version and tells vulnerability.

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
@urvashi-code1255 

Please look into my PR

**Review by urvashi-code1255 — COMMENTED** [review]
@mohammedjameel24 pull the recent changes

**Comment by mohammedjameel24** [comment]
> @mohammedjameel24 pull the recent changes

Git add . && Git commit "final"

Git push -m 

And then compare and pull request ryt?

**Comment by mohammedjameel24** [comment]
done pulling recent changes please merge my request

**Comment by mohammedjameel24** [comment]
can i get any message regarding why my PR is not being merged?

**Comment by urvashi-code1255** [comment]
@mohammedjameel24 Please resolve the merge conflicts and tag me after you are done with it

**Comment by mohammedjameel24** [comment]
> @mohammedjameel24 Please resolve the merge conflicts and tag me after you are done with it 

Am not able to resolve them by mulyself please guide me

**Comment by mohammedjameel24** [comment]
all conflicts resolved @urvashi-code1255

**Comment by mohammedjameel24** [comment]
please merge my pull request @urvashi-code1255

**Comment by mohammedjameel24** [comment]
> please merge my pull request @urvashi-code1255 

@urvashi-code1255

**Review by urvashi-code1255 — APPROVED** [review]
Thanks for contributing @mohammedjameel24 :)

**Pull request merged**
