### PR TITLE
added expense tracker #290

### PR DESCRIPTION
**Pull request by vinayak0127**
## Related Issue
  - expense tracker using pure vanilla js

Closes: #290 

### Describe the changes you've made
- added expense tracker in pure vanilla js under gssoc'21 participant

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
N\A

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@vinayak0127 Add your project details in script.js like the other projects

**Comment by vinayak0127** [comment]
> @vinayak0127 Add your project details in script.js like the other projects

okay

**Comment by vinayak0127** [comment]
the weight converter is issue #341

**Comment by vinayak0127** [comment]
## Related Issue
  - Weight Converter using pure vanilla js

Closes: #341


### Describe the changes you've made
- added Weight Converter in pure vanilla js under gssoc'21 participant

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
N\A

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
image

**Comment by vinayak0127** [comment]
please review this issue

**Comment by vinayak0127** [comment]
i am getting conflicts on updating script.js
can you help

**Pull request closed without merging**
