### PR TITLE
book search project added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue
book search project added
Closes: #1726

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

https://user-images.githubusercontent.com/67833077/120094663-60703980-c13f-11eb-8b0e-0c0130a80512.mp4

Document - Google Chrome 30-05-2021 11_47_16
Document - Google Chrome 30-05-2021 11_47_53

### CODE REVIEW

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir Please review my PR .

**Comment by Vishal-raj-1** [comment]
@Ankita297 Don't Worry You will be in top 25 for sure !!

**Comment by Ankita297** [comment]
@Vishal-raj-1 Sir can you Please see PR #1378  ,the level label is 1 . If  it is possible from your site can you change the level as i 
see that every new project get level 2.

**Pull request merged**
