### PR TITLE
Maths Quiz Game #302

### PR DESCRIPTION
**Pull request by balarka135**
@Vishal-raj-1 @urvashi-code1255 
added math Quiz Game

Closes:  #302 

### Describe the changes you've made
I add the MathQuiz game files

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.

### Screenshots
MathQuiz1

### CODE REVIEW

**Review by urvashi-code1255 — COMMENTED** [review]
@balarka135 Please resolve the merge conflicts and pull the recent changes

**Comment by balarka135** [comment]
okay

**Comment by balarka135** [comment]
@urvashi-code1255  Merge conflict has been resolve and committed. 
close #302 issue
check it

**Review by 991rajat — APPROVED** [review]
Great Work! Well Done
Congratulations for the first PR 🎉 
Keep Contributing

**Comment by balarka135** [comment]
Thank you sir

**Pull request merged**
