### PR TITLE
Auto close feature added to tooltip

### PR DESCRIPTION
**Pull request by ishani02**
## Related Issue
The tooltip in the password generator had to be closed manually by clicking on the close button on top right corner.

Closes: #574 

### Describe the changes you've made
The tooltip in the password generator now closes automatically after 3 seconds. 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
NA

### CODE REVIEW

**Comment by ishani02** [comment]
I have completed the work. Kindly review it @991rajat and @urvashi-code1255.

**Comment by 991rajat** [comment]
Look good to me.
Please squash the commits.
Let me know if need any help.

**Comment by ishani02** [comment]
@991rajat I am a beginner. Can you please guide me on how to squash commits?

**Comment by 991rajat** [comment]
Hey sorry for the delay. 
What squashing does it combines multiple commits into single one. It's a good practice to squash the commits as commits represents  a fix/feat. It will be good to merge unnecessary commit message into one. Google it there are excellent resources available. I will squash the commit no problem, next time please try to do.
So Far good work.
I believe you have opened a similar PR so I'm closing this.
Will merge that one.

**Pull request closed without merging**
