### PR TITLE
Project addition : Coding jokes

### PR DESCRIPTION
**Pull request by jhamadhav**
## Related Issue

Project Coding jokes added.
A collection of amazing and funny jokes on programming.

Closes: #1221 

### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)

NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### screenshot

codingJokes

### CODE REVIEW

**Comment by jhamadhav** [comment]
@991rajat @urvashi-code1255 please review the PR.
add GSSOC and level tags

**Comment by jhamadhav** [comment]
image
It is working for me ??

**Comment by 991rajat** [comment]
Resolve the conflicts please.

**Comment by jhamadhav** [comment]
@991rajat Done

**Comment by jhamadhav** [comment]
@991rajat please review this pr for merge !

**Pull request merged**
